### ISSUE TITLE
Token和Refreshtoken调试报错

### ISSUE THREAD

**Issue by lulifa** [pure-admin/vue-pure-admin#1000]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/65484176/b8483106-d2ac-4f01-bcdb-b39bd27ccf19)
![image](https://github.com/pure-admin/vue-pure-admin/assets/65484176/64e625db-716f-45c3-8d69-4b49c19693f2)
我login后后端返回accesstoken和refreshtoken，cookiestring中没有refreshtoken，我们刷新的时候，refreshtoken是从gettoken方法中获取到的，这样我调试了下直接是报错的

### 如何复现该问题 (How to reproduce the problem)

{
    "success": true,
    "data": {
        "username": "admin",
        "roles": [
            "admin"
        ],
        "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjdDREFBRTJDQ0Q2QzMwNzJFNEQyNTg5MTQ0QTA4QTQ3QUZBQzEyNkIiLCJ4NXQiOiJmTnF1TE0xc01ITGswbGlSUktDS1I2LXNFbXMiLCJ0eXAiOiJhdCtqd3QifQ.eyJzdWIiOiIzYTExNTM5ZC1hNDFmLTZkMDYtNWQ0Ny05YTFkOTA4ZDNhZTMiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFicC5pbyIsImVtYWlsX3ZlcmlmaWVkIjoiRmFsc2UiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOiJGYWxzZSIsIm9pX3Byc3QiOiJQSE1FRV9WdWUiLCJvaV9hdV9pZCI6IjNhMTE2ODVhLWFkOWEtN2ZiZi1lNTAwLWUwZGE2YTY5NzcyYiIsImNsaWVudF9pZCI6IlBITUVFX1Z1ZSIsIm9pX3Rrbl9pZCI6IjNhMTE2ODVhLWFkYTMtNjIyYS00NmEwLTUxNThjMWZkNGUxMCIsImF1ZCI6WyJQSE1FRSIsIlBITUVFQWRtaW4iXSwic2NvcGUiOiJQSE1FRSBQSE1FRUFkbWluIG9mZmxpbmVfYWNjZXNzIiwianRpIjoiMDM2YjUyNGUtYTJhYy00Y2ViLWEwNzEtOWQ4NWFiOGNhZTk5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0NDM3NC8iLCJleHAiOjE3MTA4NDI4NDgsImlhdCI6MTcxMDg0MjgyOH0.Zow33i97KXHxKxP1MmVstSCh8hySYZe0X_76gq2aficGczZ7cih-datMRw5Lb3WNQebWU0E31wzhi3O3MQCuIwcND7TQkMmVSjhO6N9abikCWkXtcyS3PiZJ2L_1NH5zM05OLQ1xw9gy2tfJ1jFLS4vsfJWYOQ2aNkrJajKReTYXRZZUsun6JTvN8asm0yTi4MQXEaOXh7IgB-TXZWcI0PgCQ0jVCctZwQZrk6lzZFqAP0tgOBIwSab8Xk5DoQU-IwGfYOz3pwg8O6zXRKpjvunQ210g1XLuT3MonE3UsbV5GUyV4L_n7chQcBzbDI5Aqf7YV8HPji0cSm3TD09e0g",
        "accessToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjdDREFBRTJDQ0Q2QzMwNzJFNEQyNTg5MTQ0QTA4QTQ3QUZBQzEyNkIiLCJ4NXQiOiJmTnF1TE0xc01ITGswbGlSUktDS1I2LXNFbXMiLCJ0eXAiOiJhdCtqd3QifQ.eyJzdWIiOiIzYTExNTM5ZC1hNDFmLTZkMDYtNWQ0Ny05YTFkOTA4ZDNhZTMiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFicC5pbyIsImVtYWlsX3ZlcmlmaWVkIjoiRmFsc2UiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOiJGYWxzZSIsIm9pX3Byc3QiOiJQSE1FRV9WdWUiLCJvaV9hdV9pZCI6IjNhMTE2ODVhLWFkOWEtN2ZiZi1lNTAwLWUwZGE2YTY5NzcyYiIsImNsaWVudF9pZCI6IlBITUVFX1Z1ZSIsIm9pX3Rrbl9pZCI6IjNhMTE2ODVhLWFkYTMtNjIyYS00NmEwLTUxNThjMWZkNGUxMCIsImF1ZCI6WyJQSE1FRSIsIlBITUVFQWRtaW4iXSwic2NvcGUiOiJQSE1FRSBQSE1FRUFkbWluIG9mZmxpbmVfYWNjZXNzIiwianRpIjoiMDM2YjUyNGUtYTJhYy00Y2ViLWEwNzEtOWQ4NWFiOGNhZTk5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0NDM3NC8iLCJleHAiOjE3MTA4NDI4NDgsImlhdCI6MTcxMDg0MjgyOH0.Zow33i97KXHxKxP1MmVstSCh8hySYZe0X_76gq2aficGczZ7cih-datMRw5Lb3WNQebWU0E31wzhi3O3MQCuIwcND7TQkMmVSjhO6N9abikCWkXtcyS3PiZJ2L_1NH5zM05OLQ1xw9gy2tfJ1jFLS4vsfJWYOQ2aNkrJajKReTYXRZZUsun6JTvN8asm0yTi4MQXEaOXh7IgB-TXZWcI0PgCQ0jVCctZwQZrk6lzZFqAP0tgOBIwSab8Xk5DoQU-IwGfYOz3pwg8O6zXRKpjvunQ210g1XLuT3MonE3UsbV5GUyV4L_n7chQcBzbDI5Aqf7YV8HPji0cSm3TD09e0g",
        "refresh_token": "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOiI4Rjg0QjdBQjk2N0RGOEI5OTQwNUQyMEMxM0VDN0UwRDM3MzBEODg3IiwidHlwIjoib2lfcmVmdCtqd3QiLCJjdHkiOiJKV1QifQ.I4hf1xYEpEKhXBOXvixTPqtIr1wXCBI4CmJxUYG_80YdbfRIHZWmUFe-YmjBxqzyGRt7KkCsIKnPa7zQDBDEYQ4lKB72rygaPjGNfB_sD-7Jun2NvbAzv-GXmluojmi4d4vAn6nixiiHF0i2_I0Pm1tZ-6Cn9ZcPoUGB-wKBUhY5lWjc1ONG8I0YVPFIyMWniOBZe9xrk6-8hhXmWE1bwe2Xw6bpO1B0s6eZCC8t04t0Ey3dQPQjQ2085oG7tlpy4SP6eyMpWIjuLSG-4FPTruBB7KdrNIJSIflszEUmBYbxTna7ahiCxtAS5AQhgo43YqqEl6MRJ_hUdgs_jl2Ppg.7M7f_fAzsdgCGZpY93n-zQ.WjfcvQTzRtYovZRpayS2BXHeQyv_c8bJTtbplf6yIXqNLoBpcDKwtK7IbDhe5no0wMOztT6n-BfN4d4yHKPblU3CUjdujsJvHJhZWcDkoGEbLWs4sx9o3aE-Qaz3rProLSIGqmT0dGLV9ZQtipDZpyJx7yVktkBXxEtYTPOKPXzDhvtrmk8ydVQcJsyEuBMh_Oje3rCFdeCl-Z4ErFO_kk5zUw7QspzTpQiRJxB5OUKavdLq2ukFrTGD1cdFNxfqyTfe9EMy6PdUnhzhZ7BEiRsU17kU1oDxe9n9qVMQxUD9WMQaP7JguBntyU8bc5A0V8ohbM0txDJJ061fNmPm6BrMEK1PMRicnh3PGPsephwgJFzx6uVmCR6wqZ6CU9mybG1ittA0HV6NwANHIBQyGhL557PT5-g2b-X-Lc4uF0TFl6T5-R_T03L8glBf6QwkzAP1lvb0Q7SZLoInIKKhelB3SWNyhC-ey4ZOjqdx_u0BpGaFcxsHLlXcs7I3uIQ0r1PAnXz8m7cKI0J8Iws2JUDhaRaj20KH1DRqcKEFNraghcoe8Iv0rwj70xLbA2gz8xUJ9dF7LRq5lulNB08hKNSNrJKwdPITYS5DFZEDrs0jihwgmxk-ZUOjnUXhtm3nWJ5CcewfUKPA4iS-oIGTBaw9ETkVbGin9ejfdvDOlkdSdzaqdNdxb-nYuvrv_vgPGgN5DFX5P_uhT-MCN4PTw7rd3DpPATHy6fsAyLuG4yVcpiMbkhpBSx6TFlvp_1x3X1stUVduUltc6lDicBywDFU-LqoTiy6Du2RSjm7LU4MHwEES9kWuR2yWGMzjs5f_vshyFmxncopmmNQWmzf5AXYpDF0Lxm_0uGEkwzaO513Ng3DPWkMQeYhk_uFBibeAPsgwpOHYpSKIb05qvymtJyv3b0ovPsafSb7WIPpebRp5y3uNBy1GtOdIS0TIliM4EG97_UPrg6Erh89ruT3NXddH5QTMFXHX-byZbXNKoYM6wIu3D8Xs9A7murCRJWJlEJmzYMVnLH6CZUVdnuf0JNtnUQPSRmgVt9bs1ChlOXN55Vy9fuwDS3KdSoQmnBZa6gs73fOzUCeUMkn8H2-_Lp8Rri1pmIbU6gTVLLGcuskJPxh2xpTayH-Ljr2ElvXjsjRevTFvSX9rQGmFySvNnyPbhfIG6lBOXh8txVip4bv8xoj4FZ_gBDaJ4gZiO3z5-2QPgY2eVR2LxVtrlrx8dRxtfch-vCwPEfrX1xsQ6KTSTY731zyFI0YN2xH36ptIYuRnxgIflXHtzJ9tyWndYggWQmQypQ2GPa8VTT-Y6PCbir8F1U9s-OPk5wg9An-0-ol51bn5Pqv6dvD2G-DHdllFdtrCPMSdX-rAqk-VWFbkD0NHbG22mxaBQdjLIzvKmi2BjZs8H7GK5CnzJTMNjVYhyaakL89mU5ygBc4yoTFa7t7gjrkO4z5eu_hIz6qIA-ENTgqw0PD5oWoBYYy9RfoTQPip6CzLQSymRl8bH4SZeg_TSvaBvHmnurSIIewZ9ZDqSA08IvEe5feNzCD3dhSJ242fPXfy-GcNTVw79eGgChOB3zZ2SIoQs-agGNG9GayQqOupMlQiIeDG9M8gYg8-Ixg4O8Phw5D5zfTR1Q3yuAjGbiY62AhhmGISLyzeVzo5ZqnOlFLs4RUYjMRtNwbOjINfmWLohdMl-18nqSLQKueh5IzimhQT-x9qtH5OgPdr6X2aPykVfNtqV51gL9Ce_1V2ByvzBYgfbkarUFCbtrymKFHVy1WDFjjtp-6rsAt_XzKxjo9PmIqZz0Ws22U5lN3Ro802kNYIPxNShCIg3h2iRhVCRyTBnhXmVT-u5sFE0eLIdXw7jETWds-l--vBzXWtzo1kmvILnJzebVrOkX4nhFb0q7PevrIoN-_miXxpriRA_XcKTZ8opB8CtcVqja4D7_h3e9DnhY86JmFJOPL-eDj4sepbENxehPYIOpEiwBMM4w0OGSLYeeE_9tQBXjKGGJcH7bplRmhVqrs44aPIUuE2KgBFEO0T7BIhaqbKhXIy7AWxkLSmJNUh4D5ZgM7tlhtwCDXL0lQpSHtMAi2IZJHE6CPPsTK6MZYNi8ujaTl5-uyULl5tFP10B31KidU1eoKFXRusg5J4pZRlLRtxAeJL2GQTeuA-gBGhyIsEFZRfDn3fztoKQdm6MZckwwj0s5OIknqNmMpKBEUn5cXOxDNdH7VquMvm7ZCZRw8LTMRgBYj0mfe2msugtwOtRv2ml9M3WM6hnBpsLR1Va4wu5ciZCmVx27Mma1MJ6xYrQt5fBFJ0o6f7RfFz3w.Ob1eAjQq6naJxqVl3zO2QWCIjLQqadXR0h9gdA5wvvo",
        "refreshToken": "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOiI4Rjg0QjdBQjk2N0RGOEI5OTQwNUQyMEMxM0VDN0UwRDM3MzBEODg3IiwidHlwIjoib2lfcmVmdCtqd3QiLCJjdHkiOiJKV1QifQ.I4hf1xYEpEKhXBOXvixTPqtIr1wXCBI4CmJxUYG_80YdbfRIHZWmUFe-YmjBxqzyGRt7KkCsIKnPa7zQDBDEYQ4lKB72rygaPjGNfB_sD-7Jun2NvbAzv-GXmluojmi4d4vAn6nixiiHF0i2_I0Pm1tZ-6Cn9ZcPoUGB-wKBUhY5lWjc1ONG8I0YVPFIyMWniOBZe9xrk6-8hhXmWE1bwe2Xw6bpO1B0s6eZCC8t04t0Ey3dQPQjQ2085oG7tlpy4SP6eyMpWIjuLSG-4FPTruBB7KdrNIJSIflszEUmBYbxTna7ahiCxtAS5AQhgo43YqqEl6MRJ_hUdgs_jl2Ppg.7M7f_fAzsdgCGZpY93n-zQ.WjfcvQTzRtYovZRpayS2BXHeQyv_c8bJTtbplf6yIXqNLoBpcDKwtK7IbDhe5no0wMOztT6n-BfN4d4yHKPblU3CUjdujsJvHJhZWcDkoGEbLWs4sx9o3aE-Qaz3rProLSIGqmT0dGLV9ZQtipDZpyJx7yVktkBXxEtYTPOKPXzDhvtrmk8ydVQcJsyEuBMh_Oje3rCFdeCl-Z4ErFO_kk5zUw7QspzTpQiRJxB5OUKavdLq2ukFrTGD1cdFNxfqyTfe9EMy6PdUnhzhZ7BEiRsU17kU1oDxe9n9qVMQxUD9WMQaP7JguBntyU8bc5A0V8ohbM0txDJJ061fNmPm6BrMEK1PMRicnh3PGPsephwgJFzx6uVmCR6wqZ6CU9mybG1ittA0HV6NwANHIBQyGhL557PT5-g2b-X-Lc4uF0TFl6T5-R_T03L8glBf6QwkzAP1lvb0Q7SZLoInIKKhelB3SWNyhC-ey4ZOjqdx_u0BpGaFcxsHLlXcs7I3uIQ0r1PAnXz8m7cKI0J8Iws2JUDhaRaj20KH1DRqcKEFNraghcoe8Iv0rwj70xLbA2gz8xUJ9dF7LRq5lulNB08hKNSNrJKwdPITYS5DFZEDrs0jihwgmxk-ZUOjnUXhtm3nWJ5CcewfUKPA4iS-oIGTBaw9ETkVbGin9ejfdvDOlkdSdzaqdNdxb-nYuvrv_vgPGgN5DFX5P_uhT-MCN4PTw7rd3DpPATHy6fsAyLuG4yVcpiMbkhpBSx6TFlvp_1x3X1stUVduUltc6lDicBywDFU-LqoTiy6Du2RSjm7LU4MHwEES9kWuR2yWGMzjs5f_vshyFmxncopmmNQWmzf5AXYpDF0Lxm_0uGEkwzaO513Ng3DPWkMQeYhk_uFBibeAPsgwpOHYpSKIb05qvymtJyv3b0ovPsafSb7WIPpebRp5y3uNBy1GtOdIS0TIliM4EG97_UPrg6Erh89ruT3NXddH5QTMFXHX-byZbXNKoYM6wIu3D8Xs9A7murCRJWJlEJmzYMVnLH6CZUVdnuf0JNtnUQPSRmgVt9bs1ChlOXN55Vy9fuwDS3KdSoQmnBZa6gs73fOzUCeUMkn8H2-_Lp8Rri1pmIbU6gTVLLGcuskJPxh2xpTayH-Ljr2ElvXjsjRevTFvSX9rQGmFySvNnyPbhfIG6lBOXh8txVip4bv8xoj4FZ_gBDaJ4gZiO3z5-2QPgY2eVR2LxVtrlrx8dRxtfch-vCwPEfrX1xsQ6KTSTY731zyFI0YN2xH36ptIYuRnxgIflXHtzJ9tyWndYggWQmQypQ2GPa8VTT-Y6PCbir8F1U9s-OPk5wg9An-0-ol51bn5Pqv6dvD2G-DHdllFdtrCPMSdX-rAqk-VWFbkD0NHbG22mxaBQdjLIzvKmi2BjZs8H7GK5CnzJTMNjVYhyaakL89mU5ygBc4yoTFa7t7gjrkO4z5eu_hIz6qIA-ENTgqw0PD5oWoBYYy9RfoTQPip6CzLQSymRl8bH4SZeg_TSvaBvHmnurSIIewZ9ZDqSA08IvEe5feNzCD3dhSJ242fPXfy-GcNTVw79eGgChOB3zZ2SIoQs-agGNG9GayQqOupMlQiIeDG9M8gYg8-Ixg4O8Phw5D5zfTR1Q3yuAjGbiY62AhhmGISLyzeVzo5ZqnOlFLs4RUYjMRtNwbOjINfmWLohdMl-18nqSLQKueh5IzimhQT-x9qtH5OgPdr6X2aPykVfNtqV51gL9Ce_1V2ByvzBYgfbkarUFCbtrymKFHVy1WDFjjtp-6rsAt_XzKxjo9PmIqZz0Ws22U5lN3Ro802kNYIPxNShCIg3h2iRhVCRyTBnhXmVT-u5sFE0eLIdXw7jETWds-l--vBzXWtzo1kmvILnJzebVrOkX4nhFb0q7PevrIoN-_miXxpriRA_XcKTZ8opB8CtcVqja4D7_h3e9DnhY86JmFJOPL-eDj4sepbENxehPYIOpEiwBMM4w0OGSLYeeE_9tQBXjKGGJcH7bplRmhVqrs44aPIUuE2KgBFEO0T7BIhaqbKhXIy7AWxkLSmJNUh4D5ZgM7tlhtwCDXL0lQpSHtMAi2IZJHE6CPPsTK6MZYNi8ujaTl5-uyULl5tFP10B31KidU1eoKFXRusg5J4pZRlLRtxAeJL2GQTeuA-gBGhyIsEFZRfDn3fztoKQdm6MZckwwj0s5OIknqNmMpKBEUn5cXOxDNdH7VquMvm7ZCZRw8LTMRgBYj0mfe2msugtwOtRv2ml9M3WM6hnBpsLR1Va4wu5ciZCmVx27Mma1MJ6xYrQt5fBFJ0o6f7RfFz3w.Ob1eAjQq6naJxqVl3zO2QWCIjLQqadXR0h9gdA5wvvo",
        "expires_in": 20,
        "expires": "2024-03-19T10:07:28.2248577+00:00"
    }
}后台返回了这种结果，token过期后，执行代码 获取不到refreshtoken

### 操作系统和浏览器信息 (Operating system and browser information)

谷歌浏览器版本 122.0.6261.128（正式版本） （64 位）

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/9ad00d97ee96eb4fba5a638131c2fe46ed99eb41)
