### ISSUE TITLE
建议优化下请求拦截代码

### ISSUE THREAD

**Issue by freadman** [pure-admin/vue-pure-admin#1002]
### 描述问题 (Describe the problem)

1、return whiteList.find(url => url === config.url){...}这段代码使用find函数对whiteList要求完全命中，那接口有时候使用/api/就不行，建议换成return whiteList.some(v => config.url.indexOf(v) > -1){...}
2、关于token的逻辑有临界点问题
代码中token的获取  const data = getToken()，然而，data根据是否超时返回accessToken或refreshToken，这里就存在一个超时判断准确性问题，一般情况下token的超时时间由服务器返回，而vue实际对比的是我们客户端的时间，所以会出现临界现象，即token判断是超时的，但是getToken()却获取不到refreshToken，传给后端空数据导致请求失败。
建议优化这里代码逻辑，避免临界点传空值。

### 如何复现该问题 (How to reproduce the problem)

后端返回的accessToken有效期10秒，不断点击页面，触发临界点（refresh-token接口传入空对象）

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
后续将进行调查 谢谢反馈 目前计划较多 只解决明确bug

**Comment by freadman** [comment]
我目前的处理方式是不通过时间判断，而是使用对象中的key，贴上代码，mark一下：
`const expired = "refreshToken" in data;`

**Comment by lulifa** [comment]
我提了个issue直接说是无效的。。。你token 和Refreshtoken就会出现这个现象，Refreshtoken过期后  传值为空

**Comment by zhangran2616** [comment]
这里的判断逻辑明显是有问题的。

> 我提了个issue直接说是无效的。。。你token 和Refreshtoken就会出现这个现象，Refreshtoken过期后 传值为空
