### ISSUE TITLE
前端Post请求参数后端获取不到

### ISSUE THREAD

**Issue by tanlangDark** [pure-admin/vue-pure-admin#1006]
### 描述问题 (Describe the problem)

后端使用的是SpringBoot，使用@RequestBody获取Post请求参数。
前端Post请求参数中如果参数命名vCnt，后端获取不到该参数的值。当我把参数名改为cnt时，后端就能够成功获取。相同的参数命名vWeightR也是相同的情况，可以察觉的是v开头的参数命名会导致后端获取不到数据，没有搞明白为什么会这样

### 如何复现该问题 (How to reproduce the problem)

在前端发送Post请求到后端，参数命名vCnt，看看后端是否能够成功获取到参数的值

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
see https://yiming_chang.gitee.io/pure-admin-doc/pages/request/
