### ISSUE TITLE
vite-plugin-fake-server 不支持 正则 url

### ISSUE THREAD

**Issue by softshield** [pure-admin/vue-pure-admin#1010]
### 描述问题 (Describe the problem)

希望能支持正则url

### 如何复现该问题 (How to reproduce the problem)

希望能支持正则url

### 操作系统和浏览器信息 (Operating system and browser information)

希望能支持正则url

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
请到对应插件仓库反馈
