### ISSUE TITLE
由`Stretch`配置缩放所导致角色管理模块-角色权限功能的样式渲染问题

### ISSUE THREAD

**Issue by QFifteen** [pure-admin/vue-pure-admin#1011]
### 描述问题 (Describe the problem)

1.由`Stretch`配置缩放所导致角色管理模块-角色权限功能的样式渲染问题
2.(细节小问题)在不算很窄的屏幕下，菜单树操作列，由于`flex-wrap`的换行效果，导致分页组件下方留白过多

### 如何复现该问题 (How to reproduce the problem)

问题一复现图：
![test2](https://github.com/pure-admin/vue-pure-admin/assets/66454152/bd7ac551-6ccd-4061-98ca-232f4460fbf1)

问题二示意图：
![image](https://github.com/pure-admin/vue-pure-admin/assets/66454152/476e7931-eeae-4076-a943-65acc4be72a3)

这些算不上Bug问题。当然，如果小明很忙的话，我认为这个issues可以留给感兴趣的人来处理

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
这个是业务模块 可自行处理 不算框架问题  先打上`Investigate:Waiting` 后续我来处理

**Comment by xiaoxian521** [comment]
对了 帅哥 之前有个pr不错的
在来一个就可以加入 [特别贡献者名单啦](https://github.com/pure-admin/vue-pure-admin?tab=readme-ov-file#%E7%89%B9%E5%88%AB%E4%BB%A3%E7%A0%81%E8%B4%A1%E7%8C%AE)

**Comment by QFifteen** [comment]
> 对了 帅哥 之前有个pr不错的 在来一个就可以加入 [特别贡献者名单啦](https://github.com/pure-admin/vue-pure-admin?tab=readme-ov-file#%E7%89%B9%E5%88%AB%E4%BB%A3%E7%A0%81%E8%B4%A1%E7%8C%AE)

我很喜欢`segmented`这个组件。工作偷闲时再丰富一下这个组件，比如配置尺寸、禁用等(别人家有的，咱也不能缺)
