### ISSUE TITLE
VITE_PUBLIC_PATH 设置的问题

### ISSUE THREAD

**Issue by f2xb** [pure-admin/vue-pure-admin#1012]
### 描述问题 (Describe the problem)

.env 设置
`
VITE_PUBLIC_PATH = /web/demo/
VITE_ROUTER_HISTORY = "h5"
`
nginx.conf 设置
`
location / {
    root   /opt/web/admin;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
}

location /web/demo/ {
    root   /opt/web/demo;
    index  index.html index.htm;
    try_files $uri $uri/ /opt/web/demo/index.html;
}
`
当访问 http://localhost:8848/web/demo 的时候，它会跳转到 http://localhost:8848/login，这里就会出现问题，它走的是 `location /` 而不是 `location /web/demo/`，我想要的是它跳转到 http://localhost:8848/web/demo/login 上面，我看在代码https://github.com/f2xb/vue-pure-admin/blob/791224b381e9804dadca17c77d113e4167c47e80/src/router/utils.ts#L323 getHistoryMode方法中，只是对 VITE_ROUTER_HISTORY 做了处理。
我更改了env配置
.env 设置
`
VITE_PUBLIC_PATH = /web/demo/
VITE_ROUTER_HISTORY = "h5,/web/demo/"
`
getHistoryMode方法中，分割了 VITE_ROUTER_HISTORY，设置了 createWebHistory('/web/demo/')
只有这样它跳转的时候不会有问题。

能否在getHistoryMode方法中传入VITE_PUBLIC_PATH，设置createWebHistory() 的base参数，这样就不用同时设置VITE_PUBLIC_PATH和VITE_ROUTER_HISTORY。

很棒的后台管理系统，👍

### 如何复现该问题 (How to reproduce the problem)

1

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看下文档

**Comment by f2xb** [comment]
@xiaoxian521  看过了，精简版，只设置VITE_PUBLIC_PATH，没做其它任何改动，nginx配置也是和文档一样，跳转就是有问题
