### ISSUE TITLE
希望能够添加一个对于word的预览

### ISSUE THREAD

**Issue by hulaime** [pure-admin/vue-pure-admin#1013]
### 描述问题 (Describe the problem)

希望能够添加一个对于word.docx文件的预览

### 如何复现该问题 (How to reproduce the problem)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[done](https://github.com/pure-admin/vue-pure-admin/commit/4f44f72a2c2436513065921901a93e40785cd01a)
