### ISSUE TITLE
用户管理界面裁剪图片上传组件逻辑上有点问题

### ISSUE THREAD

**Issue by heyingjie** [pure-admin/vue-pure-admin#1025]
### 描述问题 (Describe the problem)

如果一个用户首次添加信息时，他的avatar字段为""，此时裁剪图片上传的组件会处于加载状态，进入不了选择图片上传的界面。

### 如何复现该问题 (How to reproduce the problem)

将mock的avatar信息设置为"",然后去上传头像

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr
