### ISSUE TITLE
通过path路由跳转参数问题

### ISSUE THREAD

**Issue by SnowyLchen** [pure-admin/vue-pure-admin#1026]
### 描述问题 (Describe the problem)

通过path跳转的时候，携带query参数，如：
![image](https://github.com/pure-admin/vue-pure-admin/assets/52272752/d6a71bc6-c5c5-441f-ac45-729bae3915af)
可以正常跳转，但是标签页进行切换，切换回来的时候，当前页参数丢失。

### 如何复现该问题 (How to reproduce the problem)

标签页进行切换，切换回来的时候

\src\layout\components\tag\index.vue #tagOnClick
应增加path类型路由参数传递，如：
![image](https://github.com/pure-admin/vue-pure-admin/assets/52272752/f22cbab1-0702-4c58-85f3-f8f70813b773)

代码可进行优化

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by Styunlen** [comment]
我之前提过的一个pr #667（虽然没merge） 好像意外的能解决这个问题😲，虽然我想解决的问题不同，但是我在跳转的过程中加入了对params和query的保存，以及对相同标签页不同query和params的保存，防止相同标签页不同query的标签同时高亮，也能在标签进行跳回时恢复上下文

**Comment by SnowyLchen** [comment]
> 我之前提过的一个pr #667（虽然没merge） 好像意外的能解决这个问题😲，虽然我想解决的问题不同，但是我在跳转的过程中加入了对params和query的保存，以及对相同标签页不同query和params的保存，防止相同标签页不同query的标签同时高亮，也能在标签进行跳回时恢复上下文

😂好的吧
