### ISSUE TITLE
关于项目中使用 路由createWebHistory 模式为 h5 模式的时候，假如url地址携带特殊符号的参数会导致页面卡死的现象

### ISSUE THREAD

**Issue by jessie-yongjian** [pure-admin/vue-pure-admin#1028]
### 描述问题 (Describe the problem)

关于项目中使用 路由模式createWebHistory为 h5 模式的时候，假如url地址携带特殊符号的参数会导致页面卡死的现象

### 如何复现该问题 (How to reproduce the problem)

比如url地址为  
[getHistoryMode](http://localhost:8849/welcome?message=bG1WZTdMV2NZMzBneDgybk8yRmx4dW8rUTNsdnc1aHh4UkZLNE1oWUJlV1FWWEZMcTVpMmFFNHEvMURvYUZ1YWNmSjRrNDNmb2cwa0NwZStEb3FwRE8zZGU3bkNIRVhaQ2pXS01pcnIrK0N5ZGhUSkZwSG13MXBsdVp1Z3libENUVjFUODJNSWpZT2ZhVDNSZHI3enBpdnF2d0l3aHBIai8vb1BYOGtFK1U0PQ==&)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by jessie-yongjian** [comment]
哈希模式不会出现这个问题

**Comment by xiaoxian521** [comment]
目前计划较多 欢迎pr

**Comment by jessie-yongjian** [comment]
问题排除是sso.ts 文件黎明是处理函数导致的

**Comment by jessie-yongjian** [comment]
问题排除是sso.ts 文件里面的处理函数在h5模式下携带query参数，参数有特殊符号的时候会导致

**Comment by guohui666** [comment]
> 问题排除是sso.ts 文件里面的处理函数在h5模式下携带query参数，参数有特殊符号的时候会导致

请问你解决了吗？
