### ISSUE TITLE
cdn模式打包失败

### ISSUE THREAD

**Issue by shuTwT** [pure-admin/vue-pure-admin#1029]
### 描述问题 (Describe the problem)

<img width="1024" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/95295076/d71430ee-d827-4bee-8b6f-e7bacb1a0b32">

### 如何复现该问题 (How to reproduce the problem)

在 .env.production 文件，将 VITE_CDN 设置成true,然后运行`pnpm run build`

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
卸载下图包
<img width="343" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/43112dca-94db-47d5-b92e-b3b274fa3496">

它们不支持cdn模式
