### ISSUE TITLE
node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script...

### ISSUE THREAD

**Issue by mariree** [pure-admin/vue-pure-admin#1030]
### 描述问题 (Describe the problem)

代码clone以后，pnpm install无法成功安装，一直卡在node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script...这一步

### 如何复现该问题 (How to reproduce the problem)

代码clone以后，pnpm install无法成功安装，一直卡在node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script...这一步
查到有个相似问题，回复是无法复现被关闭了。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
无法复现
拉取代码pnpm i
一会就安装好了呀

你可以多等一会 或者直接等一会然后直接结束进程或者换yarn
