### ISSUE TITLE
请问是否有计划优化token过期检测，无感刷新token方式

### ISSUE THREAD

**Issue by ZM25XC** [pure-admin/vue-pure-admin#1032]
### 描述问题 (Describe the problem)

目前平台将token和过期时间存储在cookie中，判断cookie中是否有`multiple-tabs` 字段判断是否登录。
是否有考虑将`accesstoken`,`refreshToken`,`expires`字段挂载到pinia中，更换判断cookie中是否存在`multiple-tabs`字段识别用户是否登录的方式，改用直接判断pinia中 `expires`的值是否大于当前毫秒时间戳来确认

### 如何复现该问题 (How to reproduce the problem)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
我觉得目前的就行了

**Comment by QFifteen** [comment]
我觉得这应该在你自己的项目里去做业务更改，而不是让平台来适应。你是想放到`local Storage`里做持久化，当然可以，也不难。多百度一下，很多这种文章。

**Comment by QFifteen** [comment]
> > 我觉得这应该在你自己的项目里去做业务更改，而不是让平台来适应。你是想放到`local Storage`里做持久化，当然可以，也不难。多百度一下，很多这种文章。
> 
> 我自己的项目已经实现了，我在想要不要pr上来

没必要，大概率被`close`。多站在平台的角度来看问题，而不是根据你自己的业务来随心pr(不确定的事就先开`issues`问)
