### ISSUE TITLE
切割面板移动端没法用

### ISSUE THREAD

**Issue by LiuXIn011** [pure-admin/vue-pure-admin#1037]
### 描述问题 (Describe the problem)

切割面板移动端没法拖拽

[代码位置 src/views/components/split-pane.vue](https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/components/split-pane.vue)

### 如何复现该问题 (How to reproduce the problem)

F12切换移动端使用切割面板

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/570
