### ISSUE TITLE
使用前端登出logOut方法没有重置路由

### ISSUE THREAD

**Issue by freadman** [pure-admin/vue-pure-admin#1038]
### 描述问题 (Describe the problem)

使用签到登出logOut方法没有重置路由，导致换一个账号登录，展示的菜单还是上一个用户登录的菜单

### 如何复现该问题 (How to reproduce the problem)

1、动态获取路由
2、登录用户1
3、退出登录用户1
4、登录用户2
5、检查菜单是否更新

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多看文档。。。。。

**Comment by xiaoxian521** [comment]
初学者请通读几遍文档
