### ISSUE TITLE
路由BUG

### ISSUE THREAD

**Issue by LiuXIn011** [pure-admin/vue-pure-admin#1040]
### 描述问题 (Describe the problem)

在添加路由后（红色框选的为添加的路由），路由结构如下：
![image](https://github.com/pure-admin/vue-pure-admin/assets/48080203/508ec0a3-d4ae-4622-857a-bab7e2668605)
这时，路由不知是什么原因，会被挂载到跟路由‘/’的children下
![image](https://github.com/pure-admin/vue-pure-admin/assets/48080203/671be04f-bbb8-4d09-9779-fae009838582)
当使用useUserStore的logOut方法退出登录后，外层的路由被删除。
![image](https://github.com/pure-admin/vue-pure-admin/assets/48080203/3d6647d1-6022-42a7-a0aa-cef78f5440dd)
跟路由‘/’的children下的新增路由没有被删除，导致路由被异常缓存。
![image](https://github.com/pure-admin/vue-pure-admin/assets/48080203/f72c89ab-b170-4e48-9d9e-de87c05abc14)
在下次加载路由时，缓存的路由会污染数据。导致mate中的权限数据异常

### 如何复现该问题 (How to reproduce the problem)

在login页面使用console.log(router.getRoutes());输出全部路由
在welcome页面使用console.log(router.getRoutes());输出全部路由

登录后退出，查看控制台3条log，对比根目录‘/’的children

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/pull/1208)
