### ISSUE TITLE
请问这些东西要怎么删除，我在router/components/下没有找到这几个页面的路由啊？

### ISSUE THREAD

**Issue by 1054427212** [pure-admin/vue-pure-admin#1041]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/62043845/49330b63-a68f-466b-b6a3-0a8ad0db7ebb)

### 如何复现该问题 (How to reproduce the problem)

请问这些东西要怎么删除，我在router/components/下没有找到这几个页面的路由啊？

### 操作系统和浏览器信息 (Operating system and browser information)

请问这些东西要怎么删除，我在router/components/下没有找到这几个页面的路由啊？

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
项目开发用精简版
