### ISSUE TITLE
建议优化过往代码

### ISSUE THREAD

**Issue by xun-jian** [pure-admin/vue-pure-admin#1048]
### 描述问题 (Describe the problem)

不是提问题。看作者现在开始全职开源了，建议作者有空闲时停一停脚步，对过往2-3年前写好的代码重审一下。
比如，有些许的类型问题跳不严谨或直接undefined忽略了；还有一些代码重复，像store里和配置的一些东西看2年前的有不少优化的空间。

### 如何复现该问题 (How to reproduce the problem)

建议优化过往代码

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr 我们有自己的计划和进度
