### ISSUE TITLE
能否提供关于plus-pro-components的更多示例

### ISSUE THREAD

**Issue by hulaime** [pure-admin/vue-pure-admin#1049]
### 描述问题 (Describe the problem)

如：plus-pro-components在系统管理用户或角色等场景下的新增示例

### 如何复现该问题 (How to reproduce the problem)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考 https://plus-pro-components.com/components/form.html

**Comment by xiaoxian521** [comment]
从框架的角度，我一直坚持使用一个个组件去拼`form`，其实在你们有`ui`设计的情况下。`json`的格式看自己的项目需求

**Comment by xiaoxian521** [comment]
参考系统管理的代码，里面代码足够抽离、结构也清晰并搭配`ReDialog`函数式弹框，对于使用者来说就是copy、change
