### ISSUE TITLE
当一个页面存在多个`RePureTableBar`组件，列无法正常拖动问题

### ISSUE THREAD

**Issue by wangxiaoshuai521** [pure-admin/vue-pure-admin#1053]
### 描述问题 (Describe the problem)

两个PureTableBar、第二个列无法拖动排序

### 如何复现该问题 (How to reproduce the problem)

![aaa](https://github.com/pure-admin/vue-pure-admin/assets/50014096/d72147aa-837f-426a-a411-5c6f7ebdbf0e)
![bbb](https://github.com/pure-admin/vue-pure-admin/assets/50014096/f5da0e7c-b7ca-4c0c-8cf8-50d8e944f1f8)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供复现仓库

**Comment by wangxiaoshuai521** [comment]
> 提供复现仓库

https://github.com/wangxiaoshuai521/wangyongshuai-biji.git

**Comment by wangxiaoshuai521** [comment]
> 提供复现仓库

https://gitee.com/wang_xiaoshuai521/pure_study.git

**Comment by wangxiaoshuai521** [comment]
> > 提供复现仓库
> 
> https://gitee.com/wang_xiaoshuai521/pure_study.git

页面是\src\views\welcome

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/ea36e260e201e0947cba1059115e0b016ad2c11b)

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/assets/44761321/fecc6403-08f2-4b1e-8c13-339d6bd9529d

**Comment by wangxiaoshuai521** [comment]
收到收到、感谢
