### ISSUE TITLE
ts文件中FormRule中Message国际化不起作用

### ISSUE THREAD

**Issue by lulifa** [pure-admin/vue-pure-admin#1055]
### 描述问题 (Describe the problem)

![角色配置页面](https://github.com/pure-admin/vue-pure-admin/assets/65484176/fc9418ee-f8b8-4f01-a7ae-fa8f82674c39)
formrule 中的message 中英文切换 不起作用：
import { reactive } from "vue";
import type { FormRules } from "element-plus";
import { $t, transformI18n } from "@/plugins/i18n";

/** 自定义表单规则校验 */
export const formRules = reactive(<FormRules>{
  name: [{ required: true, message: transformI18n($t("buttons.hscloseCurrentTab")), trigger: "blur" }],
  code: [{ required: true, message: "角色标识为必填项", trigger: "blur" }]
});

### 如何复现该问题 (How to reproduce the problem)

获取最新版本，系统管理模块中的角色管理，角色名称必填信息  只展示中文  切换多语言不起作用

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
最新版不叫 hscloseCurrentTab

**Comment by lulifa** [comment]
我只是随意找了一个多语言的 放在验证message中去验证了 结果切换英文 还是中文提示

**Comment by xiaoxian521** [comment]
参考 src/views/login/utils/rule.ts 文件
