### ISSUE TITLE
> > 提供复现仓库

### ISSUE THREAD

**Issue by wangxiaoshuai521** [pure-admin/vue-pure-admin#1057]
> > 提供复现仓库
> 
> https://gitee.com/wang_xiaoshuai521/pure_study.git

页面是\src\views\welcome

_Originally posted by @wangxiaoshuai521 in https://github.com/pure-admin/vue-pure-admin/issues/1053#issuecomment-2041279209_

**Comment by xiaoxian521** [comment]
目前很忙 等等吧 
重复https://github.com/pure-admin/vue-pure-admin/issues/1053#issuecomment-2041279209
