### ISSUE TITLE
The dependency `cloc` is under the GPL license, please consider changing it

### ISSUE THREAD

**Issue by cloydlau** [pure-admin/vue-pure-admin#1058]
### 描述问题 (Describe the problem)

The GPL is contagious and belongs to the copyleft licenses, I won't go into details here.
Please consider switching to another alternative, such as [scc](https://github.com/boyter/scc) (MIT license).
If you agree, I can submit a PR for this.

### 如何复现该问题 (How to reproduce the problem)

Opan `./package.json`.

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by cloydlau** [comment]
If you agree, I can submit a PR for this.

**Comment by xiaoxian521** [comment]
貌似只有cloc有npm版本
我这是开源项目 我觉得没问题
