### ISSUE TITLE
第一张图是我第二次登录时，后端返回的路由，可以看到是传了auths的

### ISSUE THREAD

**Issue by liliuhai** [pure-admin/vue-pure-admin#1061]
第一张图是我第二次登录时，后端返回的路由，可以看到是传了auths的
![a7](https://github.com/pure-admin/vue-pure-admin/assets/5433744/0a9c8e5c-46ba-41ca-9761-74c0b59d2926)
第二张图是这个时候，'/'路由下面保存的上一次登录获取的后端路由，auths是空的
![a8](https://github.com/pure-admin/vue-pure-admin/assets/5433744/0e5ae65c-c1cc-4bdb-9a9b-2da480846c23)
第三张图是执行177行router.addRoute(flattenRouters);之前的情况，auths是设置正确了
![a9](https://github.com/pure-admin/vue-pure-admin/assets/5433744/15b699e5-7324-47b7-95f1-217a16ecb23e)
第四张图是执行177行之后，用原来的“/”路径的做了addroute，之后auths就变回第一次登录后auths为空的情况了
![a10](https://github.com/pure-admin/vue-pure-admin/assets/5433744/aa7a232e-e690-4ced-9ddf-8a1609db56b0)

_Originally posted by @liliuhai in https://github.com/pure-admin/vue-pure-admin/issues/1060#issuecomment-2044544082_

**Comment by xiaoxian521** [comment]
等待调查好吗 不要重复提
目前很忙 不好意思
