### ISSUE TITLE
腾讯即时消息IM集成的SDK打包build报错

### ISSUE THREAD

**Issue by huqings** [pure-admin/vue-pure-admin#1062]
### 描述问题 (Describe the problem)

纯git clone项目引入npm i @tencentcloud/chat-uikit-vue后，dev运行正常，build报错。如何解决？
![微信截图](https://github.com/pure-admin/vue-pure-admin/assets/12019831/960e17f0-0d66-4462-9da2-2f8b50004e89)

### 如何复现该问题 (How to reproduce the problem)

npm i @tencentcloud/chat-uikit-vue
引入sdk之后，build打包

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
非平台问题 自己找任何兼容vite
