### ISSUE TITLE
通过swagger解析生成TS类型和对应接口

### ISSUE THREAD

**Issue by chanceyliu** [pure-admin/vue-pure-admin#1063]
### 描述问题 (Describe the problem)

想请问下大佬有没有计划引入配套的生成接口的工具，看了下项目里面是有大量的TS类型定义的，在平时开发的过程中，定义接口阶段，如果前端在去根据swagger手动定义下接口类型，然后手写接口，是很机械和繁琐的。因为axios也是大佬项目封装好的，想的是能不能再配套出一个生成接口的工具或者推荐用的工具

### 如何复现该问题 (How to reproduce the problem)

~

### 操作系统和浏览器信息 (Operating system and browser information)

~

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
暂不考虑 计划安排到了6月
