### ISSUE TITLE
三级菜单向左折叠后图标显示样式问题

### ISSUE THREAD

**Issue by caimingyi484** [pure-admin/vue-pure-admin#1069]
### 描述问题 (Describe the problem)

在pure-admin-thin项目中，二级路由菜单使用fa-solid:file时，当菜单收缩后，有三级子菜单的二级菜单中图标与文字无法对齐。
如图所示：
![微信图片_20240413103028](https://github.com/pure-admin/vue-pure-admin/assets/51154104/c2c93c10-1e92-4e74-9718-4573311b8538)

### 如何复现该问题 (How to reproduce the problem)

路由菜单配置的代码如下：
{
  path: "/",
  name: "Home",
  component: Layout,
  redirect: "/welcome",
  meta: {
    icon: "ep:home-filled",
    title: $t("menus.pureHome"),
    rank: 0
  },
  children: [
    {
      path: "/welcome",
      name: "Welcome",
      component: () => import("@/views/welcome/index.vue"),
      meta: {
        title: $t("menus.pureHome"),
        icon: "ep:home-filled",
        showLink: VITE_HIDE_HOME === "true" ? false : true
      }
    },
    {
      path: "/welcome2",
      name: "Welcome",
      redirect: "/welcome2/a",
      meta: {
        title: "测试2",
        icon: "fa-solid:file"
      },
      children: [
        {
          path: "/welcome2/a",
          name: "Welcome",
          component: () => import("@/views/welcome/index.vue"),
          meta: {
            title: "测试2",
            icon: "fa-solid:file"
          }
        },
        {
          path: "/welcome2/b",
          name: "Welcome",
          component: () => import("@/views/welcome/index.vue"),
          meta: {
            title: "测试2长名称",
            icon: "fa-solid:file"
          }
        }
      ]
    },
    {
      path: "/welcome3",
      name: "Welcome",
      component: () => import("@/views/welcome/index.vue"),
      meta: {
        title: "测试3",
        icon: "fa-solid:file"
      }
    }
  ]
}

### 操作系统和浏览器信息 (Operating system and browser information)

window11下的chrome和edge浏览器访问

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
等我们后面调查一下 近期没时间 你可以换个图标

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/dbb05f416642bbf44263dc29da209c273301e549)
