### ISSUE TITLE
overallStyle 配置没有添加到本地存储里

### ISSUE THREAD

**Issue by wukongyang** [pure-admin/vue-pure-admin#1071]
### 描述问题 (Describe the problem)

<img width="772" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/54463146/7deeb632-f743-460c-a7d2-82fef26d4190">
![image](https://github.com/pure-admin/vue-pure-admin/assets/54463146/984f97fd-2c4e-4525-aca3-722f5d218015)

### 如何复现该问题 (How to reproduce the problem)

初始化项目后overallStyle设置为system，整体风格无法配置成自动

### 操作系统和浏览器信息 (Operating system and browser information)

所有浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by wukongyang** [comment]
另外响应式的Storage不好维护，整破防了。根本找不到在哪里被修改了，我这里将configObj修改成这样，依然打印出来了配置，不知道在哪里做修改
<img width="814" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/54463146/bd3140ff-9196-42a4-970a-2198b3bed04d">

**Comment by xiaoxian521** [comment]
目前很忙 不解答源码 请自行研究
