### ISSUE TITLE
个人信息页，刷新页面导致左侧菜单字体变灰色

### ISSUE THREAD

**Issue by nineaiyu** [pure-admin/vue-pure-admin#1072]
### 描述问题 (Describe the problem)

刷新前
![image](https://github.com/pure-admin/vue-pure-admin/assets/19207867/4068abf5-3672-49c2-9ebe-43f3aaa1f460)
刷新后
![image](https://github.com/pure-admin/vue-pure-admin/assets/19207867/3f704952-eafb-4d14-8271-664874735d1e)

### 如何复现该问题 (How to reproduce the problem)

刷新页面

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by nineaiyu** [comment]
主题色选择非白色的其他颜色会触发这个问题

**Comment by xiaoxian521** [comment]
谢谢反馈 样式加个 !important 应该就能解决 欢迎pr

**Comment by xiaoxian521** [comment]
无法复现

**Comment by QFifteen** [comment]
线上预览的版本会有这个问题，在本地跑起的版本，确实没这个问题

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/5d3a9dff460d0e893eceec744f2e40b9c03bf5db)
