### ISSUE TITLE
最新版设计的离线图标也是带冒号，导致异步配置的菜单图标都只能用在线图标

### ISSUE THREAD

**Issue by caimingyi484** [pure-admin/vue-pure-admin#1073]
### 描述问题 (Describe the problem)

最新版设计的离线图标也是带冒号，导致异步配置的菜单图标都只能用在线图标。如果想使用离线图标，该如何处理？
![微信图片_20240415094003](https://github.com/pure-admin/vue-pure-admin/assets/51154104/ad1fe3f4-88d9-4178-b3c6-ac335c28d542)

### 如何复现该问题 (How to reproduce the problem)

异步配置的菜单图标只想使用离线图标，防止延迟加载。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/icon/
