### ISSUE TITLE
[pure-admin-utils - useEcharts] 个别属性不生效（这个问题并没有解决，同 issue#678 ）

### ISSUE THREAD

**Issue by yourbusiness** [pure-admin/vue-pure-admin#1074]
### 描述问题 (Describe the problem)

使用useEcharts发现个别属性不生效.
markPoint markLine
项目是vue-pure-admin，在项目外面用没问题，但是一旦拿到项目里面来用就有问题，markPoint失效

### 如何复现该问题 (How to reproduce the problem)

和 https://github.com/pure-admin/vue-pure-admin/issues/678 这个问题一模一样，问题还存在

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
只有这个回复 https://github.com/pure-admin/vue-pure-admin/issues/678#issuecomment-1658417422
源码不关心属性 只渲染
