### ISSUE TITLE
RePureTableBar 组件的 列设置拖拽功能在页面加了keepAlive后无法拖拽

### ISSUE THREAD

**Issue by xiahengxz** [pure-admin/vue-pure-admin#1075]
### 描述问题 (Describe the problem)

问题组件：RePureTableBar 
运行国际化完整版代码
给角色管理，用户管理页面加上keepAlive
在角色管理页面刷新浏览器，此时打开列设置今天拖拽是可以正常拖拽的， 然后切换到用户管理页面，打开列设置就不能拖拽

### 如何复现该问题 (How to reproduce the problem)

问题组件：RePureTableBar 
运行国际化完整版代码
给角色管理，用户管理页面加上keepAlive
进入角色管理页面，先刷新浏览器，此时打开列设置然后拖拽， 是可以正常拖拽的， 然后切换到用户管理页面，打开列设置就不能拖拽

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by QFifteen** [comment]
嗯...自己偷闲试了下，个人未复现问题，正常拖拽。不知道你是不是拖拽到`勾选列`、`操作`这些固定列上去了
