### ISSUE TITLE
设置跨域代理

### ISSUE THREAD

**Issue by chenbihuaer** [pure-admin/vue-pure-admin#1078]
### 描述问题 (Describe the problem)

为什么在vite.config.ts中设置跨域代理无效

### 如何复现该问题 (How to reproduce the problem)

proxy: {
        '^/admin':'http://192.168.1.70/'
      },

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
新手多看文档 github的issues 只用来解决bug
https://www.bilibili.com/video/BV1kg411v7QT/
