### ISSUE TITLE
静态路由模式下，router.beforeEach会重复触发两次

### ISSUE THREAD

**Issue by 1Chen1y1111** [pure-admin/vue-pure-admin#1080]
### 描述问题 (Describe the problem)

在精简版中，通过左边菜单栏点击，从首页跳转到404页面，router.beforeEach会重复触发两次
![1](https://github.com/pure-admin/vue-pure-admin/assets/88277615/d57adc98-4cc0-4623-be30-40b54d77ab76)
![2](https://github.com/pure-admin/vue-pure-admin/assets/88277615/834649ec-1ae6-4ba4-8205-5d56b14e8080)

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/88277615/26dcd8dc-1e56-49db-8552-3610e37301d7)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues?q=beforeEach
