### ISSUE TITLE
ReDialog

### ISSUE THREAD

**Issue by Tie-Tie** [pure-admin/vue-pure-admin#1081]
### 描述问题 (Describe the problem)

我希望你将我修改后的代码加入到该项目中的ReDialog，下面是我的ReDialog中closeDialog的解决方案

### 如何复现该问题 (How to reproduce the problem)

 options.beforeClose
    ? options.beforeClose(() => {
        dialogStore.value[index].visible = false;
        options.closeCallBack &&
          options.closeCallBack({ options, index, args });
        useTimeoutFn(() => {
          dialogStore.value.splice(index, 1);
        }, 200);
      })
    : (dialogStore.value[index].visible = false);
  options.closeCallBack && options.closeCallBack({ options, index, args });
  useTimeoutFn(() => {
    dialogStore.value.splice(index, 1);
  }, 200);
  
  
  or
  
  const control = () => {
    dialogStore.value[index].visible = false;
    options.closeCallBack && options.closeCallBack({ options, index, args });
    useTimeoutFn(() => {
      dialogStore.value.splice(index, 1);
    }, 200);
  };
  options.beforeClose
    ? options.beforeClose(() => {
        control();
      })
    : control();

**Comment by xiaoxian521** [comment]
目前没时间 等后续计划调查
