### ISSUE TITLE
打包报错：node-v20.12.2 ，pnpm-v8.10.0

### ISSUE THREAD

**Issue by tombingo** [pure-admin/vue-pure-admin#1084]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/13918652/7abc19fe-3ba3-499a-842b-f18d8b178494)

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

win10

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
see https://github.com/pure-admin/vue-pure-admin/issues/1045
