### ISSUE TITLE
账号设置页-更新头像上传文件错误

### ISSUE THREAD

**Issue by shuTwT** [pure-admin/vue-pure-admin#1085]
### 描述问题 (Describe the problem)

`views/account-settings/components/Profile.vue` 第 69行 `const onCropper = info => (cropperInfo.value = info);`导致上传文件表单参数不对
该问题导致 `new File()`传入的 是以下结构的对象
```
{
    "base64": "",
    "blob": {},
    "info": {
    }
}
```
服务端接收后变成了
```
[object Object]
```

### 如何复现该问题 (How to reproduce the problem)

账号设置页-更新头像功能对接服务端发现该问题

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/ada3e80c7ee449beeacb63804854e96f3f26323e)
