### ISSUE TITLE
加入自己的iconfont后，打包出错

### ISSUE THREAD

**Issue by remember-5** [pure-admin/vue-pure-admin#1091]
### 描述问题 (Describe the problem)

引用 #1045 之前已经讨论过这个问题，但是issues被锁定了

### 如何复现该问题 (How to reproduce the problem)

> 下面是复现步骤，自定义`iconfont`的属性`font_family`和`css_prefix_text`尝试相同值和不同值，但仍报错
# 引入iconfont

[iconfont引入](https://yiming_chang.gitee.io/pure-admin-doc/pages/icon/#iconfont-%E7%9A%84%E5%BC%95%E5%85%A5)

<img width="867" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/31730796/752a1d84-1c72-48b5-bf8b-895c272b0ce7">

<img width="454" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/31730796/d52564f4-d77d-4b75-853f-3403bbd50c21">

 # iconfont配置

<img width="951" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/31730796/03ce61bb-7936-4a09-957b-fda96fad26f7">

<img width="687" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/31730796/60ea836b-0214-4530-9e3b-298c598b209a">

# 打包

<img width="1542" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/31730796/98175f16-5728-4373-912a-b845021fd3fd">

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
加入 https://github.com/pure-admin/vue-pure-admin/blob/main/build/plugins.ts#L56
