### ISSUE TITLE
如何在verical布局模式下添加一个layout只有navbar，隐藏sidebar的路由页面

### ISSUE THREAD

**Issue by 1Chen1y1111** [pure-admin/vue-pure-admin#1100]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/88277615/b517d705-2322-4af6-9e8e-032c3ee91509)

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/88277615/4b4c43aa-068c-4dbd-87e7-6973ee17251c)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前很忙 只解决确定性bug
请自行研究
