### ISSUE TITLE
showLink:false和activePath一起使用导致的菜单高亮问题

### ISSUE THREAD

**Issue by T97-coffee** [pure-admin/vue-pure-admin#1102]
### 描述问题 (Describe the problem)

我的项目是以5.1版本为基础构建的，在开发过程中我遇到一个场景，我需要从一个菜单页面A跳转到另外一个不在菜单中展示的页面B。但是希望B能头部和侧边的菜单都按A菜单高亮，所以我使用了showLink:fasle和activePath属性希望达到这个效果，实际结果是我只能保证其中一个菜单高亮。于是我拉取vue-pure-admin最新的代码本地运行查看效果，结果也是一样，并且组件内容也不渲染了，控制台有warning报错！

### 如何复现该问题 (How to reproduce the problem)

nested.ts

`{
          path: "/nested/menu1/menu1-2",
          redirect: "/nested/menu1/menu1-2/menu1-2-1",
          meta: {
            title: $t("menus.pureMenu1-2"),
            keepAlive: true
          },
          children: [
            {
              path: "/nested/menu1/menu1-2/menu1-2-1",
              component: () =>
                import("@/views/nested/menu1/menu1-2/menu1-2-1/index.vue"),
              name: "Menu1-2-1",
              meta: {
                title: $t("menus.pureMenu1-2-1"),
                keepAlive: true
              }
            },
            {
              path: "/nested/menu1/menu1-2/menu1-2-2",
              component: () =>
                import("@/views/nested/menu1/menu1-2/menu1-2-2/index.vue"),
              name: "Menu1-2-2",
              meta: {
                activePath: "/nested/menu1/menu1-2/menu1-2-1",
                showLink: false,
                title: $t("menus.pureMenu1-2-2"),
                keepAlive: true
              }
            }
          ]
        },`

menu1-2-1/index.vue

`<script setup lang="ts">
import { ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
defineOptions({
  name: "Menu1-2-1"
});
const router = useRouter();
const jump = () => {
  router.push({
    name: "Menu1-2-2"
  });
};
const input = ref("");
const { t } = useI18n();
</script>

<template>
  <el-button @click="jump">跳转</el-button>
  <div class="dark:text-white">
    <p>{{ t("menus.pureMenu1") }}</p>
    <p style="text-indent: 2em">{{ t("menus.pureMenu1-2") }}</p>
    <p style="text-indent: 4em">{{ t("menus.pureMenu1-2-1") }}</p>
    <el-input v-model="input" />
  </div>
</template>
`

### 操作系统和浏览器信息 (Operating system and browser information)

![image](https://github.com/pure-admin/vue-pure-admin/assets/54517781/f4c97337-2455-433a-8cb0-ff562eb610eb)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前很忙 不接受任何新需求
