### ISSUE TITLE
函数式弹窗，点击取消按钮， 延时关闭无效

### ISSUE THREAD

**Issue by nineaiyu** [pure-admin/vue-pure-admin#1106]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/19207867/9db47e6f-4508-43ba-bdcd-e842210036f3)

函数式弹窗，点击取消按钮， 延时关闭无效， 右上角关闭有效

### 如何复现该问题 (How to reproduce the problem)

https://yiming_chang.gitee.io/vue-pure-admin/#/components/dialog

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/2f9bc7e18748a4f1f834d9018d74dccefdbafe27)
