### ISSUE TITLE
文档和演示站打不开了，提示404

### ISSUE THREAD

**Issue by ljzhsq2** [pure-admin/vue-pure-admin#1108]
### 描述问题 (Describe the problem)

文档和演示站打不开了，提示404

### 如何复现该问题 (How to reproduce the problem)

文档和演示站打不开了，提示404

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
gitee那边估计在维护什么 等等

**Comment by ljzhsq2** [comment]
> gitee那边估计在维护什么 等等

但是我看别人的项目可以正常打开。
好把，我再等等。
昨天终于发现这个宝藏项目，爱不释手了

**Comment by xiaoxian521** [comment]
https://gitee.com/oschina/git-osc/issues/I9JRKR?from=project-issue

我看有些人也有这种问题 估计是部分出现问题了

<img width="959" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/91a95040-16c7-45ea-a648-98ca909dbd98">

**Comment by xiaoxian521** [comment]
emm 等他们修复吧 看来很多人都有此类问题

<img width="773" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/bc9558a9-9d8d-4eee-9e97-39730012588b">

**Comment by lovebull** [comment]
是的，刚准备打开文档，发现404了

**Comment by xiaoxian521** [comment]
我们文档源码都是提供的哈 https://github.com/pure-admin/pure-admin-doc
自行下载 本地运行 
等待gitee那边修复

**Comment by lovebull** [comment]
我暂时用element-plus的文档了看看些。谢谢开源贡献者，开源开发者提供这么好用的的开源组件

**Comment by rockhcy** [comment]
如果将文档中两处linux路径换成适配windows系统的路径，启动脚本中的 export换成set 会不会就好了~😊
