### ISSUE TITLE
大佬，什么时候实现基于前端实现的权限

### ISSUE THREAD

**Issue by zimoStrive** [pure-admin/vue-pure-admin#1111]
### 描述问题 (Describe the problem)

看了项目很符合自己，但是想入手，发现权限方案和公司不匹配。等大佬出手

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
很简单 多了解下项目 目前很忙 只解决确定性bug 别的不考虑
