### ISSUE TITLE
登录处理建议

### ISSUE THREAD

**Issue by JakeWoki** [pure-admin/vue-pure-admin#1117]
### 描述问题 (Describe the problem)

pure-admin-thin 版本，其它版本不知道是不是这样
现在登录是在请求头加Authorization进行处理，文档没有说明加上写死了，差不多服务端是springboot，对新手不太友好

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [x] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提问题前证实 发截图 而不是一味文字描述

<img width="689" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/c5e4bc82-96f6-4ee0-b36b-5611c5616e74">
