### ISSUE TITLE
不算bug，一丢丢文档问题

### ISSUE THREAD

**Issue by weizhigang55** [pure-admin/vue-pure-admin#1120]
### 描述问题 (Describe the problem)

文档地址：https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/#%E5%A6%82%E4%BD%95%E5%8F%AA%E8%A6%81%E9%9D%99%E6%80%81%E8%B7%AF%E7%94%B1
加入使用静态路由只需要贴心按照文档的描述改就行，再修改login页面的时候我发现如果使用wen'dang文档下面的截图写的话会在初次登录的时候无法获取到除首页以外的其他静态路由（仅在首次登录时候会获取不到静态路由 刷新后可以）
![bug2](https://github.com/pure-admin/vue-pure-admin/assets/86505066/dbee7b18-5204-4751-af94-6e5e92a89adb)

修改后发现截图和上面让改写的差了一个setToken先后的区别，如果按照下图修改是可以的
![bug1](https://github.com/pure-admin/vue-pure-admin/assets/86505066/b7ccb218-83c0-416a-9049-a8b7927c8239)

### 如何复现该问题 (How to reproduce the problem)

<img width="1369" alt="bug3" src="https://github.com/pure-admin/vue-pure-admin/assets/86505066/91123a6c-dc19-4105-9301-45253066deec">

### 验证 (Verify)

- [ ] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
文档等我们开发任务完成后 会统一补充

**Comment by dingyaj** [comment]
这个只要静态路由的文档删了？
