### ISSUE TITLE
表格adaptive属性在列表初始化隐藏的时候高度异常

### ISSUE THREAD

**Issue by liguang-5896** [pure-admin/vue-pure-admin#1121]
### 描述问题 (Describe the problem)

表格adaptive属性在列表初始化隐藏的时候高度异常
默认显示
![image](https://github.com/pure-admin/vue-pure-admin/assets/50100828/81f0d47e-ddfb-408a-8f95-f836ea41cefe)
开始隐藏点击按钮后显示，表格变得很高
![image](https://github.com/pure-admin/vue-pure-admin/assets/50100828/5e1687de-afd4-4781-9ed6-18f5f3baf6ab)

### 如何复现该问题 (How to reproduce the problem)

<script setup lang="ts">
import { ref } from "vue";
import dayjs from "dayjs";
import { clone } from "@pureadmin/utils";

const date = dayjs(new Date()).format("YYYY-MM-DD");

const showTable = ref(1);

const props = withDefaults(
  defineProps<{
    height?: string;
  }>(),
  {
    height: null
  }
);

const columns: TableColumnList = [
  {
    label: "日期",
    prop: "date",
    width: "260",
    fixed: true
  },
  {
    label: "姓名",
    prop: "name",
    width: "260"
  },
  {
    label: "地区",
    prop: "state",
    width: "260"
  },
  {
    label: "城市",
    prop: "city",
    width: "260"
  },
  {
    label: "地址",
    prop: "address",
    width: "260"
  },
  {
    label: "邮编",
    prop: "post-code",
    width: "260"
  },
  {
    label: "操作",
    width: "120",
    fixed: "right",
    slot: "operation"
  }
];

const tableData = [
  {
    date,
    name: "Tom",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Jack",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Dick",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Harry",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Sam",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Lucy",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Mary",
    address: "No. 189, Grove St, Los Angeles"
  },
  {
    date,
    name: "Mike",
    address: "No. 189, Grove St, Los Angeles"
  }
];

const cloneData = clone(tableData, true);

const tableDataMore = cloneData.map(item =>
  Object.assign(item, {
    state: "California",
    city: "Los Angeles",
    "post-code": "CA 90036"
  })
);

function handleClick(row) {
  console.log(
    "%crow===>>>: ",
    "color: MidnightBlue; background: Aquamarine; font-size: 20px;",
    row
  );
}
</script>

<template>
  <el-button type="primary" @click="showTable += 1">
    点击一下---{{ showTable }}
  </el-button>

  <pure-table
    v-show="showTable === 1"
    adaptive
    :border="true"
    :data="tableDataMore"
    :columns="columns"
  >
  </pure-table>
  <pure-table
    v-show="showTable === 2"
    adaptive
    :border="true"
    :data="tableDataMore"
    :columns="columns"
  >
  </pure-table>
  <pure-table
    v-show="showTable === 3"
    adaptive
    :border="true"
    :data="tableDataMore"
    :columns="columns"
  >
  </pure-table>
</template>

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应仓库 提问 https://github.com/pure-admin/pure-admin-table/issues
最好提供视频

**Comment by liguang-5896** [comment]
<script setup lang="ts">
import { ref } from "vue";
import { tableDataMore } from "./data";
const showTable = ref(1);

const props = withDefaults(
  defineProps<{
    height?: string;
  }>(),
  {
    height: null
  }
);

const columns: TableColumnList = [
  {
    label: "日期",
    prop: "date",
    width: "260",
    fixed: true
  },
  {
    label: "姓名",
    prop: "name",
    width: "260"
  },
  {
    label: "地区",
    prop: "state",
    width: "260"
  },
  {
    label: "城市",
    prop: "city",
    width: "260"
  },
  {
    label: "地址",
    prop: "address",
    width: "260"
  },
  {
    label: "邮编",
    prop: "post-code",
    width: "260"
  },
  {
    label: "操作",
    width: "120",
    fixed: "right",
    slot: "operation"
  }
];

function handleClick(row) {
  console.log(
    "%crow===>>>: ",
    "color: MidnightBlue; background: Aquamarine; font-size: 20px;",
    row
  );
}
</script>

<template>
  <el-button type="primary" @click="showTable += 1">
    点击一下---{{ showTable }}
  </el-button>

  <pure-table
    v-show="showTable === 1"
    adaptive
    :border="true"
    :data="tableDataMore"
    :columns="columns"
  >
  </pure-table>
  <pure-table
    v-show="showTable === 2"
    adaptive
    :border="true"
    :data="tableDataMore"
    :columns="columns"
  >
  </pure-table>
  <pure-table
    v-show="showTable === 3"
    adaptive
    :border="true"
    :data="tableDataMore"
    :columns="columns"
  >
  </pure-table>
</template>

**Comment by xiaoxian521** [comment]
不要上来发一堆代码 直接提供复现仓库 会是更好的选择
