### ISSUE TITLE
线上预览版本504了

### ISSUE THREAD

**Issue by 178me** [pure-admin/vue-pure-admin#1122]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/50314769/a30b32f5-4d8d-427a-b877-88ad60a3809d)
这是网站的返回页面

### 如何复现该问题 (How to reproduce the problem)

打开线上预览版本

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
gitee估计在维护什么
