### ISSUE TITLE
保姆级文档的网址打不开了

### ISSUE THREAD

**Issue by zhonghy** [pure-admin/vue-pure-admin#1124]
### 描述问题 (Describe the problem)

保姆级文档的网址打不开了,  https://yiming_chang.gitee.io/vue-pure-admin    

### 如何复现该问题 (How to reproduce the problem)

https://yiming_chang.gitee.io/vue-pure-admin  这个地址出现了Bad Gateway
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.(code:0-26-32.01)  这个错误，麻烦及时修复一下。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by eryajf** [comment]
我这边临时拉起了一个，后续如有需要，也可长期保留：https://pure-admin-doc.eryajf.net/

> 可能极少链接有问题，但大部分内容不影响阅读。

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/1108
