### ISSUE TITLE
文档和预览挂了

### ISSUE THREAD

**Issue by wmc710** [pure-admin/vue-pure-admin#1125]
### 描述问题 (Describe the problem)

文档和预览挂了

### 如何复现该问题 (How to reproduce the problem)

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.(code:0-11-32.02)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
gitee在维护 等几天
