### ISSUE TITLE
`segmented`分段控制器尺寸变化问题及 `Element Plus 2.7.0` 新分段器的应用

### ISSUE THREAD

**Issue by QFifteen** [pure-admin/vue-pure-admin#1129]
### 描述问题 (Describe the problem)

分段控制器尺寸首次变化，未触发`handleResizeInit`函数问题，这个问题可追溯到：#1016 的代码调整。需要在`watch`中给回`immediate`配置即可。

第二个点是 Element Plus 在 `2.7.0` 已经新增了分段控制器组件 [#16258](https://github.com/element-plus/element-plus/pull/16258)。我想，可以给到相关的示例，就像**引导页模块**一样，拥有两种版本。

我乐意做此事并付诸了行动。但事实上，我没有一个很好的思路来直观、清晰的展示两种分段器实例，也恐自己的思路与作者想法岔路，所以先开`issues`来问问想法，也可以让更多的人参与到这个事

### 如何复现该问题 (How to reproduce the problem)

尺寸变化-复现gif：
![Kapture 2024-05-06 at 14 27 48](https://github.com/pure-admin/vue-pure-admin/assets/66454152/6bccbd48-18f3-4118-82fc-5c3e13e6e651)

### 操作系统和浏览器信息 (Operating system and browser information)

mac OS

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by kooriookami** [comment]
一个更像是 Antd 版本的风格

**Comment by QFifteen** [comment]
好的
