### ISSUE TITLE
【不是bug】请教一下关于Redialog组件渲染问题

### ISSUE THREAD

**Issue by dywtdance** [pure-admin/vue-pure-admin#1130]
### 描述问题 (Describe the problem)

系统菜单编辑页面openDialog方法
![image](https://github.com/pure-admin/vue-pure-admin/assets/116505573/ce7d80c3-14f0-4821-97e2-9f47ea1ebdaa)
点击【新增】按钮调用没问题，即使用默认参数不报错，但是点击【修改】按钮则报错
![image](https://github.com/pure-admin/vue-pure-admin/assets/116505573/863c632c-6091-4f5c-8b22-edccdd2c7e3a)
报错如下：
![image](https://github.com/pure-admin/vue-pure-admin/assets/116505573/75fb09fa-aad6-461a-83fb-1c809a382684)
Redialog组件没有弹出，初步判断是渲染的问题
![image](https://github.com/pure-admin/vue-pure-admin/assets/116505573/17c5d15e-2219-4681-918e-f8362b22af2e)

### 如何复现该问题 (How to reproduce the problem)

具体是根据完整版的菜单编辑页面的代码进行编辑，逻辑基本一样；

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前很忙 只解决确定性bug
