### ISSUE TITLE
菜单中点击外链会跳转两次

### ISSUE THREAD

**Issue by Jerome12138** [pure-admin/vue-pure-admin#1131]
### 描述问题 (Describe the problem)

`5.1.0`版本中增加了如下功能，但是未屏蔽掉`el-menu`本身的路由跳转逻辑，导致点击外链菜单会重复两次跳转。

```feat: 菜单支持a标签右键的所有浏览器行为 (#936)```

### 如何复现该问题 (How to reproduce the problem)

示例项目中点击菜单“外部页面-文档外链”中的任意链接

![image](https://github.com/pure-admin/vue-pure-admin/assets/32919763/59d8cb17-687b-43e5-bde6-60cc7ca33b6b)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/assets/44761321/9d810b50-e50b-4afb-bf24-9945b51bc5b7
