### ISSUE TITLE
函数式dialog参数设置后，拖拽全屏问题

### ISSUE THREAD

**Issue by chenxiangjun2010** [pure-admin/vue-pure-admin#1136]
### 描述问题 (Describe the problem)

1.弹窗设置draggable:true,如果弹窗高度超过一屏，那么点击拖拽之后，弹窗顶部被覆盖，不可再拖拽，导致没办法再继续输入
2.多层dialog属性会覆盖问题，比如第一层弹窗，fullscreen:false,在弹窗内，添加一个按钮，再去打开第二个弹窗，第二个弹窗设置
fullscreen:true,点击第二个弹窗的关闭按钮，第一个弹窗也会自动变成了全屏

### 如何复现该问题 (How to reproduce the problem)

1.属性设置draggable:true，高度超过一屏
2.2层弹窗，设置全屏属性不同

### 操作系统和浏览器信息 (Operating system and browser information)

谷歌浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
二次封装 https://element-plus.org/zh-CN/component/dialog.html#dialog-%E5%AF%B9%E8%AF%9D%E6%A1%86 
去看看他怎么用的
