### ISSUE TITLE
后端菜单无法展示到页面上

### ISSUE THREAD

**Issue by devil-ycl** [pure-admin/vue-pure-admin#1138]
### 描述问题 (Describe the problem)

您好，我在对接的过程中，已经获取到后端菜单的参数，并已经与内置的菜单合并了，然而只是展示出了内置菜单，后端返回的没有展示，请教一下这是什么原因引起的呢？ 需要如何解决这个问题？

![1](https://github.com/pure-admin/vue-pure-admin/assets/79831436/4962f91e-72fb-4f12-a7a8-94e024ead5bb)
![2](https://github.com/pure-admin/vue-pure-admin/assets/79831436/4b1c1a20-ff5f-4bb5-beeb-733197200900)
![3](https://github.com/pure-admin/vue-pure-admin/assets/79831436/a6026c36-3198-4b09-a409-ca555109dd53)

### 如何复现该问题 (How to reproduce the problem)

export const API_SYSTEM = (url: string) => `/system${url}`;

      proxy: {
        "/system": {
          // target: "http://114.132.172.194:11111",
          target: "http://127.0.0.1:11111",
          changeOrigin: true,
          rewrite: path => path.replace(/^\/system/, "")
        }
      },

![4](https://github.com/pure-admin/vue-pure-admin/assets/79831436/5957b399-ddc5-4e30-a83d-0af8beb0730e)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前很忙 仅解决确定性bug
