### ISSUE TITLE
[PR] 我抽离了各种布局模式下的语言选择器为公共组件

### ISSUE THREAD

**Issue by yymjku18** [pure-admin/vue-pure-admin#1142]
### 描述问题 (Describe the problem)

我在国际化，想追加新的语种时，改动了太多地方:
首先新语种语言包，根组件，国际化相关的共同hooks函数中进行对应的添加，这些共同部分添加配置是合情合理的。
但是，登录画面，各种布局下的导航栏也要追加一个新的`el-dropdown-item`，我认为这是有些繁琐的。

仔细阅读了各个布局模式的侧边栏的代码，发现不只是语言选择的部分，查询，消息，用户等很多地方都是可以复用的。
不然将来如果添加了更多丰富的布局模式，侧边栏不对将成倍维护很多近似代码。

我姑且抽离了国际化相关的部分，期待团队的验证与指点。

### 如何复现该问题 (How to reproduce the problem)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
是的 编写之初导航不算多 后面越来越多 但可能还需要更多的抽离 你可以自行发挥 后续有空我会`review`
