### ISSUE TITLE
混合模式的布局小bug

### ISSUE THREAD

**Issue by yymjku18** [pure-admin/vue-pure-admin#1144]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/77368194/295db641-f584-4f4b-b1b2-f31d2ed4d290)

### 如何复现该问题 (How to reproduce the problem)

中文模式下，第一次进入混合模式
从中文切换为英文
可以发现导航菜单会与工具菜单重合
此状态下如果刷新浏览器可以自动修复（自适应）

### 操作系统和浏览器信息 (Operating system and browser information)

目前只尝试了谷歌浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
小概率复现 这里并不属于平台的问题
