### ISSUE TITLE
如何删除title中的favicon.ico 图标

### ISSUE THREAD

**Issue by JiaMingJia** [pure-admin/vue-pure-admin#1154]
### 描述问题 (Describe the problem)

已经在index.html删除了相关代码和图标文件，但是项目运行起来后还是会显示

### 如何复现该问题 (How to reproduce the problem)

已经在index.html删除了相关代码和图标文件，但是项目运行起来后还是会显示

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前很忙 只解决确定性bug 其他看文档或自行研究
