### ISSUE TITLE
pure-table父容器高度自适应问题咨询

### ISSUE THREAD

**Issue by llllihtyihcy** [pure-admin/vue-pure-admin#1155]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/30112166/85e4348d-8e00-40a4-8496-708961dba5a5)
    /** 表格距离页面底部的偏移量，默认值为 `96` */
    offsetBottom?: number;
咨询一下，怎样设置距父容器底部距离，而不是页面底部距离

### 如何复现该问题 (How to reproduce the problem)

咨询一下，怎样设置距父容器底部距离，而不是页面底部距离

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前很忙 只解决确定性bug
