### ISSUE TITLE
pure-table组件多表头场景headerRenderer失效

### ISSUE THREAD

**Issue by zuopf769** [pure-admin/vue-pure-admin#1182]
### 描述问题 (Describe the problem)

pure-table组件多表头场景headerRenderer失效

### 如何复现该问题 (How to reproduce the problem)

跟了代码发现是如果是多级表头这里的代码有问题，直接替换了scopedSlots，把header scope丢失了
if (children?.length > 0) {
    scopedSlots = children.map(renderColumns);
 }

应该改为

if (children?.length > 0) {
    scopedSlots.default = children.map(renderColumns);
 }

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
能提供你的多表头场景headerRenderer失效代码示例不
