### ISSUE TITLE
pure-admin-thin 项目  vite-plugin-checker@0.7.2 插件未升级到 0.8.0

### ISSUE THREAD

**Issue by cyyinfo** [pure-admin/vue-pure-admin#1187]
### 描述问题 (Describe the problem)

pure-admin-thin 项目  vite-plugin-checker@0.7.2 插件未升级到 0.8.0

我看 [vue-pure-admin](https://github.com/pure-admin/vue-pure-admin) 已经升级了，但是
[pure-admin-thin](https://github.com/pure-admin/pure-admin-thin) 暂未升级

### 如何复现该问题 (How to reproduce the problem)

检查下 [pure-admin-thin](https://github.com/pure-admin/pure-admin-thin) package.json 文件
定位到 "vite-plugin-checker": "^0.7.2", 位置

### 验证 (Verify)

- [ ] 是否仔细阅读过 [文档](https://pure-admin.github.io/pure-admin-doc/) (Have you read [documentation](https://pure-admin.github.io/pure-admin-doc/) carefully)
- [ ] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by Ymonkey11** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的来信，查看后将尽快恢复，谢谢。
