### ISSUE TITLE
精简版登录页热更新报错

### ISSUE THREAD

**Issue by zzx131** [pure-admin/vue-pure-admin#438]
![EZML_`UPOJEX WKQR)ER%75](https://user-images.githubusercontent.com/22722085/218288903-500c4c63-edcd-4d9c-9242-728545530f99.png)

我在首页修改代码后，控制台报这个错误
[hmr] Failed to reload /src/views/login/index.vue. This could be due to syntax errors or importing non-existent modules. (see errors above)

**Comment by zzx131** [comment]
通过测试我发现，在热加载后，import.meta.env.VITE_ROUTER_HISTORY; 这里拿不到值，导致出现问题这个问题

**Comment by xiaoxian521** [comment]
修改了什么代码，提供复现步骤

**Comment by zzx131** [comment]
例如修改 登录页账号，修改成账号1234，这个时候会报错
<el-input
                  clearable
                  v-model="ruleForm.username"
                  placeholder="账号"
                  :prefix-icon="useRenderIcon(User)"
                />

**Comment by zzx131** [comment]
![image](https://user-images.githubusercontent.com/22722085/218301989-90d638f1-7f3c-4f81-9c1a-deb36193dbff.png)
例如修改账号，会不会刷新

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/pure-admin-thin/commit/2c887ee1d91aeacd54bbb5476959c216d0e8f011)
