### ISSUE TITLE
搜索的Form集成到Table中去，支持类似column一样的灵活定义

### ISSUE THREAD

**Issue by sunnyguohua** [pure-admin/vue-pure-admin#439]
**Is your feature request related to a problem? Please describe.**
希望通过一个灵活的Table控件实现不同列表的增删改查，不需要开发人员自己重新拼接组件

**Describe the solution you'd like**
搜索的Form放到Table中去，支持类似column一样的灵活定义

**Additional context**
如果能够支持，我可以对接后端，写一个类似低代码开发中数据定义的功能，提供在线的数据定义和增删改查功能

**Comment by xiaoxian521** [comment]
不好意思，不会支持，table是二次封装需要保持高可维护度，自行实现
