### ISSUE TITLE
切换页面刷新的问题

### ISSUE THREAD

**Issue by wang2650** [pure-admin/vue-pure-admin#440]
当切换页面的时候，比如从用户管理，文本框输入内容，点击角色管理，再返回用户管理。导致用户管理文本框输入的内容丢失。
我设了路由的keepalive=true没有用，还是会刷新用户管理的页面。 用framesrc也没用。
我在你的演示网站里测试，也是一样的问题。
页面切换的时候不刷新，这个如何解决呢？谢谢。

**Comment by xiaoxian521** [comment]
keepalive 多看文档怎么用 还有你不要初始化时主动去改值

**Comment by zpszz** [comment]
好无语
