### ISSUE TITLE
可以给表头数据添加其他自定义属性吗，比如这个selectValue

### ISSUE THREAD

**Issue by shirely1018** [pure-admin/vue-pure-admin#441]
const columns = ref<TableColumnList>([
    {
      label: "状态",
      prop: "status",
      **selectValue**: "车辆",
    }])

**Comment by xiaoxian521** [comment]
这种情况用 `headerRenderer` 多看案例

**Comment by shirely1018** [comment]
就是headerRenderer里边需要用到这个值
 headerRenderer: ({ column, $index }) => (
        <div>{column.selectValue}</div>
 ),

**Comment by shirely1018** [comment]
我这边需要实现这么一个需求，表头放一个select和input。
麻烦您指点一下，select和input框绑定的值可以放在哪里啊
![f522976b456ba5960e284b219756699](https://user-images.githubusercontent.com/33014031/218654851-0fbcd6e2-d4be-40d3-8a92-aa0b530a5af3.png)

**Comment by xiaoxian521** [comment]
就正常写 参考 https://github.com/pure-admin/pure-admin-table/blob/main/src/columns.tsx#L50
