### ISSUE TITLE
移动端通知栏tooltip点击穿透问题

### ISSUE THREAD

**Issue by wg666-del** [pure-admin/vue-pure-admin#443]
1、h5环境下点击通知栏
2、鼠标点击让tooltip出现
![image](https://user-images.githubusercontent.com/66242308/218658662-7a3d6a3e-a8c2-4b1b-bbb3-dd89140c0eb5.png)
3、点击tooltip后通知栏消失但tooltip还在
![image](https://user-images.githubusercontent.com/66242308/218658802-53d48dec-43a4-4ece-b9b5-3f0ef32b4762.png)

**Comment by xiaoxian521** [comment]
你是用浏览器模拟手机端测试的吗？我真机测试没问题

**Comment by xiaoxian521** [comment]
手机端的话一切以真机测试为主
