### ISSUE TITLE
面包屑中的一级菜单建议设置成不可点击

### ISSUE THREAD

**Issue by YOUAHAHAH** [pure-admin/vue-pure-admin#444]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/101163308/218704118-029e7be8-bbde-4df5-809e-0507e82084ea.png)

**Describe the solution you'd like**
点击 详情信息 跳转至404
**Describe alternatives you've considered**
src\layout\components\sidebar\breadCrumb.vue

**Additional context**

**Comment by YOUAHAHAH** [comment]
src\layout\components\sidebar\breadCrumb.vue
![image](https://user-images.githubusercontent.com/101163308/218713690-2ebe8a2a-397c-4b4d-adc3-2b7522c46e6a.png)

**Comment by xiaoxian521** [comment]
这属于你的需求 自行更改
