### ISSUE TITLE
【多级嵌套路由处理成一维数组】导致（带多个router-view的）嵌套路由失效

### ISSUE THREAD

**Issue by doghap** [pure-admin/vue-pure-admin#445]
我看源代码处理路由时将子路由也挂到根路由下，这导致：
1. 原来的路由被污染
2. （带多个router-view的）嵌套路由失效：原因是路由匹配到最外层挂到根路由的节点，并非原嵌套关系的路由

相关函数：formatFlatteningRoutes

**Comment by xiaoxian521** [comment]
参考多级菜单写法，按照平台规则走

**Comment by doghap** [comment]
我说的不是边栏菜单显示的问题，是页面展示的问题。
举个例子：
1. A和B,C,D页面是嵌套关系, BCD要在A页面里的router-view里展示，
2. 那么BCD的父级component应该是componentA，
现在的路由处理，BCD页面渲染时父级component是Layout, 而不是componentA，
这种方式只是做到了菜单层面的嵌套，并不是页面层面的嵌套， 你可以试一下<router-view>嵌套的场景

**Comment by xiaoxian521** [comment]
可能使用组件判断更合适呢？ 你的具体场景是什么呢

**Comment by wangwei8888** [comment]
谢谢 作者大大,完美解决了我的问题  -_-
