### ISSUE TITLE
权限管理热加载问题，页面报错

### ISSUE THREAD

**Issue by zzx131** [pure-admin/vue-pure-admin#449]
1、测试步骤
![image](https://user-images.githubusercontent.com/22722085/219307300-c789418a-2d9e-48b8-8a79-f93bd0943b20.png)
2、页面报错如下图
![image](https://user-images.githubusercontent.com/22722085/219308477-4e02beee-1bcd-4168-8f8a-ae0c65ccd74c.png)

**Comment by xiaoxian521** [comment]
精简版？

**Comment by zzx131** [comment]
正式版和精简版都有问题

**Comment by zzx131** [comment]
> 精简版？

完整版和精简版都会出现这个问题

**Comment by xiaoxian521** [comment]
自行参考https://github.com/pure-admin/pure-admin-thin/commit/2c887ee1d91aeacd54bbb5476959c216d0e8f011 处理 目前没时间 就是把 `import { initRouter } from "@/router/utils";` 放最后就行

**Comment by zzx131** [comment]
> 自行参考[pure-admin/pure-admin-thin@2c887ee](https://github.com/pure-admin/pure-admin-thin/commit/2c887ee1d91aeacd54bbb5476959c216d0e8f011) 处理 目前没时间 就是把 `import { initRouter } from "@/router/utils";` 放最后就行

按钮权限也同样出现这样的问题，但是没有`import { initRouter } from "@/router/utils";` 这一行代码

**Comment by zzx131** [comment]
![image](https://user-images.githubusercontent.com/22722085/219310722-f6151fed-909f-41ed-9c7f-3ab5e22398b8.png)

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/8fc9a4eca680956ba1805c285e6450a471e652c5)
