### ISSUE TITLE
关于后端返回的路由问题

### ISSUE THREAD

**Issue by zzx131** [pure-admin/vue-pure-admin#451]
大佬您好，目前后端返回的菜单中，由于数据的完整性，最后的叶子节点带了一个空的children数组，导致页面菜单加载不出来，具体返回数据如下格式，这个问题前端可以处理吗？多谢了
![(FDZJ E16LAKP6OL7(9RC{T](https://user-images.githubusercontent.com/22722085/219864612-d7f9e024-e11a-4f12-a596-0541861e3943.png)

**Comment by xiaoxian521** [comment]
这个不属于平台的问题 自行处

**Comment by zzx131** [comment]
已解决，现在通过后端Json进行处理
