### ISSUE TITLE
任意单根节点的页面，在根节点上方添加任意注释，将导致路由导航失效

### ISSUE THREAD

**Issue by xiaobo0113** [pure-admin/vue-pure-admin#452]
**Describe the bug**
任意单根节点的页面，如 guide/index.vue 的单根节点为 `<el-card>`，在 <el-card> 上方添加任意注释，如 `<!-- xxx -->`，将导致路由导航失效。

**To Reproduce**
1.  guide/index.vue 的根节点 `<el-card>` 上方添加任意注释，如 `<!-- xxx -->`
2. 点击登录按钮进入系统
3. 点击用户名，点击退出系统
4. 再次点击登录按钮进入系统
5. 此时点击左侧导航栏的任意导航，app-main 部分都显示不出来

**Expected behavior**
app-main 部分正常显示

**Screenshots**
![image](https://user-images.githubusercontent.com/22719696/220005435-b8c4c76b-dd13-4ec4-b4c5-21dc184aabc2.png)
![image](https://user-images.githubusercontent.com/22719696/220005792-7496d07b-d81a-49c2-a5fb-8139d174b4ce.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [edge]
 - Version [版本 110.0.1587.50 (正式版本) (64 位)]

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vue3-%E5%8D%95%E6%96%87%E4%BB%B6%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%E6%A0%B9%E6%A0%87%E7%AD%BE-%E4%BD%86%E6%98%AF%E5%B9%B3%E5%8F%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E8%BF%99%E4%B9%88%E7%94%A8%E5%91%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
