### ISSUE TITLE
pnpm build 的时候报错，没更改源码 

### ISSUE THREAD

**Issue by lyxlwz** [pure-admin/vue-pure-admin#453]
```pnpm build```的时候报错，没更改源码 

![image](https://user-images.githubusercontent.com/54365306/220239489-9ae24361-9ac7-4fa5-894c-54547da36c6a.png)

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#%E6%89%93%E5%8C%85%E6%97%B6%E6%8A%A5-unexpected-token-%E5%A6%82%E4%B8%8B%E5%9B%BE-%E6%9D%A5%E8%87%AA%E7%BE%A4%E5%8F%8B%E6%8F%90%E4%BE%9B

**Comment by lyxlwz** [comment]
哦哦谢谢，不好意思没看到文档这
