### ISSUE TITLE
vue-pure-admin精简版（非国际化版本）跳转页内菜单tab不高亮显示

### ISSUE THREAD

**Issue by achangchangchang** [pure-admin/vue-pure-admin#458]
复现流程
随便改了一个页面,将路由地址改为其他页面
![image](https://user-images.githubusercontent.com/33746006/220857904-0a469d08-d2e9-499a-a6af-90abec51e9b2.png)
将对应页面的showLink改为false
![image](https://user-images.githubusercontent.com/33746006/220858002-2cb46cd4-9caa-4b44-92fd-7d4629daec7d.png)
标签页不会高亮
![image](https://user-images.githubusercontent.com/33746006/220858091-8a738b67-3b0a-4ffa-85d8-97e0094ce8f6.png)

**Comment by xiaoxian521** [comment]
设置成 `showLink: false` 的话 标签页就没必要显示了 后面有时间会优化掉

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/f47fe9f19d3c71f389fa713744093aad14fb1592)

**Comment by north521** [comment]
> 设置成 `showLink: false` 的话 就没必要在标签页显示了 后面有时间会优化掉

比如我有一个创建页面，但又不需要菜单显示，也不需要传参，跳转时标签页不会高亮显示
