### ISSUE TITLE
关于cloc报错的问题

### ISSUE THREAD

**Issue by Shideshanxx** [pure-admin/vue-pure-admin#460]
在安装完 cloc，执行 pnpm cloc 后报错，错误信息是：

 > vue3-element-admin@0.0.0 cloc D:\0-github-repositories\vue-pure-admin-thin
 > NODE_OPTIONS=--max-old-space-size=4096 cloc . --exclude-dir=node_modules --exclude-lang=YAML
'perl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
 ELIFECYCLE  Command failed with exit code 1.

**Comment by xiaoxian521** [comment]
`windows` 可能需要安装 `perl` 参考 https://blog.csdn.net/wuxiaolongah/article/details/104741819
