### ISSUE TITLE
动态路由报错：No match found for location with path "/tabs/index"

### ISSUE THREAD

**Issue by juukee** [pure-admin/vue-pure-admin#461]
```
https://yiming_chang.gitee.io/vue-pure-admin/#/tabs/index
```
报错warning： No match found for location with path "/tabs/index"

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%87%BA%E7%8E%B0%E8%AD%A6%E5%91%8A-%E2%9A%A0%EF%B8%8F
