### ISSUE TITLE
携带参数跳转页内菜单,点击标签页切换的话参数会丢

### ISSUE THREAD

**Issue by achangchangchang** [pure-admin/vue-pure-admin#462]
复现流程:先点击按钮跳转按钮,然后点击标签,再点击回来,参数就丢了
![image](https://user-images.githubusercontent.com/33746006/221774191-251dc995-7c7a-48c6-aac7-d58f27015152.png)
![image](https://user-images.githubusercontent.com/33746006/221774728-8543d37e-7f88-4501-85f2-4989d4890310.png)

**Comment by xiaoxian521** [comment]
参考下图具体写法
<img width="702" alt="image" src="https://user-images.githubusercontent.com/44761321/221800973-b493d6d6-352f-4dd3-849c-7028b69c0b36.png">
