### ISSUE TITLE
vue router scrollBehavior() method doesn't work 

### ISSUE THREAD

**Issue by wangwei8888** [pure-admin/vue-pure-admin#464]
当页面内容比较长的时候, 在两个页面中来回切换,平台会记住滚动条的位置, 我想禁用记住滚动条位置这个功能,使得每次都滚动到顶端,
于是修改代码如下,但是依然无法每次都滚动到顶部!

When the content of the page is relatively long, if you switch back and forth between two pages, the platform will remember the position of the scroll bar. I want to disable the function of remembering the position of the scroll bar so that it will scroll to the top every time.

So modify the code as follows, but still can't scroll to the top every time!
> scrollBehavior(to, from, savedPosition) { 
       return { left:0,top: 0 }
  )

**Comment by xiaoxian521** [comment]
这个并不属于平台问题 请自行研究

**Comment by wangwei8888** [comment]
作者大大,其实这个需求的场景还是挺常见的:比如用户在首页往下浏览看到底之后,再点击顶部导航菜单,跳转到另一个页面,本想从顶部开始浏览,但是结果确是从首页滚动结束的位置开始浏览,用户体验不是很好!

**Comment by xiaoxian521** [comment]
你可以用精简版提供个完整的demo代码  我有空会看看

**Comment by xiaoxian521** [comment]
经过测试 的确存在 `scrollBehavior` 失效问题，不知道是不是 `vue-router` 的问题
暂时解决办法：在需要每次滚动到顶部的页面 `script` 中加上 `document.documentElement.scrollTop = 0`

**Comment by wangwei8888** [comment]
万分感激,谢谢作者大大
