### ISSUE TITLE
精简版-权限部分Bug反馈

### ISSUE THREAD

**Issue by AntyRia** [pure-admin/vue-pure-admin#466]
使用精简版框架，按照文档更改为纯静态路由后。
使用roles进行权限管理
但在登录进入后，系统检测不到roles的内容
具体如图所示
![image](https://user-images.githubusercontent.com/75578545/222970450-bb085071-08b9-4db4-9e73-0eaf1cbef401.png)

**Comment by AntyRia** [comment]
补充说明：原版精简版这里比对是两个数组找交集，但因为我后端返回每个账号一个角色，所以改成两个string进行比对（不影响精简版整体逻辑），问题在于登陆后首次拿不到值，所以侧边栏被隐藏了，刷新页面后页面就正常了（显示、权限拦截都正常了）

**Comment by xiaoxian521** [comment]
权限部分是动态路由

**Comment by xiaoxian521** [comment]
精简版那里权限部分自行删除就好了 只是给个demo放那参考

**Comment by AntyRia** [comment]
> 权限部分是动态路由
明白了，那就是文档中配置roles方式是要动态路由下才能使用的是吧
