### ISSUE TITLE
@pureadmin/utils 组件中 useECharts 的 getInstance 方法返回的实例总为 null

### ISSUE THREAD

**Issue by ChasonZheng** [pure-admin/vue-pure-admin#467]
**Describe the bug**
@pureadmin/utils 组件中 useECharts 的 getInstance 方法返回的实例总为 null

**Expected behavior**
useECharts 的 getInstance 方法应该返回创建的 echarts 实例

**Screenshots**
![image](https://user-images.githubusercontent.com/33928208/223017692-afbfdb93-9aa4-4b2b-a6c0-9d579a1a46ba.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu22.04
 - Browser chrome
 - Version 110.0.5481.177

**Comment by xiaoxian521** [comment]
多看例子 不是这么使用

**Comment by heyingjie** [comment]
您好，我这边看了下，没有看到文档中有关于getInstance的例子。还有在vue pure admin的界面中加了句代码打印数据，打印的语句是放在setOptions之后的，看到getInstance的确返回是null。

`<script setup lang="ts">
import { type PropType, ref, computed } from "vue";
import { useDark, useECharts } from "@pureadmin/utils";

const props = defineProps({
  data: {
    type: Array as PropType<Array<number>>,
    default: () => []
  },
  color: {
    type: String,
    default: "#41b6ff"
  }
});

const { isDark } = useDark();

const theme = computed(() => (isDark.value ? "dark" : "light"));

const chartRef = ref();
const { setOptions, getInstance } = useECharts(chartRef, {
  theme,
  renderer: "svg"
});

setOptions({
  container: ".line-card",
  xAxis: {
    type: "category",
    show: false,
    data: props.data
  },
  grid: {
    top: "15px",
    bottom: 0,
    left: 0,
    right: 0
  },
  yAxis: {
    show: false,
    type: "value"
  },
  series: [
    {
      data: props.data,
      type: "line",
      symbol: "none",
      smooth: true,
      color: props.color,
      lineStyle: {
        shadowOffsetY: 3,
        shadowBlur: 7,
        shadowColor: props.color
      }
    }
  ]
});

console.log("getInstance:", getInstance());
</script>

<template>
  <div ref="chartRef" style="width: 100%; height: 60px" />
</template>
`

**Comment by xiaoxian521** [comment]
你这么用肯定不行啊 不要上来就用啊
还没有实例化好 通过按钮点击调用或延时调用
