### ISSUE TITLE
Windows用户启动项目后mock请求404

### ISSUE THREAD

**Issue by ZmSama** [pure-admin/vue-pure-admin#469]
我看了以往的issues，应该是平台问题，但是那个问题提出者并没有说出解决方案，我尝试了看了一下控制台的报错是什么TSD，然后%之类的一堆乱码，猜测是平台编码问题。所有解决方案如下：

**删除mock文件夹下的文件，重新自己新建文件，将内容一个一个复制过去即可解决问题**
如果项目能做到编码问题的改善就更好了，如果不能也没关系，mock文件也不多

**Comment by xiaoxian521** [comment]
从未有此问题

**Comment by xiaoxian521** [comment]
平台用 [vite-plugin-mock](https://www.npmjs.com/package/vite-plugin-mock) 提供mock服务，如果有问题请去这里提，非平台问题

**Comment by xiaoxian521** [comment]
还有就是你说的删除 重新建就行，这一看就是你本地环境问题
