### ISSUE TITLE
pure-table组件事件@current-change分页时点击数据行时调用分页错误

### ISSUE THREAD

**Issue by slency** [pure-admin/vue-pure-admin#470]
**Describe the bug**
pure-table组件事件@current-change分页时，@current-change="onCurrentChange"，点击数据行时，onCurrentChange方法捕获参数为当前行数据对象，和切换分页的参数不一致导致分页请求错误

**To Reproduce**
1. 示例中pure-admin-table高级用法分页中
2. 点击数据行触发分页方法，当前页数请求错误

**Comment by xiaoxian521** [comment]
[Duplicate](https://github.com/pure-admin/pure-admin-table/issues/11)
