### ISSUE TITLE
标签页操作：混合模式下，打开showLink:false页面，刷新页面左侧导航栏一直加载状态

### ISSUE THREAD

**Issue by ruall** [pure-admin/vue-pure-admin#473]
混合模式：完整版预览->标签页操作->打开1详情页，刷新页面左侧路由会一直是加载状态
![image](https://user-images.githubusercontent.com/30111680/225223259-5f9e79ae-efad-40c6-b5cc-65568d590202.png)

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/40b7e12eaa9d4a35d7a9de099999b14b8fce0bff)
