### ISSUE TITLE
点击内容全屏时候 出现无限递归

### ISSUE THREAD

**Issue by Lin-Van** [pure-admin/vue-pure-admin#474]
https://github.com/pure-admin/vue-pure-admin/blob/a8a3e5b303d4f022cf4570c5b63c238486755cfc/src/store/modules/settings.ts#L27
我看预览的项目是没错 但是拉下来本地运行就无法内容全屏
以下是报错：
Uncaught InternalError: too much recursion
    track reactivity.esm-bundler.js:263
    get2 reactivity.esm-bundler.js:497
    get pinia.mjs:908
    toRaw reactivity.esm-bundler.js:991
    hasOwnProperty2 reactivity.esm-bundler.js:457
    hasOwnProperty2 reactivity.esm-bundler.js:459
    hasOwnProperty2 reactivity.esm-bundler.js:459
    hasOwnProperty2 reactivity.esm-bundler.js:459
    hasOwnProperty2 reactivity.esm-bundler.js:459
    hasOwnProperty2 reactivity.esm-bundler.js:459

**Comment by xiaoxian521** [comment]
无法复现

**Comment by Lin-Van** [comment]
> 无法复现

打包之后不会有问题，可是在vscode中使用pnpm dev运行就会出现

**Comment by Lin-Van** [comment]
> 无法复现
解决该问题的方法为：将xxx.hasOwnProperty(‘yyy’)修改为Object.prototype.hasOwnProperty.call(xxx, ‘yyy’)
我参考以下解决了问题 [https://blog.csdn.net/m0_44981797/article/details/124709808](url)
