### ISSUE TITLE
精简版，生产打包，VITE_PUBLIC_PATH不为时/，部署到nginx的子目录会报错

### ISSUE THREAD

**Issue by LokhangQ** [pure-admin/vue-pure-admin#475]
例如：
指定VITE_PUBLIC_PATH为/admin，然后使用pnpm build命令打包
![image](https://user-images.githubusercontent.com/25002126/225488571-f66fc133-9e5e-4400-9ce0-0ea23a92a6ee.png)

将打包处理的dist文件下的所有文件复制放入到nginx目录下的html/admin目录
![image](https://user-images.githubusercontent.com/25002126/225488650-4c12843d-8d07-4b2e-8a4b-7a4ead4c0fee.png)

nginx的配置为：
![image](https://user-images.githubusercontent.com/25002126/225488750-b59a8533-b4b8-4eea-b3be-8c59ae72b1fa.png)

浏览器报错信息
![image](https://user-images.githubusercontent.com/25002126/225488899-cc42e4ae-005c-4261-8538-eb9670c9fbc4.png)

一个nginx可能要部署多个项目，所以要放在不同的子目录下，不能直接放在根目录下，但是这种部署方式会报错。

**Comment by xiaoxian521** [comment]
看文档
