### ISSUE TITLE
导航模式为混合模式时鼠标放在头部菜单更多（。。。）图标时一直闪动

### ISSUE THREAD

**Issue by gerryge** [pure-admin/vue-pure-admin#480]
**Describe the bug**
导航模式为混合模式时鼠标放在头部菜单更多（。。。）图标时一直闪动。

**To Reproduce**
1. 用Chrome浏览器打开，切换导航模式到混合模式
2. 鼠标放在头部菜单更多的三个点（。。。）图标时，下拉菜单一直跳动

**Expected behavior**
下拉菜单应该不闪动

**Screenshots**
![menu-flickering](https://user-images.githubusercontent.com/6952917/225854299-7f15345d-f28c-41dc-a59b-4febb5979375.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: Version 111.0.5563.65 (Official Build) (64-bit)

**Additional context**
在Edge Version 110.0.1587.63 (Official build) (64-bit) 可以复现问题
Edge Version 111.0.1661.41 (Official build) (64-bit) 无法复现问题
Edge Version 111.0.1661.44 (Official build) (64-bit) 无法复现问题

**Comment by xiaoxian521** [comment]
不考虑兼容各个版本，请使用最新版

**Comment by gerryge** [comment]
> 不考虑兼容各个版本，请使用最新版

你好，我使用的Chrome和Edge都是最新版本，都可以复现问题。你可以最近点下很容易复现。
![image](https://user-images.githubusercontent.com/6952917/226228334-196c3e81-c375-470c-ab0f-dc897f85ba46.png)

![image](https://user-images.githubusercontent.com/6952917/226228271-e531b5d5-45a0-4a59-9e0b-f89684d6b052.png)
