### ISSUE TITLE
不太清楚如何使用useECharts里的setOptions方法

### ISSUE THREAD

**Issue by x-carrier** [pure-admin/vue-pure-admin#485]
代码片段
![image](https://user-images.githubusercontent.com/49521216/226787086-d0210388-5948-4cfe-a785-f6e16a0d4905.png)

页面截图
![image](https://user-images.githubusercontent.com/49521216/226787240-0d287096-46e6-41c1-a3c4-13623aa6411b.png)

问题描述
在onBeforeMount方法里触发setOptions方法可以渲染图表
而后选择下拉框触发change方法重新获取图表数据后调用setOptions方法
页面显示空白
![image](https://user-images.githubusercontent.com/49521216/226787375-e8234489-7edd-4c22-9ff8-298869b0b239.png)
请问是使用的方法不对吗

**Comment by jim-jay** [comment]
是如何解决的？
