### ISSUE TITLE
【bug】如果引入iconfont的图标，会覆盖到element-plus的图标

### ISSUE THREAD

**Issue by pcloth** [pure-admin/vue-pure-admin#486]
**问题描述**
如果引入iconfont的图标，会覆盖到element-plus的图标引用，并造成element-plus组件的原生图标不正确
![1679455128417](https://user-images.githubusercontent.com/18551791/226793494-88733acf-e141-4294-ae94-31e5aeaf28d0.png)

**复现**
1. 引入一个iconfont图标，内容为
`
.icon-arrow-down:before {
    content: "\e89a";
}
`

**期待结果**
`
<i class="iconfont icon-arrow-down"/>
`
显示iconfont图标

`
<i class="el-icon el-input__icon icon-arrow-down"><svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M831.872 340.864 512 652.672 192.128 340.864a30.592 30.592 0 0 0-42.752 0 29.12 29.12 0 0 0 0 41.6L489.664 714.24a32 32 0 0 0 44.672 0l340.288-331.712a29.12 29.12 0 0 0 0-41.728 30.592 30.592 0 0 0-42.752 0z"></path></svg></i>
`
显示element的图标

**Screenshots**
![1679455536410](https://user-images.githubusercontent.com/18551791/226794435-5f355291-e2b3-4db5-9e17-b9c6e14e585f.png)

**移除iconfont之后element图标能正确显示**

**Comment by xiaoxian521** [comment]
图标用法看文档

**Comment by xiaoxian521** [comment]
`iconfont` 你可以自定义名称啊

**Comment by pcloth** [comment]
> `iconfont` 你可以自定义名称啊

和`iconfont`这个font-family名称没有关系，图标名称只要重名的都会有这个问题，很容易造成隐藏小bug。
