### ISSUE TITLE
无法实现嵌套子路由

### ISSUE THREAD

**Issue by wangwei8888** [pure-admin/vue-pure-admin#489]
![image](https://user-images.githubusercontent.com/36029972/227473096-85826e27-3128-4b68-b8bb-8f3ca303bd00.png)

![image](https://user-images.githubusercontent.com/36029972/227433382-51f2861a-2a5e-48e5-a37a-dc0e29dc8b3d.png)

如图所示:需要实现点击下方子路由,上方绿色导航区域保持不变
其中路由代码如下:
```
export default {
  path: "/nest",
  meta: {
    title: "嵌套路由"
  },
  children: [
    {
      path: "/nest/index",
      name: "nest",
      component: () => import("@/views/nest/index.vue"),
      meta: {
        title: "嵌套路由"
      }
      // children: [
      //   {
      //     path: "/nest/index/:id",
      //     name: "inner",
      //     component: () => import("@/views/nest/child.vue"),
      //     meta: {
      //       title: "菜单"
      //     }
      //   }
      // ]
    },
    {
      path: "/nest/index/:id",
      name: "inner",
      component: () => import("@/views/nest/child.vue"),
      meta: {
        title: "菜单",
        showLink: false
      }
    }
  ]
} as RouteConfigsTable;
```
外层布局代码
```
<template>
  <div class="flex flex-col">
    <div class="border-green-500 border-[1px]">
      <h1>嵌套路由外层导航区域(要求点击下方子路由,导航区域保持不变)</h1>
      <div>
        <router-link to="/nest/index/1">点击跳转到子路由 1</router-link>
        <router-link to="/nest/index/2">点击跳转到子路由 2</router-link>
      </div>
    </div>
    <div class="mt-10 w-[500px] h-[1000px] border-red-500 border-[1px]">
      <h1>子路由显示区域</h1>
      <router-view />
    </div>
  </div>
</template>
```

实际效果:点击切换子路由之后,整个父布局都被切换了

![image](https://user-images.githubusercontent.com/36029972/227433538-c557b62e-3ca1-4da8-8c53-7a03143eecbe.png)

已经fork pure-admin-thin 精简版代码
仓库地址如下:
https://github.com/wangwei8888/pure-admin-thin.git

小弟试了好多方法都无法实现,希望作者大大抽空帮忙看看,感激不尽!

**Comment by xiaoxian521** [comment]
更推荐使用组件方式 [duplicate](https://github.com/pure-admin/vue-pure-admin/issues/445#issuecomment-1437914456)
如果要使用嵌套路由方式可以参考这个改下 https://gitee.com/yiming_chang/vue-pure-admin/commit/96365a023888accd361b919f76b10ff80255bad7
