### ISSUE TITLE
仔细读完文档，菜单项 auths 配置项比较费解

### ISSUE THREAD

**Issue by delai** [pure-admin/vue-pure-admin#492]
以下是我费解的地方，可能是我理解岔了，盼作者答复，感谢感谢！
假设是静态路由，菜单项里配置了 auths， 对应的页面里的某个按钮，也如下加了配置，那么这对任何用户都是一样的，如何体现出权限不同导致的不同人看到的不一样呢？所以，我觉得针对按钮的权限控制跟菜单类似，还是得按照角色来判断才对啊。

```
<Auth value="btn_add">
  <el-button type="success"> 拥有code：'btn_add' 权限可见 </el-button>
</Auth>
```

**Comment by t-1an** [comment]
> 权限要做好 肯定需要动态路由 而不是仅仅在前端配置

Hi 作者，感谢您的代码分享和耐心解答。我想请教一下动态路由是哪个字段去定义Role的按钮权限的呢？

我想实现的功能简单来说就是：某个页面admin和common都可以访问，但是admin具备'btn:add'权限可以看见按钮，而common不行。
