### ISSUE TITLE
最新版，tab标签的【关闭】小图标出现了两个

### ISSUE THREAD

**Issue by caimingyi484** [pure-admin/vue-pure-admin#494]
最新版，tab标签的【关闭】小图标出现了两个，该如何解决？

**Comment by xiaoxian521** [comment]
贴图

**Comment by caimingyi484** [comment]
![20230329142239](https://user-images.githubusercontent.com/51154104/228447685-4310314d-1072-427f-a70e-63c6f5bf1bf7.png)

**Comment by caimingyi484** [comment]
> 贴图

![20230329142239](https://user-images.githubusercontent.com/51154104/228447851-7fa58d64-0503-494e-a009-a81e375561e3.png)

**Comment by xiaoxian521** [comment]
无法复现
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/44761321/228448591-e8ec3af5-957c-415e-8689-c890ad4b0c0a.png">

**Comment by caimingyi484** [comment]
> 无法复现 <img alt="image" width="1259" src="https://user-images.githubusercontent.com/44761321/228448591-e8ec3af5-957c-415e-8689-c890ad4b0c0a.png">

main分支最新版，Chrome浏览器正常，在Mircosoft Edge（版本 111.0.1661.54 (正式版本) (64 位)）浏览器下会出现
