### ISSUE TITLE
双击分页表格触发current-change

### ISSUE THREAD

**Issue by yh-mai** [pure-admin/vue-pure-admin#495]
**Describe the bug**
chrome：双击带有分页功能的表格某一行数据，会出现loading，并且显示正在加载中 【object,object】页...字样，有一定的点击限制，隔一小段时间（很短），再次双击会重复出现
edge： 单击即可实时复现

**To Reproduce**
1. 前往 https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/high 页面
2. 选择分页、加载动画、动态列表格
3. chrome 双击表格中数据，edge单击即可
4. 出现loading，并且显示正在加载中 【object,object】页...字样

**Screenshots**
![9C4C9B0C-C781-4b01-9FE6-17A183CC3D48](https://user-images.githubusercontent.com/72854238/228481527-d014db4b-c9d8-4499-83a4-3f92bf500940.png)

**Desktop (please complete the following information):**
 - Browser：chrome，edge

**Comment by yh-mai** [comment]
不对，都是单击就会出现，只是点一下后要换个位置，这个更容易出来

**Comment by xiaoxian521** [comment]
提问题前先看看 `issues` 有没有相同的 [Duplicate](https://github.com/pure-admin/pure-admin-table/issues/11)

**Comment by yh-mai** [comment]
单击表格中数据显示会显示 正在加载【object,object】页...，此时点击分页，也是显示的 正在加载【object,object】页...
