### ISSUE TITLE
单击分页表格中的数据，显示 正在加载第[obect object]页...

### ISSUE THREAD

**Issue by yh-mai** [pure-admin/vue-pure-admin#496]
**Describe the bug**
单击分页表格中的数据，就会显示 正在加载第[obect object]页...，并且此时正常点击 分页的按钮也会出现

**To Reproduce**
1. 前往预览版的此页面： https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/high
2. 选择分页、加载动画、动态列表格
3. 单击表格中的某一条数据
4. 出现loading，并且显示正在加载第[obect object]页...字样
5. 此时使用分页功能
6. 也会出现loading，并且显示正在加载第[obect object]页...字样

**Screenshots**
![image](https://user-images.githubusercontent.com/72854238/228487777-d8b18b9e-0519-4595-b90b-24181da11853.png)

**Comment by yh-mai** [comment]
点击后换一个位置，再次点击可重复复现

**Comment by yh-mai** [comment]
同样作为一个程序员，所以我很理解测试给自己提bug时候，同样的问题提了多次的心情（那冲动不是一次两次的），但有时候，类似的标题可能只是一个引子，所以如果可以，花一点时间将描述看一下

**Comment by xiaoxian521** [comment]
> **Describe the bug** 单击分页表格中的数据，就会显示 正在加载第[obect object]页...，并且此时正常点击 分页的按钮也会出现
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. 前往预览版的此页面： https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/high
> 2. 选择分页、加载动画、动态列表格
> 3. 单击表格中的某一条数据
> 4. 出现loading，并且显示正在加载第[obect object]页...字样
> 5. 此时使用分页功能
> 6. 也会出现loading，并且显示正在加载第[obect object]页...字样
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/72854238/228487777-d8b18b9e-0519-4595-b90b-24181da11853.png)

这样描述就很清楚了 有空我修复下 谢谢反馈

**Comment by yh-mai** [comment]
好的，非常感谢

**Comment by yh-mai** [comment]
> > **Describe the bug** 单击分页表格中的数据，就会显示 正在加载第[obect object]页...，并且此时正常点击 分页的按钮也会出现
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. 前往预览版的此页面： https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/high
> > 2. 选择分页、加载动画、动态列表格
> > 3. 单击表格中的某一条数据
> > 4. 出现loading，并且显示正在加载第[obect object]页...字样
> > 5. 此时使用分页功能
> > 6. 也会出现loading，并且显示正在加载第[obect object]页...字样
> > 
> > **Screenshots** ![image](https://user-images.githubusercontent.com/72854238/228487777-d8b18b9e-0519-4595-b90b-24181da11853.png)
> 
> 这样描述就很清楚了 有空我修复下 谢谢反馈

好的，非常感谢

**Comment by yh-mai** [comment]
本地启动了下，在如下位置进行打印输出
![image](https://user-images.githubusercontent.com/72854238/228495518-dad23b94-ae55-4d7a-8239-bb46230c9648.png)

发现单击表格时触发了，打印了一次
分页功能在触发上面的bug前，进行切换会打印一次，触发后进行切换，会打印两次

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/638a95a4af9ceaa22e467100baa3c75a41ff504c)
