### ISSUE TITLE
在edge浏览器下，tab标签的【关闭】小图标出现了两个

### ISSUE THREAD

**Issue by caimingyi484** [pure-admin/vue-pure-admin#497]
**Describe the bug**
main分支最新版，Chrome浏览器正常，在Mircosoft Edge（版本 111.0.1661.54 (正式版本) (64 位)）浏览器下会出现tab标签的【关闭】小图标出现了两个，请看贴图

**To Reproduce**
请用edge浏览器访问 [https://yiming_chang.gitee.io/vue-pure-admin/](url)

**Screenshots**
![20230329173818](https://user-images.githubusercontent.com/51154104/228493794-96a4c2b2-6b9b-4bd8-8192-fa4f70bb618b.jpg)

**Comment by xiaoxian521** [comment]
不考虑edge
