### ISSUE TITLE
每次生产构建完，有些页面跳转会卡住，控制台信息如下：  TypeError: Failed to fetch dynamically imported module: xxx，刷新页面又恢复正常了

### ISSUE THREAD

**Issue by lyf3358** [pure-admin/vue-pure-admin#498]
每次生产构建完，有些页面跳转会卡住，控制台信息如下：  TypeError: Failed to fetch dynamically imported module: xxx，刷新页面又恢复正常了
![image](https://user-images.githubusercontent.com/46048856/228552231-7222da42-87a9-4420-8f1c-eceedafe77b9.png)
请问如何解决呢？

**Comment by xiaoxian521** [comment]
。。。。。 那是你自己写的问题 无法复现

**Comment by lyf3358** [comment]
@xiaoxian521 每次构建后hash值发生变化，如果正在访问旧的页面，就会报错，刷新才能加载新的文件

**Comment by GD4007** [comment]
> @xiaoxian521 每次构建后hash值发生变化，如果正在访问旧的页面，就会报错，刷新才能加载新的文件

我也遇到这问题了，我试了下pure-admin-thin也会有这问题，现在有解决吗

**Comment by GD4007** [comment]
> @xiaoxian521 每次构建后hash值发生变化，如果正在访问旧的页面，就会报错，刷新才能加载新的文件

我也遇到这问题了，我试了下pure-admin-thin也会有这问题，现在有解决吗 @lyf3358
