### ISSUE TITLE
请问启动报这个错是什么问题呢，我试了好几个16 以上的 node 版本都不行

### ISSUE THREAD

**Issue by fxzer** [pure-admin/vue-pure-admin#499]
![image](https://user-images.githubusercontent.com/68853957/228796105-fda55702-5a8a-4c6e-9af4-4f63eed82a85.png)
OS:Mac OS13
pnpm : 7.27.1
node:v16.18.1

**Comment by xiaoxian521** [comment]
如何复现它

**Comment by xiaoxian521** [comment]
`mac` 删除 `pnpm` 命令

```
cd /usr/local/lib/node_modules 
rm -rf pnpm
npm install -g pnpm
```
