### ISSUE TITLE
菜单 反馈！意见！需求

### ISSUE THREAD

**Issue by yanmin41295** [pure-admin/vue-pure-admin#501]
目前看二级菜单在只用一个子菜单情况下，需要加上 showParent: true才会显示二级，如果不加只会显示一级菜单，同理三级、四级...类似

其实我认为更好的实现是不需要这个字段，只要有childern则有下一级

![image](https://user-images.githubusercontent.com/80966418/229263370-35ce0f1c-a956-45f7-a28f-a123deb04a3d.png)

**Comment by xiaoxian521** [comment]
可自行二次开发
