### ISSUE TITLE
我在看您的代码发现"@pureadmin/utils": "^1.8.5" 的主页地址是 404

### ISSUE THREAD

**Issue by ldw4033** [pure-admin/vue-pure-admin#505]
您好，我在拜读您的代码，发现 @pureadmin/utils package.json 中homepage 地址是 https://github.com/xiaoxian521/pure-admin-utils/tree/main/#readme 显示是 404 ，找不到正确的链接地址，请修正。

**Comment by xiaoxian521** [comment]
Duplicate of https://github.com/pure-admin/pure-admin-utils-docs/issues/4
