### ISSUE TITLE
设置`showLink: false`后,刷新菜单会导致菜单无法正常加载

### ISSUE THREAD

**Issue by Yuirki** [pure-admin/vue-pure-admin#507]
![image](https://user-images.githubusercontent.com/51293718/230320266-b6c9db34-eb98-43c7-8be3-846c27997c75.png)
是否应改为设置`showLink: false`后刷新菜单仍然能够正常加载菜单，刷新后的菜单选中状态，可以保留刷新前的选中状态，或当前路由的父级菜单。

**Comment by Yuirki** [comment]
拉取最新代码已修复

**Comment by itliujia** [comment]
混合模式下还是这样
