### ISSUE TITLE
getAuths()函数获取当前页面对应的Auths时，是否有缓存机制？切换用户登录后，获取到的还是原来的信息

### ISSUE THREAD

**Issue by rbj0820** [pure-admin/vue-pure-admin#508]
目前遇到的情况是这样的，一开始登录的账号是张三，显示权限【A,B,C,D】；退出系统使用李四登录后，李四的权限只有【A，B】，但getAuths()返回的还是【A,B,C,D】，一定要浏览器刷新后，getAuths()返回的才正确。
![image](https://user-images.githubusercontent.com/20568714/230324781-108d6c76-65f8-4736-9f9b-fa6fa0fd4f67.png)
![image](https://user-images.githubusercontent.com/20568714/230325683-500db22f-d771-4e0b-abe7-1c1d3dbc0755.png)

![image](https://user-images.githubusercontent.com/20568714/230324980-320c01db-d0d9-4ffe-a78c-6412aba255ba.png)
![image](https://user-images.githubusercontent.com/20568714/230325414-309bb4c3-decd-434a-9a5b-9ea7037a10eb.png)

**Comment by xiaoxian521** [comment]
当然有啊 要先清空 https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/permission/page/index.vue#L37&L38

**Comment by xiongbb** [comment]
我也遇到同样问题，使用的是精简非国际版，在storageSession里没看到async-routes，使用vue-dev tools看到退出后routes是清空数据了的，重新登录也是对的，但是getAuth读出来是错的

**Comment by AlcoholTobaccoCode** [comment]
我也同样遇到此问题，使用`storageSession().removeItem("async-routes");`之后也必须刷新才能获取到最新的权限

**Comment by xiaoxian521** [comment]
额 清空重新获取 这个获取就是重新请求动态路由接口 参考权限管理页面 无需刷新

**Comment by xiaoxian521** [comment]
> 我在useUserStore的logOut()里，router.push("/login");前面加了个router.go(0); 强制更新路由状态 ，不优雅，倒是解决了。。

提供的有重制动态路由的方法 https://github.com/pure-admin/vue-pure-admin/blob/main/src/store/modules/user.ts#L63 没必要用什么强制更新这种很不优雅的东西

**Comment by xiaoxian521** [comment]
没事多看看文档 文档都有

**Comment by xiongbb** [comment]
> > 我在useUserStore的logOut()里，router.push("/login");前面加了个router.go(0); 强制更新路由状态 ，不优雅，倒是解决了。。
> 
> 提供的有重置动态路由的方法 https://github.com/pure-admin/vue-pure-admin/blob/main/src/store/modules/user.ts#L63 没必要用什么强制更新这种很不优雅的东西

user.ts里的resetRouter(); 这个没有动，而且我在vue devtools里看了，确实清空了，但是
`function getAuths(): Array<string> {
  return router.currentRoute.value.meta.auths as Array<string>;
}`
读出来的依然是上次登录用户的auths。在storageSession，pinia等几个地方都看了，也没有找到缓存

**Comment by xiaoxian521** [comment]
能提供个具体的复现仓库吗 获取我可以看看 我也极其不推荐不喜欢什么强制刷新

**Comment by xiongbb** [comment]
> 能提供个具体的复现仓库吗 或许我可以看看 我也极其不推荐不喜欢什么强制刷新

我已经使用pure-admin-thin 模拟重现出了问题。我先使用admin登录，然后登出，再去mock数据里修改const permissionRouter,去掉了btn_edit，再次登录，问题如下图
[问题](https://gitee.com/fishdong1107/typora-image/raw/master/image/202303/07/err.png)

**Comment by xiaoxian521** [comment]
额，修改`mock`数据是需要重启服务才能生效

**Comment by xiaoxian521** [comment]
最好是一次模拟出来 而不是通过修改代码

**Comment by xiongbb** [comment]
> 额，修改`mock`数据是需要重启服务才能生效

截图里，getAsyncRoutes修改后返回了新的值，btn_edit已经没有了

**Comment by rbj0820** [comment]
> 当然有啊 要先清空 https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/permission/page/index.vue#L37&L38

这个缓存设计是不是有逻辑问题，都用其他账号重新登录了，为什么缓存不更新呢
