### ISSUE TITLE
hasAuth取到上一次的登录信息,必须要刷新浏览器才能取得新值。

### ISSUE THREAD

**Issue by xiongbb** [pure-admin/vue-pure-admin#509]
精简非国际版，使用mock数据，admin用户，第一次登录后退出，修改mock数据的permissionRouter，删除btn_edit，再次登录，从浏览器network页签可以看到asyncRoutes已经返回了修改后的值，但是进入button页面，hasAuth显示的还是有btn_edit权限，浏览器刷新一次后就没有btn_edit了。
<img width="1919" alt="err" src="https://user-images.githubusercontent.com/31085013/230692898-1473586b-9363-444c-9c4a-11e5f66c68a0.png">

**Comment by xiongbb** [comment]
> 水平有限，想出了一个笨办法，在logOut方法中，最后加上**window.location.href = "/";** 让浏览器刷新一下，可以解决这个问题。

我是加了一个router.go(0);，也是强制刷新了一下，页面会闪一下，不优雅

**Comment by xiaoxian521** [comment]
参考 https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/permission/page/index.vue#L37&L39  修改mock数据需要重启服务  就那么难懂？ 单反会点前端都能理解 不再解释第二遍
