### ISSUE TITLE
initRouter不向下执行

### ISSUE THREAD

**Issue by ghoulhyk** [pure-admin/vue-pure-admin#513]
这段代码在别的地方是正常的，但是写在**mixNav.vue**中，**打包部署之后**，就会卡在initRouter不向下执行了。

![image](https://user-images.githubusercontent.com/20198413/231150435-3c118ef0-c2af-4ee9-a6b6-337d0778a932.png)

![image](https://user-images.githubusercontent.com/20198413/231151264-1026a431-4e8b-4f4d-896d-ee2b04226e19.png)

`
function onOrgChanged() {
  const loading = ElLoading.service({
    lock: true,
    text: "Loading",
    background: "rgba(0, 0, 0, 0.7)"
  });
  // loginUtils
  //   .changeSelectedOrg(val)
  Promise.resolve(1)
    .then(res => {
      console.info("xxx - 1");
      usePermissionStoreHook().clearAllCachePage();
      return initRouter();
    })
    .then(() => {
      console.info("xxx - 2");
      return router.push("/");
    })
    .catch(e => {
      console.error(3, e);
    })
    .finally(() => {
      console.info("xxx - 4");
      loading.close();
    });
  return;
}
`

**Comment by xiaoxian521** [comment]
可能你写法又问题
