### ISSUE TITLE
放到monorepo rush中，rush update后缺少依赖启动失败

### ISSUE THREAD

**Issue by zhangchengkk** [pure-admin/vue-pure-admin#518]
创建新的rush monorepo，rush update后启动失败。
`
error when starting dev server:
Error: modules: vue-demi package.json file does not exist
`
和直接pnpm install安装对比了一下，确实缺少了一些依赖。想请教下是什么原因？

**Comment by xiaoxian521** [comment]
安装`vue-demi`
`pnpm install vue-demi`
