### ISSUE TITLE
pureadmin-admin-table   表格的 序号列和 勾选列希望合二为一

### ISSUE THREAD

**Issue by kiwimg** [pure-admin/vue-pure-admin#520]
希望 pureadmin-admin-table 表格的  序号列和 勾选列希望合二为一

可以参照 airtable的效果，目前现代化表格大部分这样设计，这样可以减少列的占用空间，

**Comment by xiaoxian521** [comment]
pure-admin-table并没有限制你做什么 如果你希望这样仅仅通过对应配置就行

**Comment by kiwimg** [comment]
谢谢 没看到具体示例，你的意思已经支持了吗
