### ISSUE TITLE
`vscode` 插件 `Volar` 的 `1.4.0` 版本给平台带来的影响以及解决方案

### ISSUE THREAD

**Issue by xiaoxian521** [pure-admin/vue-pure-admin#523]
昨天`volar`升级到了`v1.4.0`版本对平台造成了下图的影响，很多组件的类型提示消失了，尤其是`el-`的组件，也有很多码友对`volar`官方反应了此问题，详见[language-tools/issues/2641](https://github.com/vuejs/language-tools/issues/2641) 估计这个问题很快会得到解决

![e57e09f9bba5cd517747536b0ff8e687](https://user-images.githubusercontent.com/44761321/233527748-37b0f0a5-8f27-4fb4-921c-cc39908398cb.jpeg)

这里先提供个解决办法就是将`volar`降级到`1.2.0`版本

<img width="812" alt="image" src="https://user-images.githubusercontent.com/44761321/233528172-77e2fd5b-30ba-427f-9d59-4e4e7a66d5af.png">

降级方法如下图

<img width="759" alt="image" src="https://user-images.githubusercontent.com/44761321/233544388-fc493a56-e186-4e5a-8ce7-9b66722b0fa4.png">

**Comment by zzh948498** [comment]
如何降级，在哪下载呢？

**Comment by zhuxiaoweb** [comment]
1.2.0同样报错：
![image](https://user-images.githubusercontent.com/32625924/233528726-bc5dff61-c3a7-4ed4-9ed8-21738d4ac719.png)

**Comment by miles66jhg** [comment]
我降到1.2.0可以了，没有报错，试试重启一下

**Comment by xiaoxian521** [comment]
降级后需要重新启动`vscode` 可看下图`volar v1.2.0`版本是没有问题的

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/44761321/233529059-cab51f72-3eb3-4c20-9289-c4bdddc55a67.png">

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/44761321/233529091-875a4be2-59c1-4ce6-ace7-3c46897d678a.png">

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/44761321/233529112-be7642ca-711d-43fd-aca1-013cc05d683b.png">

**Comment by 2011102394** [comment]
可怕的1.4版本

**Comment by mayoisuki** [comment]
> 如何降级，在哪下载呢？

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/1.2.0/vspackage
这个是1.2.0的下载链接

**Comment by 2011102394** [comment]
来信收到，谢谢

**Comment by StormerZSha** [comment]
降低到1.2.0以及更低版本问题都还存在

**Comment by xiaoxian521** [comment]
> 降低到1.2.0以及更低版本问题都还存在

此解决方案只针对`pure-admin`平台，别的项目未知

**Comment by zhuxiaoweb** [comment]
> 降级后需要重新启动`vscode` 可看下图`volar v1.2.0`版本是没有问题的
> 
@xiaoxian521 
没问题了

**Comment by warmthsea** [comment]
![image](https://user-images.githubusercontent.com/45450994/233530006-b6616c26-5c63-4b47-a71e-0332297b559f.png)
降到 1.2，volar 直接在这个项目启动失败了

**Comment by warmthsea** [comment]
> > ![image](https://user-images.githubusercontent.com/45450994/233530006-b6616c26-5c63-4b47-a71e-0332297b559f.png) 降到 1.2，volar 直接坏掉了
> 
> <img alt="image" width="348" src="https://user-images.githubusercontent.com/44761321/233530166-50c58043-14f3-401f-a8c3-d1656da31197.png">
> 
> 非`pure-admin`平台 自行处理哦 该`issues`只是针对`pure-admin`用户

好吧，谢谢，应该就是  volar / vite 的原因

**Comment by xiaoxian521** [comment]
> 

不会大部分项目将`volar`降到`1.2.0`版本都是没问题的，你可以选择先卸载`volar`再去重新安装`volar v1.2.0`，然后重启`vscode`

**Comment by StormerZSha** [comment]
> > 降低到1.2.0以及更低版本问题都还存在
> 
> 此解决方案只针对`pure-admin`平台，别的项目未知

我的问题，我把TypeScript Vue Plugin (Volar)降级了而不是Vue Language Features (Volar)，已经成功解决了

**Comment by warmthsea** [comment]
> 

我的项目没用

**Comment by warmthsea** [comment]
> > 
> 
> 我的项目没用

降到了 1.1 ，正常工作了！

![image](https://user-images.githubusercontent.com/45450994/233558878-612062e6-cfe9-4eaf-bfc7-c8822be02c22.png)

**Comment by xiaoxian521** [comment]
`volar` v1.4.2 已修复

**Comment by cdr7508** [comment]
> > 如何降级，在哪下载呢？
> 
> https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/1.2.0/vspackage 这个是1.2.0的下载链接

感谢，我的信创平台下了个0.9.0的版本，勉强用一下

**Comment by 2011102394** [comment]
来信收到，谢谢
