### ISSUE TITLE
如何配置路由为页面跳转路由，而不是#选项卡？

### ISSUE THREAD

**Issue by caimingyi484** [pure-admin/vue-pure-admin#524]
**Is your feature request related to a problem? Please describe.**
如何配置路由为页面跳转路由，而不是#选项卡？

**Describe the solution you'd like**
将https://yiming_chang.gitee.io/vue-pure-admin/#/permission/page/index 改为 https://yiming_chang.gitee.io/vue-pure-admin/permission/page/index ，没有#实现页面跳转，该如何配置？

**Comment by xiaoxian521** [comment]
看文档 这是基本的vue-router知识
