### ISSUE TITLE
混合导航下打开showLink:false页面并刷新后，左侧导航栏菜单显示空白

### ISSUE THREAD

**Issue by itliujia** [pure-admin/vue-pure-admin#525]
[![p9Ep3WV.png](https://s1.ax1x.com/2023/04/21/p9Ep3WV.png)](https://imgse.com/i/p9Ep3WV)

**Comment by xiaoxian521** [comment]
`showLink:false`隐藏菜单 就是不显示

**Comment by itliujia** [comment]
这个是详情页啊，那刷新的时候不能显示同级的菜单码

**Comment by north521** [comment]
> 这个是详情页啊，那刷新的时候不能显示同级的菜单码

请问，这个问题你解决了吗

**Comment by itliujia** [comment]
你好，我最近正在学习中，无法亲自回复你的邮件。我将尽快给你回复。
