### ISSUE TITLE
导航栏模式使用 混合模式 时，重新调用initRouter会卡住。

### ISSUE THREAD

**Issue by ghoulhyk** [pure-admin/vue-pure-admin#527]
导航栏模式使用 混合模式 时，重新调用initRouter会卡住。
在预览网站中可以复现，先调整为混合模式，再到页面权限页面里，切换角色。
![QQ截图20230424001601](https://user-images.githubusercontent.com/20198413/233851872-f03b6e05-2511-466f-bdf4-609621e1bc9a.jpg)

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/d305e6fb1fb5b2cf88766f87ab2e4376a495f715)
