### ISSUE TITLE
pure-table勾选项不居中显示

### ISSUE THREAD

**Issue by rbj0820** [pure-admin/vue-pure-admin#528]
精简版，测试发现，当pure-table设置showOverflowTooltip时，不居中显示
`const columns: TableColumnList = [
  {
    type: "selection",
    align: "center"
  },
  {
    label: "日期",
    prop: "date"
  },
  {
    label: "姓名",
    prop: "name"
  },
  {
    label: "地址",
    prop: "address"
  }
];
`
`<div>
    <pure-table
      border
      showOverflowTooltip
      ref="tableRef"
      :data="tableData"
      :columns="columns"
      @selection-change="handleSelectionChange"
    />
    <div style="margin-top: 20px">
      <el-button @click="toggleSelection([tableData[1], tableData[2]])">
        Toggle selection status of second and third rows
      </el-button>
      <el-button @click="toggleSelection()">Clear selection</el-button>
    </div>
  </div>`
![image](https://user-images.githubusercontent.com/20568714/234204287-9c32283b-8142-4eab-9b31-a0b8e960df2f.png)

**Comment by xiaoxian521** [comment]
看下element-plus的table
