### ISSUE TITLE
dark主题颜色修改

### ISSUE THREAD

**Issue by norlight** [pure-admin/vue-pure-admin#529]
dark.scss中修改了`--el-bg-color`和`app-main`的`background`，但顶部菜单鼠标悬浮时背景色、下拉菜单背景色、登录页的背景色没发生变化。需要单独修改或配置哪里吗？

<img width="235" alt="Snipaste_2023-04-26_02-10-19" src="https://user-images.githubusercontent.com/14835448/234367156-98d5d9fe-59ea-4d20-a3cd-e06dca8d4d72.png">

**Comment by xiaoxian521** [comment]
具体看代码哈
