### ISSUE TITLE
KeepAlive使用之后页面点击标签会显示空白页面不会渲染，系统异常但是控制台并没有什么错误

### ISSUE THREAD

**Issue by xdz1** [pure-admin/vue-pure-admin#531]
只有将appMain.vue中的Keep-alive改为div即可运行但是这样就失去了Keepalive

**Comment by xiaoxian521** [comment]
不管是用与否 页面最外层需要包个标签 比如 `div` [点击查看具体](https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vue3-%E5%8D%95%E6%96%87%E4%BB%B6%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%E6%A0%B9%E6%A0%87%E7%AD%BE-%E4%BD%86%E6%98%AF%E5%B9%B3%E5%8F%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E8%BF%99%E4%B9%88%E7%94%A8%E5%91%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
