### ISSUE TITLE
精简版 build:staging 使用CDN报错

### ISSUE THREAD

**Issue by libra1010** [pure-admin/vue-pure-admin#532]
精简版 build:staging 使用CDN报错

Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

查看引用JS，均使用CDN引用并下载成功
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/9667153/234889044-3aad03a3-b560-4a5f-9fca-a741697084d2.png">

目前找不到是哪个模块导致的 cdn错误， 网上都指向vue-demi
经过查看是下载成功的

**Comment by libra1010** [comment]
@xiaoxian521 我确认了bug
因为我使用autoimport 然后配置了
  AutoImport({
      resolvers: [ElementPlusResolver()],
      imports: ['vue']   
    })
当我去掉 下面内容时可以正常运行
 imports: ['vue']

**Comment by xiaoxian521** [comment]
autoimport 并不是平台推荐 自行解决

**Comment by PeiTianHuang** [comment]
> [@xiaoxian521](https://github.com/xiaoxian521) 我确认了bug 因为我使用autoimport 然后配置了 AutoImport({ resolvers: [ElementPlusResolver()], imports: ['vue'] }) 当我去掉 下面内容时可以正常运行 imports: ['vue']

我也遇到了同样的问题，请问你最终是如何解决的呢
