### ISSUE TITLE
macbook Safari 浏览器访问demo网站报错

### ISSUE THREAD

**Issue by wangwei8888** [pure-admin/vue-pure-admin#533]
<img width="903" alt="屏幕快照 2023-04-28 下午4 27 11" src="https://user-images.githubusercontent.com/36029972/235099339-2d5c42dd-7a63-43eb-99d0-d00cec79f3e5.png">
如图所示,macbook safari  打开
https://yiming_chang.gitee.io/vue-pure-admin
报错 ,chrome 访问正常

**Comment by xiaoxian521** [comment]
请参考这里 https://yiming_chang.gitee.io/pure-admin-doc/pages/introduction/#%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81 平台也不推荐`safari浏览器`

![Uploading image.png…]()
