### ISSUE TITLE
`params` 路由传参模式下，面包屑无法找到父级路径

### ISSUE THREAD

**Issue by xiaoxian521** [pure-admin/vue-pure-admin#536]
如下视频，`query` 模式下可以找到父级并显示出标签页操作，而 `params` 模式下不行

https://user-images.githubusercontent.com/44761321/236165648-00205910-7644-4062-9197-f88f37b89909.mp4

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/d49b23e8f961d0956d10adf3cc6ab44424341ca2)

**Comment by hogking** [comment]
我使用的的是pure-admin-thin开发，按照fixed内容更改后可正常展示父级路径了。但点击tab栏（我这里叫做详情信息）两次后，会多出404页面。请教是否有遇到该问题？
<img width="444" alt="image" src="https://user-images.githubusercontent.com/38121483/236905990-a032e4c9-27d8-42b4-9bc1-c54b39029fad.png">

**Comment by xiaoxian521** [comment]
> 我使用的的是pure-admin-thin开发，按照fixed内容更改后可正常展示父级路径了。但点击tab栏（我这里叫做详情信息）两次后，会多出404页面。请教是否有遇到该问题？ <img alt="image" width="444" src="https://user-images.githubusercontent.com/38121483/236905990-a032e4c9-27d8-42b4-9bc1-c54b39029fad.png">

请用完整版测试 精简版暂时没同步 一个`pr`并不代表解决一个问题，可能有些问题在前面的`pr`处理了一半
