### ISSUE TITLE
项目中引用Vditor想实现Markdown 编辑器，初始化加载不出来

### ISSUE THREAD

**Issue by HaiDongQingYu** [pure-admin/vue-pure-admin#540]
项目中引用Vditor想实现Markdown 编辑器，初始化加载不出来，是什么情况
使用Vditor的示例代码
![image](https://user-images.githubusercontent.com/66376469/236749231-25ad17fa-2e92-4cef-a712-1fd9e2e6124f.png)

在vue3模板下正常显示

**Comment by xiaoxian521** [comment]
业务代码自行研究

**Comment by 88act** [comment]
确实存在这个问题  Vditor 加载不出来    https://github.com/Vanessa219/vditor

**Comment by code-ssd** [comment]
`index.html` 删除 `window.process = {};`

**Comment by AKAZhiyu** [comment]
works for me

**Comment by Moonia-Cherry** [comment]
> `index.html` 删除 `window.process = {};`

It works!
我原封不动地将vue-pure-admin的markdown模块拷贝到pure-admin-thin，补充好依赖后，vditor就是不显示，看到这条回复，把这一行注释了，马上就显示出来了；回头寻找vue-pure-admin的index.html，发现没有window.process = {};
