### ISSUE TITLE
登录后点击菜单跳转至404

### ISSUE THREAD

**Issue by hogking** [pure-admin/vue-pure-admin#541]
偶现：登录后拉取动态路由成功，菜单及相关二级菜单正常显示，点击后会显示404异常页面（控制台无任何报错）。但一般都是刷新之后，再点击菜单就能够进入到对应路由页面了。

**Comment by xiaoxian521** [comment]
从未出现过的情况 如果你确认是bug并且必现后提供复现仓库 才会得到解决

**Comment by csj96** [comment]
我也出现这个问题，就是偶尔会出现，登录成功后点击都会直接跳到404界面，会话中存储的路由是正确的，但是跳转的时候打印处理的路由却是缺失的，所以他就跳到了404界面。刷新网页后就正常了，找不到问题在哪。还有就是这个问题只是偶尔出现，大部分情况都是正常的。 @xiaoxian521 希望帮我解决下，如果不知道问题是啥，那我想知道跳转的时候读取的是哪里的路由

**Comment by zzx131** [comment]
> 我也出现这个问题，就是偶尔会出现，登录成功后点击都会直接跳到404界面，会话中存储的路由是正确的，但是跳转的时候打印处理的路由却是缺失的，所以他就跳到了404界面。刷新网页后就正常了，找不到问题在哪。还有就是这个问题只是偶尔出现，大部分情况都是正常的。 @xiaoxian521 希望帮我解决下，如果不知道问题是啥，那我想知道跳转的时候读取的是哪里的路由

这个问题我也出现过，不过大部分出现在修改代码以后，如果不对代码修改，没有这个问题，我怀疑是vite加载的时候把路由丢失了

**Comment by pot-code** [comment]
同样出现过
