### ISSUE TITLE
根据文档配置动态路由二级菜单出现无法点选和打开的情况

### ISSUE THREAD

**Issue by INSIinc** [pure-admin/vue-pure-admin#547]
**Describe the bug**
动态路由配置的二级菜单出现无法点选和打开的情况

**To Reproduce**
后端返回动态路由
```json
{
    "id": "645f542bd4e8995122734538",
    "path": "/userManage",
    "meta": {
        "title": "用户管理",
        "icon": "add",
        "keepAlive": false,
    },
    "children": [
        {
            "path": "/userManage/index",
            "name": "UserList",
            "meta": {
                "title": "用户列表",
                "keepAlive": true,
                "roles": [
                    "admin"
                ],
            },
        },
        {
            "path": "/userManage/addUser",
            "name": "AddUser",
            "meta": {
                "title": "添加用户",
                "keepAlive": true,
                "roles": [
                    "admin"
                ],
            },
        }
    ]
}
```
前端报错
<img width="349" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/42080694/9bfe072e-6dc0-4e53-bcb1-96d95ca3db92">

修改源代码
```typescript
function hasOneShowingChild(
  children: childrenType[] = [],
  parent: childrenType
) {
  if (children === null) return false;
....
```
错误消失

但是出现另外的问题
<img width="267" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/42080694/af880fe7-33d8-4248-9fa4-71d40bbb36c1">
如图所示，二级菜单出现不该出现的箭头，并且无法点选和打开

**Expected behavior**
二级菜单出现并可以正常打开

**Comment by xiaoxian521** [comment]
提供复现仓库

**Comment by INSIinc** [comment]
> 提供复现仓库

https://github.com/INSIinc/zbxtfront

**Comment by xiaoxian521** [comment]
> > 提供复现仓库
> 
> https://github.com/INSIinc/zbxtfront

具体代码位置 最好用最新版本

**Comment by INSIinc** [comment]
> > > 提供复现仓库
> > 
> > 
> > https://github.com/INSIinc/zbxtfront
> 
> 具体代码位置 最好用最新版本

sidebarItem.vue  155行，会报错children是null，按照文档配置的二级菜单，第二级确实是不存在children的。

**Comment by xiaoxian521** [comment]
提供配置路由位置

**Comment by INSIinc** [comment]
> 在确保你是最新代码的同时提供配置路由位置，不需要关心报错 如果按照这个要求还报错 我会解决

报错之后网页404了

**Comment by INSIinc** [comment]
> 在确保你是最新代码的同时提供配置路由位置，不需要关心报错 如果按照这个要求还报错 我会解决

https://github.com/INSIinc/vue-pure-admin  我已经合并了最新代码
