### ISSUE TITLE
利用docker环境，启动后无法访问，一直卡在加载界面

### ISSUE THREAD

**Issue by CymaticsCC** [pure-admin/vue-pure-admin#548]
我使用node:18.16.0版本的镜像，然后用了精简版看看效果，pnpm i安装依赖之后， 执行dev，无论是使用safari或者是chrome都是卡在了加载界面，

![image](https://github.com/pure-admin/vue-pure-admin/assets/18202241/b125406b-4633-4d3e-a834-8e73b6046bfe)

我看b站视频说需要加载一会，但是我加载了很久依然是这个情况，

pure-admin版本是4.1.0，请问这种情况怎么解决？

**Comment by CymaticsCC** [comment]
昨天的时候也尝试过直接使用完成版，也是这个问题，都是卡在了加载界面

**Comment by xiaoxian521** [comment]
卡住了看控制台啊 截图报错信息

**Comment by CymaticsCC** [comment]
控制台看了，各种资源也都请求了，只有这一个报错

![image](https://github.com/pure-admin/vue-pure-admin/assets/18202241/17d6b992-e7d9-49ca-a29f-566ac0be2c71)

**Comment by xiaoxian521** [comment]
那就非打包问题 把`node`版本降低到`v16.20.0`试试

**Comment by CymaticsCC** [comment]
反馈一下，我之前是git网页下载了源码然后部署的（网络限制），就是进不去；这次想办法加了代理，在机器git clone下载的源码，然后就好使了，node还是18.16.0，感谢您的帮助

> 那就非打包问题 把`node`版本降低到`v16.20.0`试试

**Comment by inmine** [comment]
我也遇到这样的问题, 但是我是pnpm dev访问可以, 打包到服务器上停留在菊花页面, 请问知道这个怎么处理吗
<img width="1438" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/16496336/6f4c955d-92de-4120-8ef1-043a7e5f9901">
