### ISSUE TITLE
[bug]IconSelect双向绑定时icon预览和名字不一致

### ISSUE THREAD

**Issue by tongwenfei** [pure-admin/vue-pure-admin#552]
### 问题描述
IconSelect双向绑定时icon预览和名字不一致
### 复现
`const icon = ref("ep:edit");`
`<IconSelect v-model="icon" />`
<img width="297" alt="1684159236677" src="https://github.com/pure-admin/vue-pure-admin/assets/9261213/680b4398-d730-4f34-a31c-fdf0a62d9760">

**Comment by mynetfan** [comment]
只需要在图标选择器中的watch添加` { immediate: true }`选项就能正确初始化预览图标
