### ISSUE TITLE
pure-admin-utils 工具类中的getQueryMap方法优化建议

### ISSUE THREAD

**Issue by rainxw** [pure-admin/vue-pure-admin#555]
**1.问题的原因.**
getQueryMap中，调用了一个正则表达式对url进行验证，调用的正则表达式如下：
function bt(t) {
    const n =
      "^((https|http|ftp|rtsp|mms)?://)(([0-9]{1,3}.){3}[0-9]{1,3}|([0-9a-z_!~*'()-]+.)*([0-9a-z][0-9a-z-]{0,61})?[0-9a-z].[a-z]{2,6})(:[0-9]{1,4})?((/?)|(/[0-9a-z_!~*'().;?:@&=+$,%#-]+)+/?)$";
    return new RegExp(n, "ig").test(t);
  }
  
匹配端口的时候这里使用的是[0-9]{1,4}，匹配1到4位的端口号
 但是在实际场合下，端口号可能是5位，比如端口号为：38888
最终导致，匹配失败。

在 Linux 中，端口号的范围是从 0 到 65535，所以可以做如下的修改：
[0-9]{1,4}   ---->  [0-9]{1,5}

**Comment by mynetfan** [comment]
> ```
> /**
>  * @description `url` 链接正则
>  */
> export function isUrl(value: string): boolean {
>   const regex =
>     "^((https|http|ftp|rtsp|mms)?://)" +
>     "(([0-9]{1,3}.){3}[0-9]{1,3}" + // IP形式的URL- 199.194.52.184
>     "|" + // 允许IP和DOMAIN（域名）
>     "([0-9a-z_!~*'()-]+.)*" + // 域名- www.
>     "([0-9a-z][0-9a-z-]{0,61})?[0-9a-z]." + // 二级域名
>     "[a-z]{2,6})" + // first level domain- .com or .museum
>     "(:[0-9]{1,4})?" + // 端口- :80
>     "((/?)|" + // a slash isn't required if there is no file name
>     "(/[0-9a-z_!~*'().;?:@&=+$,%#-]+)+/?)$";
>   const reg = new RegExp(regex, "ig");
>   return reg.test(value);
> }
> ```
> 
> ```
> /**
>  * @description 提取浏览器 `url` 中所有参数
>  * @param url 超链接地址
>  * @returns 所有参数组成的对象
>  */
> export function getQueryMap(url: string): object {
>   if (!isUrl(url)) {
>     console.error(`${url}不符合超链接规范`);
>     return {};
>   }
>   const index = url.indexOf("?");
>   const params = url.slice(index + 1);
>   const arr = params.split("&");
>   const obj: any = {};
>   for (let i = 0; i < arr.length; i++) {
>     obj[arr[i].split("=")[0]] = arr[i].split("=")[1];
>   }
>   return obj;
> }
> ```
> 
> 代码提供给你 可自行调试


```isUrl("http://192.168.1.1:56250")```  →  ```false```
```isUrl("http://192.168.1.1:5625")```  →  ```true```

实际上端口号范围确实在0到65535之间，因此五位数的端口号是可能的。但这个正则中只匹配了1到4位的数字，没有兼容五位数字
