### ISSUE TITLE
能否实现table铺满内容区域，然后table高度随浏览器高度变化而变化？

### ISSUE THREAD

**Issue by jasonHG** [pure-admin/vue-pure-admin#561]
![6](https://github.com/pure-admin/vue-pure-admin/assets/29171233/b6e8288a-9ede-423a-88ed-a579133d8933)

**Comment by xiaoxian521** [comment]
关于这个问题 你应该去看 `el-table` 是否支持

**Comment by jasonHG** [comment]
行吧。。我自己看能不能调整样式实现吧。

**Comment by tanytree** [comment]
> 



> 行吧。。我自己看能不能调整样式实现吧。

可以的，用样式flex 实现

**Comment by xiaoxian521** [comment]
目前已支持，参考 https://github.com/pure-admin/vue-pure-admin/commit/39833ce917dc8eea27fe2a097e1ad08dc9fffa64
更多参考 https://github.com/pure-admin/pure-admin-table/releases/tag/v2.3.0
