### ISSUE TITLE
左侧菜单栏点击黑色遮罩关闭显示的问题

### ISSUE THREAD

**Issue by wbsllm** [pure-admin/vue-pure-admin#562]
出现情况:  打开浏览器调试,将尺寸拉到显示 【折叠菜单按钮】的尺寸(大概在768以下),然后点击 折叠菜单按钮，显示菜单后,点击黑色遮罩关闭显示, 然后将尺寸恢复, 会发现在左侧菜单折叠了;
建议:  当菜单处于左侧菜单时,折叠菜单按钮一直显示(不管页面尺寸大还是小), 按钮点击效果:  正常页面时点击效果为: 折叠左侧菜单;页面尺寸很小的时候点击显示左侧菜单(目前效果)

**Comment by xiaoxian521** [comment]
自己喜欢什么风格自行调整 这个从设计最初没人有你这种想法

**Comment by wbsllm** [comment]
不是风格问题,出现情况,不太对劲吧

**Comment by wbsllm** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/72794088/e4efc218-e279-47bc-8f55-df0c5bef2f58)
左侧菜单不显示了,非要点按钮才显示

**Comment by xiaoxian521** [comment]
> ![image](https://user-images.githubusercontent.com/72794088/239814218-e4efc218-e279-47bc-8f55-df0c5bef2f58.png) 左侧菜单不显示了,非要点按钮才显示

无法复现你这种问题 自己同步问题？
如果你可以复现 先用完整版复现 提供复现视频 
确定问题我会解决

**Comment by wbsllm** [comment]
精简版,好像没有这个问题

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/1c89464d1a5856a037e0b5a4584c64917a092140)
