### ISSUE TITLE
左侧菜单栏的收起问题

### ISSUE THREAD

**Issue by 1847123733** [pure-admin/vue-pure-admin#563]
https://github.com/pure-admin/vue-pure-admin/assets/63571610/b9b81e37-5a83-4f45-9c52-c32df4d4a209

**Comment by xiaoxian521** [comment]
多看文档

https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vertical-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95%E5%8D%A1%E9%A1%BF-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3-%E8%8F%9C%E5%8D%95%E5%88%87%E6%8D%A2%E5%8D%A1%E9%A1%BF
