### ISSUE TITLE
pure-admin-utils 工具类中的getQueryMap方法bug，以及优化建议

### ISSUE THREAD

**Issue by rainxw** [pure-admin/vue-pure-admin#565]
![image](https://github.com/pure-admin/vue-pure-admin/assets/35726776/66a509c2-dd3b-463e-9c6f-9618f58a9965)

![image](https://github.com/pure-admin/vue-pure-admin/assets/35726776/0e6a0802-4ef2-41bb-976a-6596bd61b76a)

**Comment by xiaoxian521** [comment]
升级到 `1.8.10` 版本即可
