### ISSUE TITLE
路由重定向造成标签页出现重复内容

### ISSUE THREAD

**Issue by beibeiaiwuhao** [pure-admin/vue-pure-admin#567]
当访问路由： 
      https://yiming_chang.gitee.io/vue-pure-admin/#/tabs/index
没有问题，可以正常显示

但是当访问 
 https://yiming_chang.gitee.io/vue-pure-admin/#/tabs 
的时候，路由显示  
https://yiming_chang.gitee.io/vue-pure-admin/#/tabs/index
但是 tag不能正常显示，会出现一个同名的tag

![截屏2023-05-23 下午2 44 53](https://github.com/pure-admin/vue-pure-admin/assets/15605907/dfeb5569-fc01-40c2-91ed-28373de9143f)

**Comment by beibeiaiwuhao** [comment]
在群里面问了，开启标签持久化可规避这问题，但是如果不开启怎么规避呢

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/a4a691de3e55a2d7634d0f231d1b333da5c09ffd)

**Comment by beibeiaiwuhao** [comment]
👍👍👍，感谢作者积极响应
