### ISSUE TITLE
登出未清空Home组件信息导致下次登录按钮权限未更新

### ISSUE THREAD

**Issue by hogking** [pure-admin/vue-pure-admin#571]
您好，使用纯净版遇到下方Issues提到问题：
https://github.com/pure-admin/vue-pure-admin/issues/509，但我并非使用mock数据。

问题：登录换个不同权限的账号，进入某动态菜单后，getAuths()打印出来的还是上一次身份的按钮权限，得刷新。不过不同过的是我不是mock的数据，是服务器返回的动态路由数据。我看logout()里也有调resetRouter()，现在也是通过router.go(0)解决。

可能原因：
我调试发现登出时会调用resetRouter()，但resetRouter()并没有清空Home组件信息（因为Home非动态路由？）。切换身份登录时，router仍保留登出时未清空的"Home"的meta数据，导致新拉取的动态路由信息没有起到作用（handleAsyncRoutes()在遇到Home时就先遍历其未清空的children meta信息了）。

请多多指教。

**Comment by xiaoxian521** [comment]
自行参考权限页面
