### ISSUE TITLE
页面刷新侧边栏logo消失

### ISSUE THREAD

**Issue by wbsllm** [pure-admin/vue-pure-admin#572]
![image](https://github.com/pure-admin/vue-pure-admin/assets/72794088/54c2e1db-6cb4-49d4-9d8e-0f29cd013632)
如题: 页面按F5刷新一两次,左侧logo就消失了,设置中的logo显示状态是开启的

**Comment by wbsllm** [comment]
精简版,没有这个问题

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/46db63e914cf5166806113f1ad2aae79436d6349)
