### ISSUE TITLE
平台相关文档访问注意点！！！需注意

### ISSUE THREAD

**Issue by xiaoxian521** [pure-admin/vue-pure-admin#574]
最近平台文档均移除了`pwa`，这可能造成您访问平台相关文档时可能还停留在旧内容上
建议您强制刷新平台相关文档地址或者直接清除浏览器缓存，可保证您访问平台相关文档始终是最新内容！！！
如下面两个文档

[pure-admin-doc](https://yiming_chang.gitee.io/pure-admin-doc/)

[pure-admin-utils](https://pure-admin-utils.netlify.app/)

**Comment by zzx131** [comment]
收到
