### ISSUE TITLE
为啥表格是空白的

### ISSUE THREAD

**Issue by fengbt** [pure-admin/vue-pure-admin#576]
![image](https://github.com/pure-admin/vue-pure-admin/assets/74911146/9d4b3fa5-c6af-4413-8e96-c9d80b2dc239)
基本是复制过来改了一些文字，也没有啥报错，想知道怎么解决

**Comment by xiaoxian521** [comment]
非bug自己解决

**Comment by fengbt** [comment]
> 非bug自己解决

谢谢

**Comment by gaohc001** [comment]
main.ts最下面，    app.use(Table)上

**Comment by fengbt** [comment]
> main.ts最下面， app.use(Table)上

谢谢，我已经发现了，我以为已经引入了2333
