### ISSUE TITLE
pure-table 设置固定高度后上下滑动表的标题能固定一下吗？

### ISSUE THREAD

**Issue by gaohc001** [pure-admin/vue-pure-admin#577]
pure-table 设置固定高度后上下滑动表的标题能固定一下吗？

**Expected behavior**
[http://www.itmei.cn/1.png](url)

**Screenshots**

**Desktop (please complete the following information):**
win10X64,edge最新版

**Comment by xiaoxian521** [comment]
额 肯定可以啊 demo很多都是固定的 自行参考代码

**Comment by gaohc001** [comment]
<PureTableBar title="用户管理" :columns="columns" @refresh="onSearch">用这个包裹起来固定标题就不起作用了

**Comment by gaohc001** [comment]
自己改了，pnpm install后，全局搜索.el-table thead{color:var(--el-table-header-text-color);font-weight:500后改成.el-table thead{color:var(--el-table-header-text-color);font-weight:500;position:sticky;top: 0;z-index: 10}，就能固定表头了
