### ISSUE TITLE
请问使用pure-table的多选功能，遇到分页时多选值消失怎么解决？

### ISSUE THREAD

**Issue by GitHub1d** [pure-admin/vue-pure-admin#578]
![image](https://github.com/pure-admin/vue-pure-admin/assets/96401368/84e20135-759f-40f5-8132-9cd4cfe5a078)
![image](https://github.com/pure-admin/vue-pure-admin/assets/96401368/88587c9e-fcdd-40b6-b540-0a4eed055b57)

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/pure-table/high/page/columns.tsx#L18
