### ISSUE TITLE
国际化切换到英文模式刷新会回到中文模式

### ISSUE THREAD

**Issue by LengAoCold** [pure-admin/vue-pure-admin#581]
完整版线上有试，精简版本地有试。useLayout里面的initStorage 我console不会打印，在initStorage外面打印就ok，切换是OK了，我看缓存的也ok，就是好像是没有给用上useI18n。
第一次提Issues 不知道这样描述清晰不清晰。

**Comment by xiaoxian521** [comment]
很快会修复

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/315f78a825c0e051a22b5f91690f5a66c13e0116)

**Comment by LengAoCold** [comment]
大佬强,麻烦同意一下微信好友拉一下微信群..我看qq群最后一个群解散了   今天下午有加您
