### ISSUE TITLE
函数式弹窗示例页面代码存在的问题

### ISSUE THREAD

**Issue by ChasonZheng** [pure-admin/vue-pure-admin#583]
https://github.com/pure-admin/vue-pure-admin/blob/88a44f29d09a70b72789c45213097ff9e8731ca0/src/views/components/dialog/form.vue#L21

根据官方文档中[响应式基础](https://cn.vuejs.org/guide/essentials/reactivity-fundamentals.html)的说明:
1. 和响应式对象的属性类似，ref 的 .value 属性也是响应式的。**同时，当值为对象类型时，会用 reactive() 自动转换它的 .value。**
2. 为保证访问代理的一致性，对同一个原始对象调用 reactive() 会总是返回同样的代理对象，**而对一个已存在的代理对象调用 reactive() 会返回其本身**

可知，newFormInline 即为 props.formInline 本身。因此，对 newFormInline 的修改实际上就是对 props.formInline 的修改。未实现该行代码上面注释中，要求对 props 只读的效果。

**Comment by xiaoxian521** [comment]
多学学vue

**Comment by xiaoxian521** [comment]
注释写的明明白白 https://github.com/pure-admin/vue-pure-admin/blob/88a44f29d09a70b72789c45213097ff9e8731ca0/src/views/components/dialog/form.vue#L19
建议从vue基础开始学起

**Comment by ChasonZheng** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/33928208/2f9a770e-bdb0-4124-87bb-0e8b37d3e4cb)



> 注释写的明明白白
> 
> https://github.com/pure-admin/vue-pure-admin/blob/88a44f29d09a70b72789c45213097ff9e8731ca0/src/views/components/dialog/form.vue#L19
> 
> 
> 建议从vue基础开始学起

**Comment by xiaoxian521** [comment]
reactive和ref我倒是没注意 不过主要用于是消除warn的警告 这两个用法都能消除 我认为没啥影响 实际业务对你们有影响？

**Comment by ChasonZheng** [comment]
没影响，只是不好理解。代码与注释不符

**Comment by xiaoxian521** [comment]
> 没影响，只是不好理解。代码与注释不符

欢迎pr
