### ISSUE TITLE
下载精简版国际化，预发布打包和正式环境打包，点击index.html 不能预览，控制台报错。

### ISSUE THREAD

**Issue by yunyingchen** [pure-admin/vue-pure-admin#584]
index.html:1 Access to script at 'file:///E:/static/js/index-b88a1041.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
index-b88a1041.js:1     Failed to load resource: net::ERR_FAILED
index-6717f3c0.css:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
layout-theme-default.css:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
/E:/favicon.ico:1

**Comment by xiaoxian521** [comment]
用 `pnpm preview` 去打开一个服务 直接打开 `index.html` 肯定不行啊

**Comment by yunyingchen** [comment]
pnpm preview:build 是可以的，怎么部署到生产环境呢？
