### ISSUE TITLE
大佬，vue新手想问下不能在某个组件内引入自己的其他组件吗

### ISSUE THREAD

**Issue by 2212243743** [pure-admin/vue-pure-admin#585]
在views下创建了test目录写了两个文件
![image](https://github.com/pure-admin/vue-pure-admin/assets/29400078/1bcfb750-194b-4fa8-9068-a95d89bc90dc)
router/modules下写了test.ts
![image](https://github.com/pure-admin/vue-pure-admin/assets/29400078/1f88f5db-7828-42ba-b866-67a4917b0373)
但是会出现下面这种情况，从别的页面跳转到我的页面时没问题的，但是进了这个页面后进别的页面就都是空白的了，这是为啥
https://github.com/pure-admin/vue-pure-admin/assets/29400078/1815ec8a-f245-4de8-b634-2da606072795

**Comment by xiaoxian521** [comment]
<img width="371" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/2e2a034d-7074-48cf-938e-cc51d1af8662">
最外层用`div`包裹，具体看 https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vue3-%E5%8D%95%E6%96%87%E4%BB%B6%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%E6%A0%B9%E6%A0%87%E7%AD%BE-%E4%BD%86%E6%98%AF%E5%B9%B3%E5%8F%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E8%BF%99%E4%B9%88%E7%94%A8%E5%91%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

**Comment by 2212243743** [comment]
解决了，感谢大佬
