### ISSUE TITLE
咨询按钮权限的问题，谢谢

### ISSUE THREAD

**Issue by llllihtyihcy** [pure-admin/vue-pure-admin#588]
咨询大佬一个问题，同一个组件中的按钮权限能否按照role单独定义，比如下图，举个例子，我想定义common只可以操作“btn_add", admin可以操作全部按钮，怎么定义这个路由？
`const permissionRouter = {
  path: "/permission",
  meta: {
    title: "menus.permission",
    icon: "lollipop",
    rank: 10
  },
  children: [
    {
      path: "/permission/page/index",
      name: "PermissionPage",
      meta: {
        title: "menus.permissionPage",
        roles: ["admin", "common"]
      }
    },
    {
      path: "/permission/button/index",
      name: "PermissionButton",
      meta: {
        title: "menus.permissionButton",
        roles: ["admin", "common"],
        auths: ["btn_add", "btn_edit", "btn_delete"]
      }
    }
  ]
};`

![image](https://github.com/pure-admin/vue-pure-admin/assets/30112166/1dda14a8-45f6-4262-9c69-f729ae717800)

**Comment by xiaoxian521** [comment]
看文档
