### ISSUE TITLE
精简版同步完整版效率提升！！！用户同步对比更简单！！！

### ISSUE THREAD

**Issue by xiaoxian521** [pure-admin/vue-pure-admin#590]
从 `vue-pure-admin v4.3.0` 版本后，精简版 [pure-admin-thin](https://github.com/pure-admin/pure-admin-thin) 会开启更频繁的同步模式。
之前，精简版的同步都是待完整版发版后，这可能耗时半个月或者更长，用户等待时间过长，而且发版后修改的代码可能有点多，用户同步对比也麻烦。
现在，比如完整版提了两个 `commit` 都是对主体功能有影响的，平台会及时同步到精简版，用户可以及时更新，而且改动不会大，同步对比更简单！

[精简版是干啥的?](https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#%E7%B2%BE%E7%AE%80%E7%89%88%E6%98%AF%E5%B9%B2%E5%95%A5%E7%9A%84)

此公告暂不支持评论

**Comment by zzx131** [comment]
强

**Comment by wbsllm** [comment]
QQ群怎么解散了
