### ISSUE TITLE
添加了多选列之后PureTableBar，列排序出现问题

### ISSUE THREAD

**Issue by zzx131** [pure-admin/vue-pure-admin#591]
![image](https://github.com/pure-admin/vue-pure-admin/assets/22722085/51cf7d53-b174-4878-9d92-a2c5ead964b7)
如图所示

**Comment by xiaoxian521** [comment]
序号不允许拖动 用`fixed: 'left'` 固定住

**Comment by zzx131** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/22722085/918cdf30-7804-47d0-9780-8769a077ab57)
![image](https://github.com/pure-admin/vue-pure-admin/assets/22722085/70a816e3-f14f-4a88-ba81-a15302c3d547)
我下载的最新官方平台代码，只是加了多选列，然后拖动几次后，排序就回有问题，但是去掉多选列没有问题，这里的序号列已经固定了

**Comment by xiaoxian521** [comment]
```
 {
     label: "勾选列",  // 如果需要表格多选，此处label必须设置
    type: "selection",
    width: 55,
    align: "left",
    fixed: "left"
 },
```

**Comment by zzx131** [comment]
> {
>     label: "勾选列",  // 如果需要表格多选，此处label必须设置
>     type: "selection",
>     width: 55,
>     align: "left",
>     fixed: "left"
>  },

多谢了，强
