### ISSUE TITLE
内嵌 iframe 的页面如何添加监听事件

### ISSUE THREAD

**Issue by AlcoholTobaccoCode** [pure-admin/vue-pure-admin#593]
**Describe the bug**
不算是个 bug，就是想问下如果路由是用 frameSrc 配置的外部页面，求教要怎么给他加 postMessage 监听？
致谢❤️

**Expected behavior**

**Comment by xiaoxian521** [comment]
不好意思 这种东西随便百度就能出来 平台不是慈善家 只解决属于平台的bug

**Comment by xiaoxian521** [comment]
<img width="1287" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/9a49c5f8-08f6-4a67-bf2a-c04ff28213e0">

**Comment by xiaoxian521** [comment]
`gpt` 用起来

**Comment by AlcoholTobaccoCode** [comment]
这个我会，我的意思是咱们可以使用某个配置给这个内嵌的iframe添加监听的方法吗，
![image](https://github.com/pure-admin/vue-pure-admin/assets/49547938/956c7edb-acfa-4d71-9e23-070e8c39deab)

我现在是单独整了个 iframe 组件，然后在里面 `add/removeEventListener` ，然后在通过 emits 的方式暴露出去：
![image](https://github.com/pure-admin/vue-pure-admin/assets/49547938/6c0276c0-1593-4877-a711-59ed6c36d421)


想着如果有配置可以监听路由形式的 iframe 通信的话就不用这么麻烦了哈哈

**Comment by xiaoxian521** [comment]
应该可以 平台的`iframe`在这里处理 https://github.com/pure-admin/vue-pure-admin/blob/main/src/layout/frameView.vue
如果你有兴趣可以研究下 提个`pr`啥的，目前我没啥时间😂

**Comment by AlcoholTobaccoCode** [comment]
哈哈哈好的好的，辛苦啦❤️
我空下来的时候看看，谢谢作者大大
