### ISSUE TITLE
发现在打开开发者工具情况下，切换导航栏模式有明显卡顿，未打开开发者工具时不卡顿

### ISSUE THREAD

**Issue by fxzer** [pure-admin/vue-pure-admin#594]
**Describe the bug**
发现在打开开发者工具情况下，切换导航栏模式有明显卡顿，未打开开发者工具时不卡顿

**To Reproduce**
1. 打开 Chrome开发者工具
2. 切换导航栏模式
3. 发现有明显卡顿

**Expected behavior**
期待流畅
![1](https://github.com/pure-admin/vue-pure-admin/assets/68853957/47f8a878-9bb1-4e1b-ac8b-0f9450b3271a)

**Screenshots**

![2](https://github.com/pure-admin/vue-pure-admin/assets/68853957/8a4cd0d9-fb6e-4cd7-a6f0-399fb727d63e)

**Desktop (please complete the following information):**
 - OS：MacOS
 - Browser  ：Chrome 
 - Version ：113.0.5672.126（正式版本） (arm64)

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/track/#%E6%8E%92%E6%9F%A5%E6%96%B9%E6%B3%95
