### ISSUE TITLE
路由通过query或params传参，开启缓存后关闭标签页，之前打开的页面缓存依然存在

### ISSUE THREAD

**Issue by liushuanga1** [pure-admin/vue-pure-admin#595]
如下视频，打开详情信息1和2页面，对其路由设置了keepAlive缓存，关闭2页面时 再次打开2页面时，页面2还是缓存的

https://github.com/pure-admin/vue-pure-admin/assets/30852548/27334bdd-6f97-44d0-a238-d92d9da82a81

**Comment by xiaoxian521** [comment]
最新版吗

**Comment by xiaoxian521** [comment]
如果最新版还有这个问题 建议设置 `dynamicLevel` 为 `1`，这也是目前最好的解决办法了 或者你关闭的话最好都关闭掉 这里缓存就不存在了

**Comment by xiaoxian521** [comment]
因为路由传参 `name` 都是一样的 但是又不能过滤掉一样的 `name`，一旦过滤之前的缓存就不存在了 所以这里处理很麻烦 ，当然也很欢迎 `pr`

**Comment by liushuanga1** [comment]
是最新版的，我想这边的原因是，两个详情页name都是一样导致的，关闭时缓存数组还在
![c5dee16de5f7e8545aaa7041d5fc0a6](https://github.com/pure-admin/vue-pure-admin/assets/30852548/530f5043-8e2a-4362-bd82-5499f75fbab7)
![67c497ab94d5b52c7983e397cb11c28](https://github.com/pure-admin/vue-pure-admin/assets/30852548/537625fc-4fb8-4681-8a11-e22b6d0b1106)

**Comment by liushuanga1** [comment]
> 因为路由传参`name`都是一样的但是又不能过滤掉一样的`name`，一旦过滤之前的包裹就不存在了所以这里处理很麻烦，当然也很欢迎`pr`

要是给过滤掉了就会导致这个问题([#534](https://github.com/pure-admin/vue-pure-admin/issues/534#issue-1689785690))，暂时没有想到好的解决办法。

**Comment by xiaoxian521** [comment]
是的 所以 设置 dynamicLevel 为 1 是目前最好的解决办法了
