### ISSUE TITLE
不同的账户返回不同的路由菜单，菜单多的账号进入后，偶尔出现进入路由菜单消失

### ISSUE THREAD

**Issue by alusjie** [pure-admin/vue-pure-admin#602]
先用一个普通账号登录，只返回一条动态菜单，后面再用管理员账号登录，返回所有菜单，然后点击之前普通账号的路由没问题，点击其他的路由就变成菜单隐藏了，变成一个全的页面。刷新后又正常

**Comment by xiaoxian521** [comment]
请提供具体复现截图 这些文字并不能很好的让我复现

**Comment by xiaoxian521** [comment]
描述越详细 解决问题就越高效哈

**Comment by alusjie** [comment]
![Uploading 20230613185302.gif…]()

**Comment by alusjie** [comment]
![j3tAiW92zf](https://github.com/pure-admin/vue-pure-admin/assets/17893766/a07bf903-7d6b-47e0-82fd-b31203feb89b)

**Comment by alusjie** [comment]
一个账号先动态返回一条动态路由，另一个账号返回两条动态路由，其中一条动态路由包含 上一个账号的路由，然后点击另外一个不包含的理由，头部菜单个左侧菜单消失

**Comment by xiaoxian521** [comment]
贴出代码 或者直接建个仓库 我有空看

**Comment by smilecode11** [comment]
我这也出现了这样的情况

**Comment by smilecode11** [comment]
https://github.com/pure-admin/vue-pure-admin/assets/70701174/e4f6bbca-e908-4c53-8818-5dcc3759bba3

**Comment by Ftrybe** [comment]
一样。发生频率挺高

**Comment by xiaoxian521** [comment]
提供复现仓库代码 以免确定不是你们自己代码有误

**Comment by xiaoxian521** [comment]
此`issues`已被锁定，如果你们确定是`bug`并且可以提供复现仓库，请重新创建一个`issues`
