### ISSUE TITLE
打包后出现css资源找不到。

### ISSUE THREAD

**Issue by bwcgithub** [pure-admin/vue-pure-admin#603]
![微信图片_20230614163026](https://github.com/pure-admin/vue-pure-admin/assets/116618017/72cc467f-e5a1-49b3-ae1b-37e1f20ebeab)

### https: 后面少了一个“/”

**Comment by xiaoxian521** [comment]
版本 
配置？

**Comment by bwcgithub** [comment]
找不到打包后的css资源，抛出错误路径不对。配置assetsPublickPath:  './'可以解决不。

**Comment by xiaoxian521** [comment]
> 

你用的别的系统吧 平台没 `assetsPublickPath`

**Comment by bwcgithub** [comment]
大佬，嘻嘻，打扰一下。
![27f103b89c8fabe328bf0d34b85953c](https://github.com/pure-admin/vue-pure-admin/assets/116618017/a8e679f7-478b-4b59-8b0e-08a9ed72f5c3)
![84e21e4c1e4f77e7de317c7013ac679](https://github.com/pure-admin/vue-pure-admin/assets/116618017/712b9ce3-6a93-44d7-9874-f516bfb48526)
