### ISSUE TITLE
更新最新版V4.4.0版本后出现keepAlive缓存页面重复触发的问题。

### ISSUE THREAD

**Issue by wuhao-max** [pure-admin/vue-pure-admin#604]
### 描述问题 (Describe the problem)

我在精简版测试的，正式版不知道有没有这个问题。
在更新v4.4.0版本后，设置页面keepAlive为true，然后切换打开页面，第一次会触发组件内的onMounted函数，然后切换路由到其他页面，再切换回来的时候又触发了一次onMounted，然后再来回切就没事了，组件就缓存住了，简单的描述这个BUG就是：keepAlive: true的路由现在要切换两次页签，组件才会被缓存住。
我试了v4.3.0是没问题的，可能是改那个优化路由切换性能造成的。

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/39900695/09c3aa91-cf6a-45a7-b67c-1953fb29c0ac)
![image](https://github.com/pure-admin/vue-pure-admin/assets/39900695/eeb40d02-f1f9-4d45-9989-2d1682fb995a)
![image](https://github.com/pure-admin/vue-pure-admin/assets/39900695/57d61763-bf48-4737-91b6-b711f2ef821e)

### 操作系统和浏览器信息 (Operating system and browser information)

win10      pure-admin-thin     v4.4.0版本

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
开启缓存后用`activated`

https://cn.vuejs.org/guide/built-ins/keep-alive.html#lifecycle-of-cached-instance

**Comment by wuhao-max** [comment]
不是啊，大佬，我的意思是现在会重复触发onMounted钩子函数，比如说，我这个页面有个列表，在onMounted获取列表数据，我只希望第一次打开触发onMounted里面的调接口，页签不关闭的话再切换回来是不是就不会触发onMounted里面的调接口？以前的版本是正常的，但是现在v4.4.0却会重复触发两次才会被缓存上，实在不行我录个屏？

**Comment by xiaoxian521** [comment]
感谢反馈 抽空修复

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/2a2a3ee478ee96170cbc296993defee0b3093d4a)

**Comment by wyfweb1** [comment]
> 请问问题解决了吗？我也遇到了同样的问题

我也是遇到了同样的问题。
