### ISSUE TITLE
@pureadmin/utils内的isEqual方法问题

### ISSUE THREAD

**Issue by PeyFon** [pure-admin/vue-pure-admin#606]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/60815493/aa27a85f-cc2e-4560-b9e1-dfe9c7056e5c)
![image](https://github.com/pure-admin/vue-pure-admin/assets/60815493/1866a1f3-28e8-4d38-b03f-7f1c489d59c8)
这种proxy代理的对象 是必须要用户自己去处理吗，还是说这种事可以由isEqual方法内部去处理？

### 如何复现该问题 (How to reproduce the problem)

isEqual方法判断，如图

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
`isEqual` 不管这些东西，应该它不仅仅用于`vue`
在vue3中最好自己用`toRaw`先转

**Comment by PeyFon** [comment]
> `isEqual`不管这些东西，因为它不仅仅用于`vue` 在vue3中最好自己使用`toRaw`先转

![image](https://github.com/pure-admin/vue-pure-admin/assets/60815493/e1c567e8-573a-4645-8af4-193fbb089009)
![image](https://github.com/pure-admin/vue-pure-admin/assets/60815493/bb0572c1-3a06-4a86-bcd0-116758c3fdf4)
我试了下 好像判断不了一个空对象

**Comment by xiaoxian521** [comment]
你可以暂时把 {} 控对象放第一个参数 后面有时间我会修复发版

**Comment by PeyFon** [comment]
> 你可以暂时把 {} 控对象放第一个参数 后面有时间我会修复发版

好的好的

**Comment by xiaoxian521** [comment]
已优化 `@pureadmin/utils`升级最新版即可 感谢您的反馈 ❤️
