### ISSUE TITLE
elementui组件icon属性该怎么传

### ISSUE THREAD

**Issue by huashi-fengineer** [pure-admin/vue-pure-admin#609]
### 描述问题 (Describe the problem)

不使用@element-plus/icons-vue这个的话，组件自带icon属性的怎么传值，用@iconify-icons/ep好像无法显示

### 如何复现该问题 (How to reproduce the problem)

比如elementplus的Input组件支持prefix-icon属性
[步骤条组件](https://element-plus.gitee.io/zh-CN/component/steps.html#%E5%B8%A6%E5%9B%BE%E6%A0%87%E7%9A%84%E6%AD%A5%E9%AA%A4%E6%9D%A1)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/icon/
