### ISSUE TITLE
关于multiTags.ts文件内的handleTags方法

### ISSUE THREAD

**Issue by PeyFon** [pure-admin/vue-pure-admin#610]
### 描述问题 (Describe the problem)

handleTags方法的`case "push"`时
```
            // 判断tag是否已存在
            const tagHasExits = this.multiTags.some(tag => {
              return tag.path === tagPath;
            });

            // 判断tag中的query键值是否相等
            const tagQueryHasExits = this.multiTags.some(tag => {
              return isEqual(tag?.query, tagVal?.query);
            });

            // 判断tag中的params键值是否相等
            const tagParamsHasExits = this.multiTags.some(tag => {
              return isEqual(tag?.params, tagVal?.params);
            });

            if (tagHasExits && tagQueryHasExits && tagParamsHasExits) return;
```

tagHasExits、tagQueryHasExits、tagParamsHasExits  这三个值在某些情况下判断不准确

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/60815493/97ccb5e6-e23e-4076-b7b0-1def2aee0652)
说明：界面配置和权限 这两个按钮都使用query传参， 且**传参格式一致（这俩按钮都需要roleId和name），这是重点**。
如图所示，依次点击 1 2 3三个按钮。当我点击到3的时候就会出问题：由于之前已经点击过一次**界面配置按钮**， 所以`tagHasExits=true`，同时由于点击过**权限按钮**加上传参格式一致，会导致`tagQueryHasExits=true`，最后没有传入params所以`tagParamsHasExits=true`,最终导致无法push新的tag

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供具体复现仓库

**Comment by PeyFon** [comment]
> 提供具体复现仓库

抱歉，确实不方便提供，挺费事的。我这里手动把原先的代码改成了如下这样：
```
    const hasTag = toRaw(this.multiTags).some(tag => {
              return (
                tag.path === tagPath &&
                isEqual(tag?.query, tagVal?.query) &&
                isEqual(tag?.params, tagVal?.params)
              );
            });
            if (hasTag) return;
```
