### ISSUE TITLE
测试环境设置css样式报错。

### ISSUE THREAD

**Issue by bwcgithub** [pure-admin/vue-pure-admin#612]
![aaa](https://github.com/pure-admin/vue-pure-admin/assets/116618017/03f11cf9-aeaa-4881-a78a-4c0008918cb8)
![bbb](https://github.com/pure-admin/vue-pure-admin/assets/116618017/4653f14f-97b8-4305-a802-fe1065ee95ef)

**Comment by xiaoxian521** [comment]
按issues模版规范提交问题
