### ISSUE TITLE
测试环境设置样式css问题报错！

### ISSUE THREAD

**Issue by bwcgithub** [pure-admin/vue-pure-admin#613]
### 描述问题 (Describe the problem)

发布测试环境后显示打包文件报404。
![bbb](https://github.com/pure-admin/vue-pure-admin/assets/116618017/23965707-2986-4fb3-aee6-5c0f107f0326)
发现在设置的如下文件里面有报错信息相关名称。
![aaa](https://github.com/pure-admin/vue-pure-admin/assets/116618017/80d8936d-e04c-43ac-867b-7658b1436832)
本地打包后有相关文件
![ccc](https://github.com/pure-admin/vue-pure-admin/assets/116618017/150d04b1-1fb3-40b6-bb2a-64958f11e4ec)

### 如何复现该问题 (How to reproduce the problem)

是需要进行相关配置？

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
用pnpm preview去预览

**Comment by bwcgithub** [comment]
pnpm preview 也不会出现问题
![ddd](https://github.com/pure-admin/vue-pure-admin/assets/116618017/75266210-a8a9-42a2-b5d4-504dc8431219)
但就是将  .env.production 文件下的 VITE_PUBLIC_PATH = "https://test.***/znadmin/" 打包后 部署就会出现。
https:/ 应该是 https://
![dddd0](https://github.com/pure-admin/vue-pure-admin/assets/116618017/51173c3e-cbcd-4e79-a1b3-4456fe8ed181)
