### ISSUE TITLE
pnpm preview 演示不会出现问题， 但发布测试环境就会出现路径错误问题。

### ISSUE THREAD

**Issue by bwcgithub** [pure-admin/vue-pure-admin#614]
### 描述问题 (Describe the problem)

pnpm preview 也不会出现问题
![ddd](https://github.com/pure-admin/vue-pure-admin/assets/116618017/2b404b65-97f1-46df-954c-cc513858dbcb)

### 如何复现该问题 (How to reproduce the problem)

但就是将 .env.production 文件下的 VITE_PUBLIC_PATH = "[https://test.***/znadmin/](https://test.%2A%2A%2A/znadmin/)" 打包后 部署就会出现。
https:/ 应该是 https://
![dddd0](https://github.com/pure-admin/vue-pure-admin/assets/116618017/b3f185ea-8a50-4000-ba1f-c5dd6f7a1fab)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看文档
