### ISSUE TITLE
query穿参数面包屑丢失问题

### ISSUE THREAD

**Issue by jwh-1998** [pure-admin/vue-pure-admin#619]
### 描述问题 (Describe the problem)

我在router文件里直接配置了路由，然后在views的页面进行query跳转，面包屑丢失了，请问是不是不能用这样的形式呢？
<img width="361" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/77225433/5a82f1cf-e08f-4890-be69-a570dfd01e9b">
<img width="443" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/77225433/d697bad3-77bd-4cea-a954-39420cf9ff19">
<img width="991" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/77225433/db19953e-0fb1-45ae-a407-36f2407ad067">

### 如何复现该问题 (How to reproduce the problem)

不写hook.ts文件，直接配置路由进行跳转

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考 https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/tabs/hooks.ts
必须写

**Comment by shirely1018** [comment]
> 参考 https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/tabs/hooks.ts 必须写

您好，请问后期会不会优化这部分，不写hooks也不会丢失参数啊
