### ISSUE TITLE
`RePureTableBar`组件初始化时列设置勾选项未根据`hide`属性正确初始化

### ISSUE THREAD

**Issue by hogking** [pure-admin/vue-pure-admin#621]
### 描述问题 (Describe the problem)

你好，
我的某列配置如下：
{
...
minWidth: 130,
fixed: true,
hide: true
}。
表格是隐藏展示该列了，但在“列设置”中该列默认状态还是已被选中状态。

### 如何复现该问题 (How to reproduce the problem)

列配置加入{
...
hide: true
}即可

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/bf67e3673101937499d1edcc0da1feccef38268e)

**Comment by hogking** [comment]
感恩的心
