### ISSUE TITLE
对话框（reDialog）关闭时没有动画

### ISSUE THREAD

**Issue by axel10** [pure-admin/vue-pure-admin#622]
### 描述问题 (Describe the problem)

element-plus的对话框关闭时是有动画的，这里就没有了

### 如何复现该问题 (How to reproduce the problem)

打开对话框后关闭对话框

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
是的 直接销毁 没有动画

**Comment by xiaoxian521** [comment]
[已修复](https://github.com/pure-admin/vue-pure-admin/commit/4bbbd56a2a83fac7890032f46a2fcb69d934d1b0)
