### ISSUE TITLE
meta.saveSrollTop 属性貌似缺少类型定义

### ISSUE THREAD

**Issue by fxzer** [pure-admin/vue-pure-admin#623]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/68853957/e3ecef38-333d-4842-be47-f9b71adc779a)

**还有就是有两个疑问？ 望解答，谢谢！**
1. 想问一下为什么有两处相关的类型定义呢？
2. 为什么路由是对象断言为 `RouteConfigsTable`类型，但是需要在 `CustomizeRouteMeta` 类型上添加 ` saveSrollTop?: boolean;`才能生效呢？也没看到相关的继承关系，有点不太理解😁

![image](https://github.com/pure-admin/vue-pure-admin/assets/68853957/4065a522-ad09-4329-92e4-46bf085e3195)
![image](https://github.com/pure-admin/vue-pure-admin/assets/68853957/8125a475-dc5e-4b2c-bc83-a26350f5304c)

### 如何复现该问题 (How to reproduce the problem)

router.d.ts
layout/types.ts

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
不好意思 暂时没时间将源码 自己理解学习哈

**Comment by fxzer** [comment]
👌🏻
