### ISSUE TITLE
为何无法读取定义的全局类型

### ISSUE THREAD

**Issue by 18626428291** [pure-admin/vue-pure-admin#625]
### 描述问题 (Describe the problem)

clone项目后,tsconfig.json和types文件夹相同
项目根目录下的types文件下的d.ts
在build文件下的index.ts使用会报错 typescript:error:2303 未找到
请问是什么原因

### 如何复现该问题 (How to reproduce the problem)

文件都是正常配置的不知道为何不好使

### 操作系统和浏览器信息 (Operating system and browser information)

macos m1 :16g内存

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供具体代码 和截图

**Comment by xiaoxian521** [comment]
无法复现
<img width="1459" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/f9fc296f-f19f-4d82-9289-085daecfa39a">
