### ISSUE TITLE
搜索项样式优化建议

### ISSUE THREAD

**Issue by hogking** [pure-admin/vue-pure-admin#626]
### 描述问题 (Describe the problem)

您好，有一个样式的优化建议：element-plus更新后（2.3.7版本），比如部门管理、角色管理页面内的搜索框项元素el-select无法直接通过width属性控制宽度了，现在页面内的搜索按钮和搜索项之间的间隔也消失了。

### 如何复现该问题 (How to reproduce the problem)

比如"部门管理"，class="!w-[180px]"宽度控制失效。
<el-form-item label="状态：" prop="status">
        <el-select
          v-model="form.status"
          placeholder="请选择状态"
          clearable
          class="!w-[180px]"
        >
          <el-option label="启用" :value="1" />
          <el-option label="停用" :value="0" />
        </el-select>
      </el-form-item>
2.3.7版本存在该问题，回退至2.3.5就正常。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/commit/5d9e7506692259a166d858e6a20f0ad3c4c7ccff

**Comment by xiaoxian521** [comment]
你可以通过样式覆盖但这绝对不是很好的办法
最好是element-plus那里优化
