### ISSUE TITLE
请教作者,如果项目需要SEO,  该平台如何改造成SSR?

### ISSUE THREAD

**Issue by QQiTong** [pure-admin/vue-pure-admin#628]
### 描述问题 (Describe the problem)

如题
请教作者,如果项目需要SEO,  该平台如何改造成SSR?

### 如何复现该问题 (How to reproduce the problem)

如题

### 操作系统和浏览器信息 (Operating system and browser information)

如题

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
首先需要了解 `nuxt`
