### ISSUE TITLE
当路由模式改为h5时，导致找不到全局配置serverConfig.json

### ISSUE THREAD

**Issue by charlesCuiLee** [pure-admin/vue-pure-admin#630]
### 描述问题 (Describe the problem)

当路由模式改为h5得时候，由于publicPath为./ 导致找不到serverConfig.json

### 如何复现该问题 (How to reproduce the problem)

切换env 路由模式为h5，并在子路由刷新页面会报错

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
请提供报错截图

**Comment by charlesCuiLee** [comment]
![微信图片_20230629151648](https://github.com/pure-admin/vue-pure-admin/assets/45957000/9d9d888e-51a4-4240-8f11-812e96dcd009)

在此路由刷新后

**Comment by xiaoxian521** [comment]
报错信息？

**Comment by charlesCuiLee** [comment]
![微信图片_20230629151648](https://github.com/pure-admin/vue-pure-admin/assets/45957000/c8798083-0a97-4c0c-9aba-3d6d022e1f78)

当前路由模式已经切换到h5了 ，此路由刷新后

![微信截图_20230629151708](https://github.com/pure-admin/vue-pure-admin/assets/45957000/24170c65-2d8a-41fe-a854-28d566a2fb5b)

**Comment by xiaoxian521** [comment]
暂时解决办法：`VITE_ROUTER_HISTORY`为`h5` 打包时 `VITE_PUBLIC_PATH` 可不用 `./` 比如用 `/` 这个根据自己的实际情况
平台会抽空解决这个问题

**Comment by charlesCuiLee** [comment]
嗯嗯，暂时是手动改为/了，辛苦

**Comment by xiaoxian521** [comment]
测试了下 由于 `h5` 在部署时比较特殊，`VITE_PUBLIC_PATH` 不要用 `./` 可以用`/ `，这个根据自己的实际情况，后面会在文档进行备注提示
