### ISSUE TITLE
The project uses maps, but manipulating them can lead to a surge in CPU usage and visual lag

### ISSUE THREAD

**Issue by Universe-Stardust** [pure-admin/vue-pure-admin#634]
### 描述问题 (Describe the problem)

The project uses maps, but manipulating them can lead to a surge in CPU usage and visual lag

### 如何复现该问题 (How to reproduce the problem)

import Baidu Maps, and mount it. Then zoom the map

### 操作系统和浏览器信息 (Operating system and browser information)

Windows 11 or MacOS，Chrome

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
use mapbox it works great
