### ISSUE TITLE
使用动态路由时，第一个菜单无法跳转到path或者component指定的页面

### ISSUE THREAD

**Issue by alibbbian** [pure-admin/vue-pure-admin#637]
### 描述问题 (Describe the problem)

```
const permissionRouter1 = [
  {
    "path": "/base",
    "name": "基础管理1",
    "meta": {
      "title": "基础管理",
      "icon": "2",
      "rank": 2
    },
    "children": [
      {
        "path": "/base/qqq/index",
        "name": "菜单管理1",
        "meta": {
          "title": "菜单管理",
          "icon": "1212",
          "rank": 1,
          "auths": [
            "btn_add",
            "btn_edit",
            "btn_delete"
          ],
          "roles": [
            "admin",
            "user"
          ]
        }
      },
      {
        "path": "/base/role/index",
        "name": "角色管理",
        "meta": {
          "title": "角色管理",
          "icon": "role",
          "rank": 10,
          "auths": [
            ""
          ],
          "roles": [
            "admin",
            "user"
          ]
        }
      },
      {
        "path": "/base/user/index",
        "name": "用户管理",
        "meta": {
          "title": "用户管理",
          "icon": "user",
          "rank": 333,
          "auths": [
            ""
          ],
          "roles": [
            "admin",
            "user"
          ]
        }
      }
    ]
  },
  {
    "path": "/a",
    "name": "测试一级菜单",
    "meta": {
      "title": "测试一级菜单",
      "icon": "IF-team-icontabs",
      "rank": 11111,
      "auths": [
        "a",
        "b",
        "c",
        "d"
      ],
      "roles": [
        "admin",
        "user"
      ]
    }
  }
];
```
![image](https://github.com/pure-admin/vue-pure-admin/assets/18041895/09423a96-03f7-4194-9349-365e478cecba)

使用上面代码的动态路由配置和如图中views的代码结构，点击“菜单管理”页面就会跳到views/base/permisssion/button/index.vue页面

见源码，[第一处](https://github.com/pure-admin/vue-pure-admin/blob/b674db0a0601bb1c37ebba3c70ca2ad8468b1dc7/src/router/utils.ts#L27) [第二处](https://github.com/pure-admin/vue-pure-admin/blob/b674db0a0601bb1c37ebba3c70ca2ad8468b1dc7/src/router/utils.ts#L310-L313)

已修改第一处源码为
`const modulesRoutes = import.meta.glob("/src/views/**/index.vue");` 问题解决

不明白这里存储route为何要加载所有的vue和tsx文件！
另外某个菜单如果定义的children为[]，该菜单会不显示。我这个搞后台的前辈有点后悔上车。
搞脚手架的东西，很忌讳把问题复杂化。因为越复杂的东西越难考虑周全，简单点就好。有时候总是适得其反

### 如何复现该问题 (How to reproduce the problem)

复现及其简单，见上面描述问题的代码和截图

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
好好看文档 真搞笑 你家 `name` 用中文呀

**Comment by xiaoxian521** [comment]
免费的东西提供 那么详细的文档 也挡不住你的愚蠢

**Comment by xiaoxian521** [comment]
不要永远做个白嫖党 什么年代了 自己去主动学习 提示技术 那不迟早被淘汰
