### ISSUE TITLE
关于路由是否可以禁用

### ISSUE THREAD

**Issue by lee-stars** [pure-admin/vue-pure-admin#639]
### 描述问题 (Describe the problem)

你好作者，首先感谢你提供了这么好的开源作品，在使用的过程中有些疑问，因为没有其他查询渠道，文档也无相关说明，故冒昧提交ISSUE。

系统是前端控制权限，在实际的应用之中，可能会涉及到某一路由临时禁用的情景（改变状态为-1），我可以通过后端的where让该动态路由不显示，但是这个解决方法是不符合逻辑的，因为用户直接输入路由还是可以访问的。

请问，怎么样才能实现我禁用路由之后，用户访问该路由直接返回404或者其他操作呢。

### 如何复现该问题 (How to reproduce the problem)

路由管理，切换路由状态之后拥有权限组的用户还是可以访问已禁用路由

### 操作系统和浏览器信息 (Operating system and browser information)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前设计是 只有有权限的角色才能访问对应路由 无权限 访问会404

**Comment by xiaoxian521** [comment]
参考代码 https://github.com/pure-admin/vue-pure-admin/blob/main/src/router/index.ts#L129

**Comment by lee-stars** [comment]
非常感谢，有思路了，直接禁用的时候赋值权限为空，任何人都无法访问
