### ISSUE TITLE
生产环境系统出现报错，原因是@pureadmin/utils的1.9.7版本，useGlobal函数报错

### ISSUE THREAD

**Issue by jeff-fe** [pure-admin/vue-pure-admin#644]
### 描述问题 (Describe the problem)

生产环境系统出现报错，原因是@pureadmin/utils的1.9.7版本，useGlobal函数报错

### 如何复现该问题 (How to reproduce the problem)

https://github.com/xiaoxian521/pure-admin-utils   这个仓库为啥改成私有了？

### 操作系统和浏览器信息 (Operating system and browser information)

生产环境系统出现报错，原因是@pureadmin/utils的1.9.7版本，useGlobal函数报错

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
无法复现
https://github.com/pure-admin/pure-admin-utils-docs/issues/7
