### ISSUE TITLE
演示的地址访问出现报错

### ISSUE THREAD

**Issue by jeff-fe** [pure-admin/vue-pure-admin#645]
### 描述问题 (Describe the problem)

演示的地址访问出现报错

### 如何复现该问题 (How to reproduce the problem)

演示的地址访问出现报错

### 操作系统和浏览器信息 (Operating system and browser information)

<img width="650" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/19850462/888878c7-79ae-47a8-aecb-bf00d372255a">

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
你的浏览器版本有问题 按照文档版本来 多看文档 你的这些问题文档基本都有 我很忙 多看文档 谢谢
