### ISSUE TITLE
路由没有正常显示，必须刷新页面才会显示

### ISSUE THREAD

**Issue by Echoidf** [pure-admin/vue-pure-admin#647]
### 描述问题 (Describe the problem)

我使用的是精简版，添加了系统管理路由文件后，登录完成进行跳转，该路由没有正常显示，必须刷新页面才会显示，请问这个问题怎么解决？(另一个自定义的一级菜单路由文件显示正常) 我的路由文件如下：
```
export default {
  path: "/system",
  meta: {
    title: "系统管理",
    rank: 3
  },
  children: [
    {
      path: "/system/menu/index",
      name: "MenuManage",
      component: () => import("@/views/system/menu/index.vue"),
      meta: {
        title: "菜单管理",
        roles: ["admin"]
      }
    },
    {
      path: "/system/user/index",
      name: "UserManage",
      component: () => import("@/views/system/user/index.vue"),
      meta: {
        title: "用户管理",
        roles: ["admin"]
      }
    },
    {
      path: "/system/role/index",
      name: "RoleManage",
      component: () => import("@/views/system/role/index.vue"),
      meta: {
        title: "角色管理",
        roles: ["admin"]
      }
    },
    {
      path: "/system/perm/index",
      name: "PermManage",
      component: () => import("@/views/system/permission/index.vue"),
      meta: {
        title: "权限管理",
        roles: ["admin"]
      }
    }
  ]
};

```

### 如何复现该问题 (How to reproduce the problem)

none

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
像这种问题多看文档 安装文档配置路由

**Comment by duhaohao** [comment]
很可能不是路由配置的问题，可以看下F12看下控制台有没有警告。
我出错的情况是这样的，<template></template>下,最外层有多个同级标签。
会导致Layout中的组件弹出警告。

**Comment by lujuny** [comment]
我也遇到同样的问题，想请教楼主是否找到解决办法

**Comment by Kaka25z** [comment]
> 我也遇到同样的问题，想请教楼主是否找到解决办法

我这里发现的问题是vue文件内<template>标签下超过两个div，跳转时就需要刷新页面才能显示。只有一个div是正常显示
