### ISSUE TITLE
获取response的headers

### ISSUE THREAD

**Issue by hogking** [pure-admin/vue-pure-admin#650]
### 描述问题 (Describe the problem)

作者您好，使用项目中封装好的http请求工具获取的response我该如何修改才能获得其headers呢？这主要是为了获取后端返回的自定义头信息（比如自定义文件名称）。当使用原生axios时获得的response是可以直接通过res.headers读取到headers信息的。

### 如何复现该问题 (How to reproduce the problem)

使用任意项目封装请求。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供你用axios未封装前获取headers截图

**Comment by xiaoxian521** [comment]
返回结果是后端返回
而不是自动带

**Comment by hogking** [comment]
很奇怪，后端接口并没有任何改动。
我再附上两者的代码对比，请求参数感觉是没有差异的（如果pureHttp只是简单地再封装）：
<img width="599" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/38121483/a93389d1-447e-477b-8c40-2490f6081765">


我尝试在项目封装工具内打印response，结果如下：
<img width="429" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/38121483/767901ca-a754-4ac4-b568-160550d394d2">
结果如下：
<img width="577" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/38121483/46353fb8-a95f-4c73-bf00-68dbd5c3c040">
可以看到和上面回复中的原生返回就是存在差异~
但浏览器的看响应头是有该headers信息的：
<img width="483" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/38121483/17ec094a-6520-4905-a3e6-72bba3ad75a3">
不知道是不是封装的PureHttp遗弃了一些信息

**Comment by xiaoxian521** [comment]
你的`headers`是自己传的啊 平台封装的公共的 你用平台封装的http工具 就要单独自己在传`headers`

**Comment by hogking** [comment]
您好，不知道是我理解有误还是您理解有误了。我感觉您回复的是指我的请求吧，因为平台封装的工具是默认请求会带上token信息，这里我传的headers只是为了把token带过去（和平台对齐，平台封装的会自动传JWT TOKEN，原生axios不会嘛）。
然后我不是指请求的headers的问题哈，是后台返回的response的headers缺失的问题。

**Comment by hogking** [comment]
相当于两者请求是一样的，两个请求调用的后台接口也是一样的，但是前端拿到这个response时得到的对象是不一样的。原生axios得到的信息会更丰富，平台封装的会有缺失（比如headers信息）。

**Comment by AlcoholTobaccoCode** [comment]
@hogking 你可以看下响应拦截，响应拦截先于自定义请求返回：
![image](https://github.com/pure-admin/vue-pure-admin/assets/49547938/248bb1f2-307f-4340-a0e8-7b7b48638165)

响应拦截里面的数据是全的，观察是否返回的时候只返回了 data 
![image](https://github.com/pure-admin/vue-pure-admin/assets/49547938/2e0acfec-10d5-47e3-9d59-55dcc5d0c85c)

**Comment by xiaoxian521** [comment]
<img width="1295" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/4d15f1ff-fcae-4be0-9f58-efe8f3450a7b">

这是你想要的效果吧？ 自己改下吧 通常为了方便只返回data 也就是后端返回什么 我们就会返回什么 别的信息不带 
上图除了data里的东西是后端返回 别的是axios处理的

**Comment by hogking** [comment]
“响应拦截先于自定义请求返回”
感谢 @AlcoholTobaccoCode，@xiaoxian521 。前端菜鸡给添麻烦了。。。

**Comment by xiaoxian521** [comment]
比如可以这么改，别动地方雷同
<img width="718" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/b6014dde-9019-40d2-b3ca-1d6c22866155">
