### ISSUE TITLE
在对接后端服务的时候，发现白名单的判断逻辑误判 config.url.indexOf(v) > -1 

### ISSUE THREAD

**Issue by valarchie** [pure-admin/vue-pure-admin#651]
### 描述问题 (Describe the problem)

在对接后端的时候发现 config.url.indexOf(v) > -1 比较不准确。
比如const whiteList = ["/login"];
如果后端的请求链接是 /loginInfo 或者 login/list 或者 /loginByWechat 会造成误判。  

假设const whiteList = ["/login"]
但是我访问的接口是/loginInfo, 此时因为它被识别成白名单，所以请求不会加上token.
我不能往白名单中加 const whiteList = ["/loginInfo"]
因为loginInfo是需要有token才能访问。

### 如何复现该问题 (How to reproduce the problem)

当后端的接口可以模糊匹配白名单中的链接时。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/49106b90b7bce2f24ec5c4024bfbf4c4c0abd944)
