### ISSUE TITLE
提交代码提示

### ISSUE THREAD

**Issue by lixh00** [pure-admin/vue-pure-admin#652]
### 描述问题 (Describe the problem)

如图所示，代码不为空提示是个空文件导致无法提交代码

![image](https://github.com/pure-admin/vue-pure-admin/assets/72033265/8c662827-f18b-4114-aef2-33094089a28d)

### 如何复现该问题 (How to reproduce the problem)

> git add .
> git commit -m 'feat: xxxxxx'

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供复现仓库

**Comment by lixh00** [comment]
本地，怎么提供仓库，都没能push上去

**Comment by xiaoxian521** [comment]
用平台代码模拟好问题 推送
还有像你这种问题几乎不可能发生 从没遇过

**Comment by lixh00** [comment]
怎么删掉 subject-empty 校验？我删除`commitlint.config.js`里面的`"subject-empty": [2, "never"],`，还是会校验
