### ISSUE TITLE
会考虑更换请求器达到更好的效果吗

### ISSUE THREAD

**Issue by wintsa123** [pure-admin/vue-pure-admin#654]
### 描述问题 (Describe the problem)

alova.js请求器封装了很多场景实例的方案hook，我觉得比axios更加实用

### 如何复现该问题 (How to reproduce the problem)

not bug

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
稳定性是第一位其次是用户使用数
如果这两点alova.js 达到了 甚至比 axios 高 就会换
