### ISSUE TITLE
左边菜单栏，可以添加角标吗？

### ISSUE THREAD

**Issue by enjoy322** [pure-admin/vue-pure-admin#656]
### 描述问题 (Describe the problem)

左侧菜单栏希望添加角标

### 如何复现该问题 (How to reproduce the problem)

左侧菜单栏希望添加角标

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
这个很简单 自行添加哈

**Comment by enjoy322** [comment]
可以咨询一下，如何添加吗？没有找到
| |
glclover
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年7月20日 16:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [pure-admin/vue-pure-admin] 左边菜单栏，可以添加角标吗？ (Issue #656) |

这个很简单 自行添加哈

**Comment by xiaoxian521** [comment]
角标是你自己写css啊
平台没有这种功能而且这种需求属于定制化 不属于通用
请自行添加

**Comment by xiaoxian521** [comment]
<img width="1594" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/3fd4b447-086e-4a36-ac63-0249b26aa56e">

```
 <!-- 左侧顶部小凹角 -->
    <div class="horn" />

.horn {
  width: 18px;
  height: 18px;
  position: fixed;
  background: radial-gradient(21px at right bottom, transparent 90%, red 1%);
}
```
