### ISSUE TITLE
滑块验证码或者极验验证码

### ISSUE THREAD

**Issue by juukee** [pure-admin/vue-pure-admin#657]
### 描述问题 (Describe the problem)

前端使用滑块类的比较多，类似：https://vben.vvbin.cn/#/comp/verify/rotate
这个后续会增加吗？

### 如何复现该问题 (How to reproduce the problem)

增加验证模块

### 操作系统和浏览器信息 (Operating system and browser information)

window 

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考 https://github.com/xiaoxian521?q=%E6%BB%91%E5%9D%97&tab=stars&type=&sort=&direction=
欢迎pr
暂时没有 不打算开发这
