### ISSUE TITLE
`src/layout/components/appMain.vue`文件中同名词读取解析错误

### ISSUE THREAD

**Issue by hxzAugustinus** [pure-admin/vue-pure-admin#658]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/14306029/bbea53e1-1369-4560-a779-1686ffd24c59)

![image](https://github.com/pure-admin/vue-pure-admin/assets/14306029/25bd99ed-4f1f-48c4-bb83-cbe1b9d1f7cd)

appMain.vue 里的  有个 变量  keepAlive  时 ， 组件 <keep-alive> 不知道为什么解析指向 这个 变量了 ；

把 变量  keepAlive 改成  keepAlive1 时 ，就正常解析了，指向正确的声明 ；

建议把  变量 keepAlive  改一下名字 ；

 

### 如何复现该问题 (How to reproduce the problem)

无法复现  ，但建议改一下名字

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
可以改为 `isKeepAlive` 欢迎`pr`

**Comment by hxzAugustinus** [comment]
已提交pr

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/616703f7ed5f50db4539677b5ad1c375e66a44c9)
