### ISSUE TITLE
国际化信息监听

### ISSUE THREAD

**Issue by xwland666** [pure-admin/vue-pure-admin#660]
### 描述问题 (Describe the problem)

我想在tsx文件里面监听国际化信息的改变从而修改一部分开启项目后只渲染一次的值（比如方法中的数组值），但是问题是我没法监听到国际化信息的改变。

### 如何复现该问题 (How to reproduce the problem)

在精简版国际化版本的tsx文件里面用export default 方式创建方法，在方法里面定义数组属性，数组中值是从国际化语言配置文件里面拿过来的。当国际化信息改变是数组中属性值没有发生改变。考虑通过监听国际化信息改变从而实现数组值的改变，但是没有找到方法监听

### 操作系统和浏览器信息 (Operating system and browser information)

windows11  谷歌浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
项目里有代码参考 自行查找
