### ISSUE TITLE
Failed to resolve component: pure-table

### ISSUE THREAD

**Issue by 0x777A** [pure-admin/vue-pure-admin#661]
### 描述问题 (Describe the problem)

前端小白，基于pure-admin-thin开发使用RePureTableBar， 表格不显示， 浏览器报错：
```
 [Vue warn]: Failed to resolve component: pure-table
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <User onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/pool/position"  ... > 
  at <KeepAlive key=0 include= [] > 
  at <BaseTransition mode="out-in" appear=true persisted=false  ... > 
  at <Transition name="fade-transform" enterActiveClass=undefined leaveActiveClass=undefined  ... > 
  at <Anonymous route= {fullPath: '/pool/position', path: '/pool/position', query: {…}, hash: '', name: 'position lsit', …} > 
  at <ElScrollbar key=0 > 
  at <RouterView> 
  at <AppMain fixed-header=true > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <ElConfigProvider locale= {name: 'zh-cn', el: {…}} > 
  at <App>
```

### 如何复现该问题 (How to reproduce the problem)

新建一个新页面，引用RePureTableBar即可复现

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by yttx-lql** [comment]
修改 `src/main.ts` 中将 `import Table from "@pureadmin/table";` 的注释取消掉，再把下面 `.use(Table)` 的注释取消掉。
