### ISSUE TITLE
storageSession user-info 丢失

### ISSUE THREAD

**Issue by ChinaXiaobird** [pure-admin/vue-pure-admin#662]
### 描述问题 (Describe the problem)

新标签页会跳转到login  我想保持登录态怎么做合适

### 如何复现该问题 (How to reproduce the problem)

登录后打开新标签页

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提示：session共享 自行实现

**Comment by ChinaXiaobird** [comment]
好
