### ISSUE TITLE
路由权限不需要验证除了修改路由beforeEach还有其他方法吗

### ISSUE THREAD

**Issue by lee-stars** [pure-admin/vue-pure-admin#663]
### 描述问题 (Describe the problem)

大佬好，又来提问来了，我有一个需求 ，添加一个页面到路由里面，但是这个页面不需要权限，任何人都可以访问，包括没有登录的人，只要他访问路由都可以正常的访问。

出列根据文档，在beforeEach添加白名单，还有其他的办法吗，因为不想动作者的源码，怕以后升级更改。

### 如何复现该问题 (How to reproduce the problem)

无需复现

### 操作系统和浏览器信息 (Operating system and browser information)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
不好意思 很忙 不讲解这些 自己多看看文档 研究下

**Comment by xiaoxian521** [comment]
目前只接受 bug 提问

**Comment by lee-stars** [comment]
好的好的
