### ISSUE TITLE
关于PureTableBar 组件，一个bug，一个疑问

### ISSUE THREAD

**Issue by jianyuma** [pure-admin/vue-pure-admin#665]
### 描述问题 (Describe the problem)

一、PureTableBar 组件，列展示添加拖拽功能，设置了fixed，checkbox并没有变为禁用状态
这是我看到Pull requests里关于PureTableBar拖拽功能更新时的描述是可以根据fixed设置为禁用状态的。
<img width="92" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/56958261/83f8e749-9076-49b1-84f8-5161af85a785">
但是实际并没有，只是鼠标变成了一个带有表示”禁用“的图标，
<img width="94" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/56958261/bab08f45-8f14-4ea8-96ad-8ed32cb07f7b">
拉取的框架版本是[v4.3.0]的。

二、要使用PureTableBar组件的拖拽功能，columns里每个对象必须使用label吗？
由于我需要使用多语言，所以使用headerRenderer去处理，这样才能在选择不同语言的时候立即更换语言。
```
 {
    headerRenderer: function () {
      return h("div", {}, transformI18n("crud_table.title"));
    },
    prop: "title",
    minWidth: 120
  },
```
但是使用headerRenderer，虽然可以处理多语言了，但是PureTableBar组件的列展示，都读取不到对应的列
<img width="1795" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/56958261/45709809-b00c-45ad-a6dd-772116e83199">
使用label也可以读取到多语言的内容，但是没办法做到选择语言的时候立即更换，只有刷新整个页面才能更换语言
```
 {
    label: `${transformI18n('crud_table.title') }`,
    prop: "title",
    minWidth: 120
  },

```

所以想问下有没有兼顾多语言，又能使用到PureTableBar组件的列展示和拖拽功能？

### 如何复现该问题 (How to reproduce the problem)

一、
```
  {
    label: '序号',
    type: 'index',
    width: 70,
    fixed: 'left'
  },
```

二、
```
  {
    headerRenderer: function () {
      return h("div", {}, transformI18n("crud_table.title"));
    },
    prop: "title",
    minWidth: 120
  },
```

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考项目代码 或以后issues

**Comment by xiaoxian521** [comment]
还有版本请使用最新版 非最新版 那就需要自己参考提交记录去看
