### ISSUE TITLE
功能-导出Excel：在表格中导出Date格式的数据时，时间不准确。

### ISSUE THREAD

**Issue by FrontEndDog** [pure-admin/vue-pure-admin#666]
### 描述问题 (Describe the problem)

在导出excel时，如果带有Date格式的数据，在中国会多出43秒，时区如果在韩国，会多出52秒，其他时区未测试。

在excel.vue文件中50行添加一行代码：data[0]["column-0"] = new Date("2023/07/25 12:00:00");
<img width="349" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/46493087/f4a07bb6-5bf5-42f9-a1ec-f4a8698afaa7">

### 如何复现该问题 (How to reproduce the problem)

复现仓库：https://github.com/FrontEndDog/vue-pure-admin/tree/excel-recurrent
分支：excel-recurrent

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
没平台问题 自行研究`xlsx` 像你这种问题 大概率是你写法问题

**Comment by xiaoxian521** [comment]
解决办法之一： https://github.com/pure-admin/vue-pure-admin/pull/668

强烈推荐后端导出，因为无论从性能还是自定义方面，后端控制更为方便
