### ISSUE TITLE
pure-table 中 loading 配置 background 不生效问题

### ISSUE THREAD

**Issue by Liuzebiao** [pure-admin/vue-pure-admin#671]
### 描述问题 (Describe the problem)

代码见图片：https://test-1318510234.cos.ap-beijing.myqcloud.com/loading%E4%B8%ADbackground%E5%B1%9E%E6%80%A7%E4%B8%8D%E7%94%9F%E6%95%88%E9%97%AE%E9%A2%98%E4%BB%A3%E7%A0%81%E4%BD%8D%E7%BD%AE.png

此处的background好像不生效。只有2种情况就是rgba(0,0,0,0.45) 和 rgba(255,255,255,0.45)

### 如何复现该问题 (How to reproduce the problem)

官方demo即可测试出来

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
在此处提问 https://github.com/pure-admin/pure-admin-table/issues
