### ISSUE TITLE
[feature]能否开源组件库？允许通过npm包安装

### ISSUE THREAD

**Issue by wintsa123** [pure-admin/vue-pure-admin#672]
### 描述问题 (Describe the problem)

如果我用的vue3，不是基于你的框架搭建的，我能否通过引入，npm包安装之类的方法，使用你的组件，当然我已经看到你的组件的代码了，我希望能更加快捷的去使用它？
眼红了，有几个组件看着很好用，但我的个人后台从0搭建，不是很舍得更换底层

### 如何复现该问题 (How to reproduce the problem)

1

### 操作系统和浏览器信息 (Operating system and browser information)

1

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
自己拉进去
