### ISSUE TITLE
异常网络请求

### ISSUE THREAD

**Issue by XieB** [pure-admin/vue-pure-admin#673]
### 描述问题 (Describe the problem)

看着是字体图标的，我准备把这个项目部署到无网络线下环境，是不是不行？

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/11675821/172d70c0-1be3-4a9d-8904-10a05364968e)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看文档
