### ISSUE TITLE
HRM 总是full-reload

### ISSUE THREAD

**Issue by neostfox** [pure-admin/vue-pure-admin#674]
### 描述问题 (Describe the problem)

修改任意views下面的tsx，均会触发HMR的full-reload

### 如何复现该问题 (How to reproduce the problem)

修改仓库下任意views下的tsx

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
无法复现
