### ISSUE TITLE
PureTableBar内使用多选表格时，通过列设置拖拽改变排序，会导致数据渲染异常，丢失列或显示排序与设置不一致

### ISSUE THREAD

**Issue by LiunianShuai** [pure-admin/vue-pure-admin#675]
### 描述问题 (Describe the problem)

PureTableBar内使用多选表格时，通过列设置拖拽改变排序，会导致数据渲染异常，丢失列或显示排序与设置不一致
![bug 20230730233017](https://github.com/pure-admin/vue-pure-admin/assets/100208109/9f92c30a-9eef-4616-bfe8-c0997f4e4460)

### 如何复现该问题 (How to reproduce the problem)

vue-pure-admin完整代码中
src/views/system/dept/utils/hook.tsx文件内
变量columns 数组内添加
`  {
      type: "selection",
      reserveSelection: true
    },`
然后页面内点击列设置拖拽排序即可稳定复现

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多参考以往issues
https://github.com/pure-admin/vue-pure-admin/issues/591

**Comment by LiunianShuai** [comment]
谢谢大佬解惑！下次提问前，我会注意先多查历史issues，这次抱歉啦 (>人<;)
