### ISSUE TITLE
关于表单中展示图标不生效的问题

### ISSUE THREAD

**Issue by kunlong-luo** [pure-admin/vue-pure-admin#676]
### 描述问题 (Describe the problem)

在表单中渲染从后台传过来的图标时，页面不生效，如下所示：

![image](https://github.com/pure-admin/vue-pure-admin/assets/40263163/c7789ca8-1cdc-4168-9feb-c8d119321afe)

![image](https://github.com/pure-admin/vue-pure-admin/assets/40263163/947d80c4-3bc5-4ead-9a86-7c4b576daf8d)

### 如何复现该问题 (How to reproduce the problem)

    {
      label: "图标",
      prop: "icon",
      minWidth: 120,
      cellRenderer: scope => <component is={useRenderIcon(toRaw(scope.row.icon))} />,
    },

### 操作系统和浏览器信息 (Operating system and browser information)

win11, google浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看文档学用法

**Comment by kunlong-luo** [comment]
以下代码解决了我的问题：
    {
      label: "图标",
      prop: "icon",
      minWidth: 120,
      cellRenderer: scope => (
        <el-button circle icon={useRenderIcon(toRaw(scope.row.icon))}></el-button>
      ),
    },

**Comment by kunlong-luo** [comment]
以下代码解决了我的问题：

    {
      label: "图标",
      prop: "icon",
      minWidth: 120,
      cellRenderer: scope => (
        <el-button circle icon={useRenderIcon(toRaw(scope.row.icon))}></el-button>
      ),
    },
