### ISSUE TITLE
token失效后，刷新页面无法请求后台api接口

### ISSUE THREAD

**Issue by kunlong-luo** [pure-admin/vue-pure-admin#677]
### 描述问题 (Describe the problem)

在token失效后，无法正常请求后台接口获取动态路由，侧边栏一直呈现加载状态，必须要退出并清空用户信息缓存，重新登陆后才行。
经过调试后发现问题出在路由守卫部分。

![image](https://github.com/pure-admin/vue-pure-admin/assets/40263163/af1a9c71-7d12-4f3a-8e1e-f1dfaa4d730e)

![image](https://github.com/pure-admin/vue-pure-admin/assets/40263163/93dde0ba-138b-441e-903a-c41ffa442220)

### 如何复现该问题 (How to reproduce the problem)

路由失效后刷新页面

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 有刷新token的接口啊
