### ISSUE TITLE
[pure-admin-utils - useEcharts] 个别属性不生效

### ISSUE THREAD

**Issue by ZexinW** [pure-admin/vue-pure-admin#678]
### 描述问题 (Describe the problem)

使用useEcharts发现个别属性不生效.

### 如何复现该问题 (How to reproduce the problem)

1.  使用useECharts时传入配置项:series.markPoint 或者 series.markLine.
<img width="570" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/110024406/dbe72c94-850b-4b99-8a56-0879587fe859">

2.  视图中没有最大值和最小值和渲染.
3. 并且 pure-admin预览网站首页的折线图的源码中也设置了该属性，也没有生效。

### 操作系统和浏览器信息 (Operating system and browser information)

浏览器：谷歌
OS:  macOs

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
首先你先别用`useEcharts`去检查改属性在你对于的echarts版本是否生效

如果生效 那么坚持你的版本问题，或者是否少安装了啥依赖或少引入了什么组件

因为`useEcharts` 不关心注册 只关心渲染

**Comment by ZexinW** [comment]
> 你首先先别`useEcharts`用去检查修改你的属性对于的echarts版本是否生效
> 
> 如果现在生效检查您的版本问题，或者是否少安装了啥依赖或少引入了什么组件
> 
> 因为`useEcharts`不关心注册 只关心渲染

明白.
但是.
1.  我是用的 pure-admin-thin，echarts版本和 pure-admin-mian 是一样的 5.4.2
2.  pure-admin-main中的相关配置也没生效，例如下图：
![image](https://github.com/pure-admin/vue-pure-admin/assets/110024406/c48cc6b9-e7f5-4fd1-a8d3-8298701d79e4)
![image](https://github.com/pure-admin/vue-pure-admin/assets/110024406/36b2b428-b1d3-453e-b19d-5f41253458e9)
3. 我使用 echarts 原生的方法去渲染，在没有引入其他包或者依赖的情况下，最大值最小值成功生效。
<img width="634" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/110024406/bc8eec25-3d0b-4e20-889f-a3d9b48529c4">

所以我才提的 issue.

**Comment by ZexinW** [comment]
> 请用完整版恢复该问题 专业版并没有注册echarts

您好，现在完整版本（pure-admin-main）就是有问题.

例如:
这才是正确的配置渲染，该渲染来自我写的简易hook.
![image](https://github.com/pure-admin/vue-pure-admin/assets/110024406/6af4aef3-3511-4774-ac5d-7fbaad0f8ef2)
![image](https://github.com/pure-admin/vue-pure-admin/assets/110024406/8486686d-105f-430d-b6b1-9658cb62b9e8)

目前的错误渲染，该渲染来自于 pure-admin-utils - useEcharts：
![image](https://github.com/pure-admin/vue-pure-admin/assets/110024406/5a410a27-354d-4064-b37f-028a16c3c488)

不存在是否注册 Echarts，因为我就是当前文件引入了 Echarts 依赖. 如果pure-admin-utils开源了的话，我就自己找问题直接发pr了.

总结: 传入了 配置项，经过 useEcharts 没有得到预期的渲染.

**Comment by yourbusiness** [comment]
这个问题解决了吗？我也遇到了

**Comment by yourbusiness** [comment]
这个问题麻烦可以看下吗？在项目外面用没问题，但是一旦拿到项目里面来用就有问题，markPoint失效，项目就是vue-pure-admin
