### ISSUE TITLE
使用element-plus组件问题

### ISSUE THREAD

**Issue by wu464818763** [pure-admin/vue-pure-admin#679]
### 描述问题 (Describe the problem)

使用带icon的按钮组件时不显示icon

### 如何复现该问题 (How to reproduce the problem)

<el-button type="primary">
    <el-icon style="vertical-align: middle">
      <Search />
    </el-icon>
    <span style="vertical-align: middle"> Search </span>
  </el-button>
页面用这段官方示例看就行

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/icon/
