### ISSUE TITLE
PPT模块插入竖向文本框时候，输入英文字符是顺时针90度。

### ISSUE THREAD

**Issue by haosj01** [pure-admin/vue-pure-admin#681]
### 描述问题 (Describe the problem)

PPT模块插入竖向文本框时候，输入英文字符是顺时针90度。
<img width="773" alt="1691308286741" src="https://github.com/pure-admin/vue-pure-admin/assets/21052456/aeec785c-fccb-4379-b287-f92f1badb270">

### 如何复现该问题 (How to reproduce the problem)

PPT模块插入竖向文本框时候，输入英文字符

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pipipi-pikachu/PPTist/issues
