### ISSUE TITLE
登录后,在新的tab页打开,需要再次登录的问题

### ISSUE THREAD

**Issue by podigua** [pure-admin/vue-pure-admin#682]
### 描述问题 (Describe the problem)

非国际化精简版
问题1:
1.已登陆成功,在新的tab页在此访问链接,会回到登录界面
2.退出浏览器后再次打开页会重新登陆

实际的token并没有过期,可以不需要再次登录才对,类似记住我的功能;
有部分信息存储在localStorage或者sessionStorage 是否可以通过某些手段来重新设置值,重新登陆不太友好;

### 如何复现该问题 (How to reproduce the problem)

登录完成后在新的tab打开即可复现

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/662
