### ISSUE TITLE
没有增加全局异常处理！

### ISSUE THREAD

**Issue by fxirtfyl** [pure-admin/vue-pure-admin#684]
### 描述问题 (Describe the problem)

1:登录接口超时以及接口报错，登录按钮一直在转圈
2:每个接口报错，不回提示正常的报错信息
3:建议根据返回的报错编码，或者 http状态来判断请求接口是否异常

// @ts-ignore
message(error.response.data.msg || "错误消息:请联系管理员!", {
  type: "error"
});

### 如何复现该问题 (How to reproduce the problem)

点击登录按钮，在登录接口发送异常的情况下，登录按钮一直转圈

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 自行添加 业务请自行处理
