### ISSUE TITLE
可拖拽函数式弹窗内容超出屏幕高度后拖拽异常

### ISSUE THREAD

**Issue by a-painting** [pure-admin/vue-pure-admin#685]
### 描述问题 (Describe the problem)

当可拖拽函数式弹窗内容超出屏幕高度后，拖拽弹窗会自动跳到顶部，而且遮盖了可拖拽区域导致无法拖拽

### 如何复现该问题 (How to reproduce the problem)

复现只需让可拖拽函数式弹窗内容超出屏幕高度

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
是这样的 根el-dialog的拖拽一样 需要把内容控制在屏幕高度内
