### ISSUE TITLE
手机打开侧边栏后无法收起

### ISSUE THREAD

**Issue by a-painting** [pure-admin/vue-pure-admin#686]
### 描述问题 (Describe the problem)

手机打开侧边栏后无法收起，收起按钮被遮盖了（点遮罩层无法收起），用pc端浏览器调试成h5却可以通过点击遮罩层收起

### 如何复现该问题 (How to reproduce the problem)

用手机打开pure-admin-thin项目

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/assets/44761321/073faace-090c-45d6-967b-237859bcc20c
