### ISSUE TITLE
设置了默认导航栏综合模式后导致手机端侧边栏无法收起

### ISSUE THREAD

**Issue by a-painting** [pure-admin/vue-pure-admin#687]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/54249795/b7b71d59-63ff-4a13-aeca-ead476a57bdc)
![image](https://github.com/pure-admin/vue-pure-admin/assets/54249795/a16623b4-7435-4ded-84b5-f4a0f99e9ac1)

我配置了默认导航栏综合模式，而手机打开只有左侧模式，可能是综合模式导致的遮罩层不见了？

### 如何复现该问题 (How to reproduce the problem)

serverConfig.json配置"Layout": "mix"
用手机打开项目

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by a-painting** [comment]
https://github.com/pure-admin/vue-pure-admin/assets/54249795/e642da10-3103-42d9-a03a-d8f718471afe

**Comment by xiaoxian521** [comment]
移动端只支持一种`左侧导航`模式

还有如果你要做移动端管理 建议用别的移动端开源库 这主打`pc端` 专业的事用专业的工具
