### ISSUE TITLE
弹窗是否可以增加抽屉模式的选项

### ISSUE THREAD

**Issue by georgeJzzz** [pure-admin/vue-pure-admin#689]
### 描述问题 (Describe the problem)

弹窗是否可以增加抽屉模式的选项

### 如何复现该问题 (How to reproduce the problem)

弹窗是否可以增加抽屉模式的选项

### 操作系统和浏览器信息 (Operating system and browser information)

win10

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
它们是两种不同组件
当然你也可以参考弹框的封装模式 自行封装抽屉
