### ISSUE TITLE
在用户管理的 tree.vue 文件中引入 ./hook.tsx 的 onSearch 方法后，index.vue页面里的数据不刷新

### ISSUE THREAD

**Issue by ryiot** [pure-admin/vue-pure-admin#690]
### 描述问题 (Describe the problem)

在用户管理的 tree.vue 文件中引入 ./hook.tsx 的 onSearch 方法后，index.vue页面里的数据不刷新。执行 onSearch() 可以获取的到api接口的数据并能在控制台打印出来，但是 ./index.vue 中的数据不会更新。在 ./index.vue 中调用onSearch()数据会更新。望解惑

### 如何复现该问题 (How to reproduce the problem)

./tree.vue
import { useUser } from "./hook";
const { onSearch } = useUser();

function nodeClick(value) {
  console.log(value);
  onSearch();
...

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
正在重构啊

**Comment by ryiot** [comment]
好的，加油
