### ISSUE TITLE
一个页面异常报错后，会导致所有路由页面无法访问

### ISSUE THREAD

**Issue by dongyanghe** [pure-admin/vue-pure-admin#691]
### 描述问题 (Describe the problem)

例如**\src\views\permission\page\index.vue**页面在浏览器运行访问时控制台报代码异常后

左侧菜单或顶部tab点击进入**\src\views\permission\button\index.vue**等其他任何页面都将无法进入

由于很多异常代码开发工具无法识别、构建编译时也不能发现，有些还是接口异常返回的造成的，所以认为这个问题有必要以一种方式规避下
![微信截图_20230817154203](https://github.com/pure-admin/vue-pure-admin/assets/11970788/04d5f1b1-69e6-4b45-8a6f-ed998cd19edd)

_在其他VUE3的后台管理框架测试，一个路由页面报错并不会影响其他继续访问_

### 如何复现该问题 (How to reproduce the problem)

在**\src\views\permission\page\index.vue**的第18行添加以下代码（或触发任何形式的代码异常）：
`console.log(usePermissionStoreHook().test().test);`

debugger调试发现异常在以下位置报出：
**\src\layout\components\tag\index.vue**
```
const moveToView = async (index: number): Promise<void> => {
  ...
  // 此处报出异常，代码中断
  await nextTick();
 ...
}
```

### 操作系统和浏览器信息 (Operating system and browser information)

所有浏览器和系统

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
做好规范
