### ISSUE TITLE
菜单栏显示问题

### ISSUE THREAD

**Issue by L1803703552** [pure-admin/vue-pure-admin#693]
### 描述问题 (Describe the problem)

当进入移动端显示的时候，“关于”菜单不显示[](url)

### 如何复现该问题 (How to reproduce the problem)

项目启动后，用手机进入局域网地址，打开左侧菜单，“关于”选项不显示
浏览器进入响应式开发界面，当宽度小于760px时，打开左侧菜单，“关于”选项不显示
![image](https://github.com/pure-admin/vue-pure-admin/assets/53083703/33e00f5a-fc69-4106-842e-5a93b6acbcce)

### 操作系统和浏览器信息 (Operating system and browser information)

Chrome 116.0.5845.97 x64 Windows

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [ ] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/51d8519b29c6ae02dff1ee4496d0088ea4f2719c)
