### ISSUE TITLE
异步操作导致组件实例丢失 使用useDataThemeChange().setEpThemeColor  @pureadmin/utils库报错

### ISSUE THREAD

**Issue by HQ-YYK** [pure-admin/vue-pure-admin#694]
### 描述问题 (Describe the problem)

# 报错信息
> Uncaught (in promise) TypeError: Cannot destructure property 'appContext' of '(0 , a.getCurrentInstance)(...)' as it is null.
![image](https://github.com/pure-admin/vue-pure-admin/assets/54365306/bb3a6fe5-bbbe-4c29-85a9-9ca81a1fd7c9)

### 如何复现该问题 (How to reproduce the problem)

在 src\store\modules\user.ts 里面
```ts
    /** 当前用户主题 */
    async getUserTheme() {
      return new Promise((resolve, reject) => {
        getThemeApi()
          .then(data => {
            if (data) {
              // this.SET_COLOR_THEME(data.homepageTheme);
              console.log("测试", data.homepageTheme);

              useDataThemeChange().setEpThemeColor(data.homepageTheme);

              resolve(data);
            }
          })
          .catch(error => {
            reject(error);
          });
      });
    }
```

在 src\layout\components\setting\index.vue
```vue
onBeforeMount(() => {
  // 获取当前用户主题
  console.log(useDataThemeChange()); // 不报错

  useUserStoreHook().getUserTheme(); // 报错 
  dataThemeChange();
  /* 初始化项目配置 */
  nextTick(() => {
    settings.greyVal &&
      document.querySelector("html")?.setAttribute("class", "html-grey");
    settings.weakVal &&
      document.querySelector("html")?.setAttribute("class", "html-weakness");
    settings.tabsVal && tagsChange();
  });
});
```

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [ ] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by HQ-YYK** [comment]
> 且更改后控制台 像死循环一样一直打印
![image](https://github.com/pure-admin/vue-pure-admin/assets/54365306/381e6e30-4e43-4219-807e-2f0c24bea390)

**Comment by xiaoxian521** [comment]
只解决平台bug
通过你的写法 应该是初始化问题 自己检查
