### ISSUE TITLE
push标签跳转之后tag标签没有高亮

### ISSUE THREAD

**Issue by 18626428291** [pure-admin/vue-pure-admin#695]
### 描述问题 (Describe the problem)

1.首先是在动态获取路由信息并生成菜单,目前是肯定有 'crm/create'路由的 
![image](https://github.com/pure-admin/vue-pure-admin/assets/42088184/4009311f-a321-40a3-8d90-e031520e2764)

2.通过handleTags方法push,
```js
 () => {
                tagStore.handleTags('push', {
                  path: '/crm/create',
                  name: 'CrmCreatePage',
                  meta: {
                    title: t('buttons.hsadd') + t('customer.customer'),
                    activePath: '/crm/list',
                    keepAlive: true,
                    showLink: true,
                    dynamicLevel: 3
                  }
                });
                router.push({ name: 'CrmCreatePage' });
              }
```
3.标签能够新增 但是不能高亮
![image](https://github.com/pure-admin/vue-pure-admin/assets/42088184/e56490cf-f251-4fcf-a70f-dcb7fa89c293)

### 如何复现该问题 (How to reproduce the problem)

是不是哪里配置了不对呢

### 操作系统和浏览器信息 (Operating system and browser information)

macos 13
chrome 

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
仔细参考 https://github.com/pure-admin/vue-pure-admin/tree/main/src/views/tabs
