### ISSUE TITLE
添加无 layout 的页面时怎么在新标签页中打开？

### ISSUE THREAD

**Issue by lqllife** [pure-admin/vue-pure-admin#696]
### 描述问题 (Describe the problem)

[添加无 layout 的页面](https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/#%E6%B7%BB%E5%8A%A0%E6%97%A0-layout-%E7%9A%84%E9%A1%B5%E9%9D%A2)
按文档中配置，可以打开无 layout 的页面，请教下如何配置才能在点击时在新标签页中打开。

### 如何复现该问题 (How to reproduce the problem)

😄

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
在浏览器新标签页打开？ 那你直接iframe啊

**Comment by xiaoxian521** [comment]
类似 
<img width="335" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/197cd176-dd29-453e-9415-3005953a88f8">
