### ISSUE TITLE
[标签页] 当标签页本身也在菜单中显示时，多个tab会同时高亮

### ISSUE THREAD

**Issue by lf-shaw** [pure-admin/vue-pure-admin#700]
### 描述问题 (Describe the problem)

在一些场景下，`tab` 页本身也是菜单的一部分，同时支持从别的页带参跳转至 `tab` 页。如果标签页本身就是菜单，就会出现多个标签同时高亮的情形。

![image](https://github.com/pure-admin/vue-pure-admin/assets/16026142/d490e4d3-d7b6-453c-83aa-46b0d1e2a731)

### 如何复现该问题 (How to reproduce the problem)

修改 `asyncRoutes.ts` 中的代码

```typescripts

    // query 传参模式
    {
      path: "/tabs/query-detail",
      name: "TabQueryDetail",
      meta: {
        // 不在menu菜单中显示
        showLink: true,      // 显示
        title: "tab-a",         // 给个标题
        activePath: "/tabs/index",
        roles: ["admin", "common"]
      }
    },

```

然后点击标签页操作中的 `query传参模式` 中的按钮。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
6 好好好 你这么用是吧 说实话有点搞笑 需求和用法不对应肯定不行啊
