### ISSUE TITLE
【细节优化】代码文本换行的实际的组织方式和文件配置.editorconfig冲突

### ISSUE THREAD

**Issue by 1717020** [pure-admin/vue-pure-admin#701]
### 描述问题 (Describe the problem)

首先明确，该问题不影响项目运行，只是一些细节问题。
开发者自行评估是否需要修改。

可以看到项目`.editorconfig`文件配置中文件结尾方式为`end_of_line = lf`，但是实际项目中是使用crlf的换行方式。

这导致使用`pnpm run lint -fix`指令批量修复代码格式化问题，会导致所有文件都被修改！

建议：修改`.editorconfig`配置文件，改为`end_of_line = crlf`，

### 如何复现该问题 (How to reproduce the problem)

直接运行pnpm run lint -fix指令，可以看到有353个文件修改

### 操作系统和浏览器信息 (Operating system and browser information)

win11 chrome

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
平台只是规定本项目的规范 如果你有自己的个性化风格 请自行修改

**Comment by 1717020** [comment]
> 平台只是规定本项目的规范 如果你有自己的个性化风格 请自行修改

你好，我的意思是该项目的.editorconfig规范和该项目本身代码冲突，这和我无关。当然，这只是个细节问题，感谢您的回复！

**Comment by xiaoxian521** [comment]
平台提供的有格式化 命令 请使用`pnpm lint`而不是`pnpm run lint -fix`

**Comment by cvpv** [comment]
> 平台提供的有格式化 命令 请使用`pnpm lint`而不是`pnpm run lint -fix`

执行`pnpm lint`也是一样的效果呀
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/2d2814ea-e452-4e50-a3eb-97efd926fae2)

**Comment by cvpv** [comment]
我在github的云vscode运行没有问题，可能该问题是使用git克隆工具或者其他什么下载工具造成自动修改了行尾标志成为了CRLF
