### ISSUE TITLE
移动端业务组件样式兼容问题

### ISSUE THREAD

**Issue by L1803703552** [pure-admin/vue-pure-admin#702]
### 描述问题 (Describe the problem)

1.“关于”页面的el-descriptions组件在进入移动端的时候显示不全
![image](https://github.com/pure-admin/vue-pure-admin/assets/53083703/fba37870-2e93-4423-9614-c5e52aae035a)
2.“首页”页面的部分el-card组件在进入手机横屏时不显示
![image](https://github.com/pure-admin/vue-pure-admin/assets/53083703/70476de4-c4d9-4c60-82cb-f1f38105e520)

### 如何复现该问题 (How to reproduce the problem)

1.浏览器进入响应式设计页面或者手机访问局域网地址，进入“关于”页面发现el-descriptions部分不显示
2.浏览器进入响应式设计页面或者手机横屏访问局域网地址，进入“首页”页面发现部分el-card组件不显示，建议给el-card加一个最小高度

### 操作系统和浏览器信息 (Operating system and browser information)

Chrome  116.0.5845.140 Windows x64

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [ ] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/570

**Comment by xiaoxian521** [comment]
多看以往issues Ok？
