### ISSUE TITLE
【iframe】iframe组件在隐藏顶部标签栏出现高度未占满的情况

### ISSUE THREAD

**Issue by cvpv** [pure-admin/vue-pure-admin#703]
### 描述问题 (Describe the problem)

iframe组件在隐藏顶部标签栏出现高度未占满的情况

![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/abc13ebb-3b7b-4f97-bc68-bf4cbefdd1f5)

原因是写死了height: calc(100vh - 88px);

应该动态判断是否有标签栏，来修改高度

### 如何复现该问题 (How to reproduce the problem)

直接运行官方项目，隐藏标签栏，然后打开IFRAME相关页面

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/pull/705)
