### ISSUE TITLE
使用pure-admin-thin时有时路由无法正常加载

### ISSUE THREAD

**Issue by yifancy** [pure-admin/vue-pure-admin#704]
### 描述问题 (Describe the problem)

在刷新之后打开一个页面是正常显示的，但是打开了多个之后却不能正常加载，连原本的第一个页面都无法正常显示
![c9eb7033a8bc4bda12a0e240d7341af](https://github.com/pure-admin/vue-pure-admin/assets/106078362/870ae21e-41f0-4185-8527-edaef472e588)
前几个也一样，然后控制台还会显示
[Vue Router warn]: No match found for location with path "/article/editArticle"这样的警告，动态路由表是严格按照格式来的
{
    "code": 200,
    "data": [
        {
            "id": 7,
            "create_time": "2023-08-13T12:19:29.528574+08:00",
            "update_time": "2023-08-13T12:19:29.536115+08:00",
            "is_deleted": false,
            "path": "/permission",
            "meta": {
                "title": "权限管理",
                "icon": "lollipop",
                "rank": 4,
                "showLink": true,
                "showParent": true,
                "roles": [
                    "admin",
                    "super"
                ],
                "auths": [
                    "student_btn",
                    "admin_btn",
                    "super_btn"
                ]
            },
            "children": [
                {
                    "id": 8,
                    "create_time": "2023-08-13T12:25:39.889510+08:00",
                    "update_time": "2023-08-13T12:25:39.897511+08:00",
                    "is_deleted": false,
                    "path": "/permission/page/index",
                    "name": "PermissionPage",
                    "meta": {
                        "title": "页面权限",
                        "icon": "",
                        "rank": 4,
                        "showLink": true,
                        "showParent": true,
                        "roles": [
                            "admin",
                            "super"
                        ],
                        "auths": [
                            "student_btn",
                            "admin_btn",
                            "super_btn"
                        ]
                    }
                },
                {
                    "id": 9,
                    "create_time": "2023-08-13T12:26:50.945025+08:00",
                    "update_time": "2023-08-13T12:26:50.946024+08:00",
                    "is_deleted": false,
                    "path": "/permission/button/index",
                    "name": "PermissionButton",
                    "meta": {
                        "title": "按钮权限",
                        "icon": "",
                        "rank": 4,
                        "showLink": true,
                        "showParent": true,
                        "roles": [
                            "admin",
                            "super"
                        ],
                        "auths": [
                            "student_btn",
                            "admin_btn",
                            "super_btn"
                        ]
                    }
                }
            ]
        },

### 如何复现该问题 (How to reproduce the problem)

我对接了后端，仅此而已

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 看文档 看issues

**Comment by xiaoxian521** [comment]
还有可以看看别的对接pure的后端 怎么用的
