### ISSUE TITLE
【nprogress】项目页面顶部进度条没有淡出动画

### ISSUE THREAD

**Issue by cvpv** [pure-admin/vue-pure-admin#707]
### 描述问题 (Describe the problem)

由于样式问题，路由切换的进度条没有淡出动画。

原版nprogress是有个结束后淡出动画，但是本项目没有。

查看样式发现是因为nprogress在淡出的时候，动态添加了transform。

这导致子元素的z-index失效，整个进度条此时开始就本网页主体完全遮挡（网页主体内容都有fixed布局且设置了z-index），所以在视觉上，整个进度条是突然消失的效果。

详见 #706 @

### 如何复现该问题 (How to reproduce the problem)

NProgress.configure中将 speed:略微调整为较大值。

然后手动在网页dom删除fixed-header

就可以很明显有无淡出动画的区别

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr
