### ISSUE TITLE
菜单栏消失问题

### ISSUE THREAD

**Issue by isekiro** [pure-admin/vue-pure-admin#708]
### 描述问题 (Describe the problem)

![screenshot-20230901-165144](https://github.com/pure-admin/vue-pure-admin/assets/50479425/81125576-e936-4d20-ba63-53f5c19b7fd5)

偶尔会出现菜单栏消失的问题，没办法复现，出问题时控制台和网络都没有报错，目前遇到2-3次，按 f5 刷新恢复

正常是如下显示：
![screenshot-20230901-170309](https://github.com/pure-admin/vue-pure-admin/assets/50479425/ed9256d0-ec0a-4c7a-865f-67c6186f41a2)

### 如何复现该问题 (How to reproduce the problem)

目前没办法复现

### 操作系统和浏览器信息 (Operating system and browser information)

开发端是 fedora ，浏览器是 windows 端 谷歌浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
得不到确定的问题就很毫无意义 提供具体复现步骤 大部分原因是自己的使用问题

**Comment by xiaoxian521** [comment]
不 可以很确定的告诉你是你自己用法问题 这种情况 从未出现过
