### ISSUE TITLE
PureTableBar 组件，列展示添加拖拽功能BUG

### ISSUE THREAD

**Issue by xiaoxiang0819** [pure-admin/vue-pure-admin#709]
### 描述问题 (Describe the problem)

页面开启 keepAlive 缓存后,只有一个页面可以进行列拖拽，另一个页面的列将无法拖动

### 如何复现该问题 (How to reproduce the problem)

开启页面keepAlive 缓存，然后在A页面进行列拖动，修改列顺序，在B页面将无法拖动PureTableBar 的列顺序

### 操作系统和浏览器信息 (Operating system and browser information)

win10,Chrome

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供复现视频

**Comment by XiaoQingShen** [comment]
页面缓存的时候，好像是sortablejs无法正常工作了。设置了动态id后，页面缓存及切换能正常使用。
![image](https://github.com/pure-admin/vue-pure-admin/assets/20433192/b55ac205-360b-4110-b039-6bb53b6317a3)
![image](https://github.com/pure-admin/vue-pure-admin/assets/20433192/ea7b29c3-7581-4b88-9c81-945ed6b257e5)
![image](https://github.com/pure-admin/vue-pure-admin/assets/20433192/862cb310-0178-4c31-adef-b56e3d893bc9)
