### ISSUE TITLE
在pure-table中无法实现在嵌套表头中渲染其他元素

### ISSUE THREAD

**Issue by Yanyeyeye** [pure-admin/vue-pure-admin#710]
### 描述问题 (Describe the problem)

嵌套表头中无法渲染其他元素，包括文字
![image](https://github.com/pure-admin/vue-pure-admin/assets/53677576/a7a220a0-0237-4a27-b9c3-c36549bbb0cf)
图片中可以看到城市和地址表头上还有一个总的表头没被渲染出来

### 如何复现该问题 (How to reproduce the problem)

columns.tsx
```typescript
import { ref } from "vue";
// 如果您不习惯tsx写法，可以传slot，然后在template里写
// 需是hooks写法（函数中有return），避免失去响应性
export function useColumns() {
  const search = ref("");
  const columns: TableColumnList = [
    {
      // headerRenderer中的内容不会被渲染
      headerRenderer: () => (
        <div>
          <span>姓名</span>
          <el-input
            v-model={search.value}
            size="small"
            clearable
            placeholder="Type to search"
          />
        </div>
      ),
      // 自定义表头
      children: [
        {
          label: "城市",
          prop: "city"
        },
        {
          label: "地址",
          prop: "address"
        }
      ]
    }
  ];

  return {
    columns
  };
}
``` 

index.vue
```typescript
<script setup lang="ts">
import { tableDataMore } from "./data";
import { useColumns } from "./columns";
import { PureTable } from "@pureadmin/table";
const { columns } = useColumns();
</script>

<template>
  <pure-table :data="tableDataMore" :columns="columns" alignWhole="center" />
</template>
```

data.ts为该框架提供的

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应仓库提问题 https://github.com/pure-admin/pure-admin-table/issues
