### ISSUE TITLE
router入口vue文件template中最外层有注释会导致页面无法渲染

### ISSUE THREAD

**Issue by TopYou** [pure-admin/vue-pure-admin#711]
### 描述问题 (Describe the problem)

// template最外面有注释会影响页面渲染
 \<template\>
 \<!-- 最外层容器 --\>
 \<div class=""\>
\</div\>
\</template\>
这样会导致无法渲染其他的页面

### 如何复现该问题 (How to reproduce the problem)

在各模块入口文件中template顶部加入注释，点击进入这个页面的然后切换至其他页面

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="608" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/e7c61886-303b-4345-82c2-1a1411254820">

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vue3-%E5%8D%95%E6%96%87%E4%BB%B6%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%E6%A0%B9%E6%A0%87%E7%AD%BE-%E4%BD%86%E6%98%AF%E5%B9%B3%E5%8F%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E8%BF%99%E4%B9%88%E7%94%A8%E5%91%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

**Comment by xiaoxian521** [comment]
刚上手的朋友 建议通读文档有问题多看有没有类似issues 基本都能解决问题

**Comment by TopYou** [comment]
谢谢大佬
