### ISSUE TITLE
动态路由匹配的页面 不会出现在标签栏

### ISSUE THREAD

**Issue by golanger123** [pure-admin/vue-pure-admin#712]
### 描述问题 (Describe the problem)

![图片](https://github.com/pure-admin/vue-pure-admin/assets/90915360/21169e6b-73ed-4570-b972-0514a6bf683f)
类似于这种动态匹配路由不会出现在标签栏，有什么办法解决吗

### 如何复现该问题 (How to reproduce the problem)

 页面中添加一个按钮，在点击时间处理函数中 根据传入的id  router push到 对应的路由
比如这种路径
 path: "/test/test405/:id"
 打开页面后 该页面不会出现在 标签栏

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多看demo
https://github.com/pure-admin/vue-pure-admin/tree/main/src/views/tabs
https://github.com/pure-admin/vue-pure-admin/blob/main/mock/asyncRoutes.ts#L188
