### ISSUE TITLE
reDialog的循环引用导致Cannot access 'reDialog' before initialization

### ISSUE THREAD

**Issue by wjr1116** [pure-admin/vue-pure-admin#713]
### 描述问题 (Describe the problem)

在app.vue 引用reDialog组件时，报错：Cannot access 'reDialog' before initialization，我看是reDialog/index.ts里import了index.vue，然后在index.vue里又引用了index.ts的方法导致的，但是直接用这个工程下载下来执行没有报错，这是少了什么东西吗？

### 如何复现该问题 (How to reproduce the problem)

我是之前版本的想升级一下，加了这个reDialog组件报错了

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [x] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 平台不都是引入好了吗 无需你多引入
