### ISSUE TITLE
当locale设置成en，国际化语言无效

### ISSUE THREAD

**Issue by RosyCloudsLee** [pure-admin/vue-pure-admin#714]
### 描述问题 (Describe the problem)

当public/serverConfig.json中的Locale 设为en，以及plugins/i18n.ts中的const i18n也进行了相应的修改，
假设 只在en.yaml设置 confs.title，没有设置zh-CN中设置confs.title,并且route中使用confs.title作为菜单，发现 不能正确显示confs.title对应的英文形式，只显示 “ confs.title”。当同时在zh-CN.yaml中设置了，就正常。

### 如何复现该问题 (How to reproduce the problem)

复现方式：任意的route的meta 的title 使用  一个 zh-CN中没有的key

问题cause： 发现route生成menu使用了transformI18n()
`  if (key && getObjectKeys(siphonI18n("zh-CN")).find(item => item === key)) {
    return i18n.global.t.call(i18n.global.locale, message);
  } else if (!key && Object.keys(siphonI18n("zh-CN")).includes(message)) {
    // 兼容非嵌套形式的国际化写法
    return i18n.global.t.call(i18n.global.locale, message);
  } else {
    return message;
  }`

将siphonI18n("zh-CN")-->siphonI18n("en")，就能解决问题

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by RosyCloudsLee** [comment]
目前在纠结 transformI18n() 中 siphonI18n("zh-CN") ，"zh-CN"是使用  serverConfig.json中Locale 还是  storage中的locale，哪一种更加合适呢？

**Comment by xiaoxian521** [comment]
你确定是最新版？

**Comment by xiaoxian521** [comment]
多看文档
<img width="1351" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/3057054a-33ab-46d9-899e-cdf11e0f9d0a">

**Comment by RosyCloudsLee** [comment]
清空缓存没有用哦，应该是transformI18n()的bug，` if (key && getObjectKeys(siphonI18n("zh-CN")).find(item => item === key)) { return i18n.global.t.call(i18n.global.locale, message); } else if (!key && Object.keys(siphonI18n("zh-CN")).includes(message)) { // 兼容非嵌套形式的国际化写法 return i18n.global.t.call(i18n.global.locale, message); } else { return message; }`
因为中文部分没有定义key，直接执行的最后一个分支，即return message, 我有debug看到结果

**Comment by RosyCloudsLee** [comment]
代码是从thin建立的，也实时同步main分支代码，确定是最新的。

**Comment by xiaoxian521** [comment]
嗯 有空我看下

**Comment by xiaoxian521** [comment]
我试了下 没问题 点击下图的清空缓存 有问题的话 可能是话你自己同步的问题 请拉起完整版代码进去验证
<img width="1676" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/44c46696-4696-419e-942d-f5f4bbbdad8b">

**Comment by RosyCloudsLee** [comment]
能在最新的main分支上复现问题的
<img width="442" alt="code_diff" src="https://github.com/pure-admin/vue-pure-admin/assets/43403309/34ff2ae2-8f03-489c-821f-cd2a2b1ed67f">
<img width="435" alt="abnormal" src="https://github.com/pure-admin/vue-pure-admin/assets/43403309/b762b85c-a6b9-4cba-ad63-84f6e133dc6f">
