### ISSUE TITLE
monorepo 多工程pnpm i 后找到不到sass

### ISSUE THREAD

**Issue by JSProxy** [pure-admin/vue-pure-admin#716]
### 描述问题 (Describe the problem)

.pureAdminTheme/originnal/saaa 生成失败 导致工程无法运 好像能生成一份，我有多个子工程，需要手动复制进子工程的node_modules 里面工程才能正常运行。

node_modules 这里把公用的库拉取  
packages
    app1
        node_modules
              缺失.pureAdminTheme/originnal/saaa 
    app2
        node_modules
              缺失.pureAdminTheme/originnal/saaa 
    app3
        node_modules
              缺失.pureAdminTheme/originnal/saaa 
scripts
package.js. 

### 如何复现该问题 (How to reproduce the problem)

monorepo 下 在根目录执行 pnpm.  i 后。子项目内的node_modules. 未生成.pureAdminTheme/originnal/saaa ，导致工程读取不到sass 尝试了在每个子工程单独。配置sass 库，一样读取不到。

### 操作系统和浏览器信息 (Operating system and browser information)

操作系统 mac。inter 处理器
浏览器 ,谷歌

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考 https://github.com/pure-admin/pure-admin-micro
找不到说明目录有问题 并非平台问题 或者自己重新安装
