### ISSUE TITLE
动态路由一级菜单是否不支持rank的排序

### ISSUE THREAD

**Issue by winson-young** [pure-admin/vue-pure-admin#717]
### 描述问题 (Describe the problem)

我尝试再动态路由下使用rank来进行**一级菜单**的**排序**时出现了以下问题：

当子机生成rank为2、系统管理为1时所呈现的排序状态：
![企业微信截图_20230907182346](https://github.com/pure-admin/vue-pure-admin/assets/16891237/7eb4cb56-cd80-48ae-a30c-474b799b7a93)

当子机生成rank为0、系统管理为1时所呈现的排序状态：
![企业微信截图_20230907182430](https://github.com/pure-admin/vue-pure-admin/assets/16891237/56db78d9-a9ac-4592-b992-e99e3d463cb2)

**可以看见一级菜单的排序与rank似乎没有任何关系，甚至和返回数据的自然顺序也是相反的**
最后我是去掉了rank属性返回解决了问题，如果动态路由中不带rank就可以按照自然返回的顺序来展示了
![企业微信截图_20230907183200](https://github.com/pure-admin/vue-pure-admin/assets/16891237/52d66b5d-befb-4f38-8a48-14c771404844)

### 如何复现该问题 (How to reproduce the problem)

动态路由返回时一级菜单附带rank属性

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多看文档 文档有的一律不回复 作者很忙
