### ISSUE TITLE
将完整版登录注册界面移植到thin中时页面切换会使组件消失

### ISSUE THREAD

**Issue by Wanan813** [pure-admin/vue-pure-admin#719]
### 描述问题 (Describe the problem)

找不到问题所在，求解答
这是登录
![image](https://github.com/pure-admin/vue-pure-admin/assets/60309095/1967a7d8-34be-450d-a5bd-0a3e5435541c)
点击注册或忘记密码
![image](https://github.com/pure-admin/vue-pure-admin/assets/60309095/208c6a85-faba-4b12-af06-044efb5fa549)

在user.ts中添加输出
![image](https://github.com/pure-admin/vue-pure-admin/assets/60309095/3983ef42-f615-48d9-9760-aa4a0cc587f0)
![image](https://github.com/pure-admin/vue-pure-admin/assets/60309095/b82b17fb-4cbd-49fc-a343-910e600bbcb9)

### 如何复现该问题 (How to reproduce the problem)

将完整版登录注册界面移植到thin中时，只要登录注册界面
![image](https://github.com/pure-admin/vue-pure-admin/assets/60309095/cb11e5e5-67dc-4aec-aad5-5ae682a5ff8f)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
这种问题·均需要自己参考代码
平台只解决确定的bug

**Comment by Wanan813** [comment]
被自己蠢到了
