### ISSUE TITLE
页面切换导致页面空白，另外作者如果繁忙能否提供交流群方式，文档上面的群是假群

### ISSUE THREAD

**Issue by a2643979238** [pure-admin/vue-pure-admin#724]
### 描述问题 (Describe the problem)

![WechatIMG10124](https://github.com/pure-admin/vue-pure-admin/assets/59910855/9cb6fb12-bef2-49bf-b467-fa6d64ae1ebb)
两个红箭头的页面是写死静态数据，黄箭头是对接了接口数据的页面，两个红箭头页面互相切换没问题，但只要切换到黄箭头对接了接口的页面，这时数据正常渲染。当从黄箭头页面切换到其他页面时，所有页面变得全空白不展示任何数据。

控制台没有任何报错，没有任何警告，所有功能一切正常，就只是页面全变成空白

### 如何复现该问题 (How to reproduce the problem)

https://github.com/pure-admin/vue-pure-admin/assets/59910855/54443b87-342a-430c-b922-e9765cfbe181

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多看以往issues 目前不提供任何群

**Comment by a2643979238** [comment]
总共18页的issues我都看完了，和我出现相同类似的问题有4个，你的回答均是看文档，看issues，我想问去哪里看？
