### ISSUE TITLE
登陆后续无获取路由响应

### ISSUE THREAD

**Issue by lee-stars** [pure-admin/vue-pure-admin#728]
### 描述问题 (Describe the problem)

之前项目偶尔发生一次，换一个电脑就行了，这次也是，换电脑就行了，但是每次这样比较麻烦，麻烦大佬排除一下是否是BUG，问题如下：

拉取最新的代码，正常写业务，运行```pnpm run dev```之后，访问8848端口进入登陆页面，输入错误登录信息，提示登陆失败，没问题。

输入正确的登录信息，控制台网络返回登陆成功的信息，页面就再也没有跳转，只执行了登录操作，没有执行asyncGetRoute这个网络请求，控制台应用程序里面也成功的写入了userInfo字段，刷新页面之后直接进入了welcome页面，右上角的名称变成了登录名称，但是左侧的菜单树并没有出来，控制台网络请求也没有获取路由的操作。

### 如何复现该问题 (How to reproduce the problem)

这个现象不是每次都发生，但也不知道啥时候就发生了。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by zzx1314** [comment]
尊嘟假嘟，为啥换电脑就可以呀，控制台有报错吗

**Comment by cvpv** [comment]
`如何复现该问题 (How to reproduce the problem)
这个现象不是每次都发生，但也不知道啥时候就发生了。`
无法提供复现步骤，就别浪费时间了
