### ISSUE TITLE
【样式异常】项目内的reset.scss 中的label {   font-weight: 700; } 会造成element plus 表单样式异常

### ISSUE THREAD

**Issue by cvpv** [pure-admin/vue-pure-admin#729]
### 描述问题 (Describe the problem)

rest.scss 中的label {   font-weight: 700; } 会造成表单的label部分意外加粗！但是由于element plus的设计，部分表单label会使用div样式，这就造成表单label样式不统一
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/45a8fa8e-794c-4ddb-aff2-64ba2b5af150)
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/847db034-391f-4d95-a0d1-3adadc77c588)

### 如何复现该问题 (How to reproduce the problem)

从element plus 复制一个demo 表单 在 精简版即可复现

我注意到，在完整版项目，强制写了.el-form-item__label ，如果开发人员想这样做来，修复这个问题。希望能在精简版也修复下

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/commit/b674db0a0601bb1c37ebba3c70ca2ad8468b1dc7
