### ISSUE TITLE
校验失败、登录请求异常，都将导致loading状态持续

### ISSUE THREAD

**Issue by ruixiaozi** [pure-admin/vue-pure-admin#731]
### 描述问题 (Describe the problem)

校验失败、登录请求异常，都将导致loading状态持续

### 如何复现该问题 (How to reproduce the problem)

校验失败、登录请求异常，都将导致loading状态持续

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by ruixiaozi** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/8970166/4959c5ee-3dac-4e8e-9212-c5b8a17b8129)

**Comment by ruixiaozi** [comment]
应该使用trycatch块做表单校验和请求处理。
减少嵌套层级，并能够捕获处理所有错误，给予正确的反馈

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/73b5d3ec41705ae36e154dd21a8bdac61679a590)
