### ISSUE TITLE
重复的find，造成性能浪费

### ISSUE THREAD

**Issue by ruixiaozi** [pure-admin/vue-pure-admin#732]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/8970166/6e832905-7439-4de3-9147-1c42b985da62)

代码位置：‘src/router/utils.ts’

参考vue-router官方文档：https://router.vuejs.org/zh/api/interfaces/Router.html#Methods-addRoute
![image](https://github.com/pure-admin/vue-pure-admin/assets/8970166/51647ddf-54a5-4134-a91e-dbffb6541f5c)

### 如何复现该问题 (How to reproduce the problem)

代码逻辑

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by ruixiaozi** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/8970166/d4d4b2f9-29ad-47cb-b1ac-c4873a5ee116)
if作为守卫语句，后面的else属于是冗余代码了。增加了代码的嵌套深度

**Comment by ruixiaozi** [comment]
.map方法也应该换成.foreach方法，这里生成了不必要的副作用结果。

**Comment by xiaoxian521** [comment]
嘿，请提供详细的前后耗时耗时截图来论证你的观点 而不是抽象的认为这会造成性能浪费！

**Comment by xiaoxian521** [comment]
> ![image](https://user-images.githubusercontent.com/8970166/267717527-d4d4b2f9-29ad-47cb-b1ac-c4873a5ee116.png) if作为守卫语句，后面的else属于是冗余代码了。增加了代码的嵌套深度

从这里可以看出 你并没有进行测试 不要一味的以你的理论知识去判断代码 多去测试
