### ISSUE TITLE
i18n咨询

### ISSUE THREAD

**Issue by jack20211101** [pure-admin/vue-pure-admin#734]
### 描述问题 (Describe the problem)

**我定义了一条带变量的提示信息：**
![2](https://github.com/pure-admin/vue-pure-admin/assets/96187352/faef31fa-3e41-4e0c-8479-b81b180da2d5)

**平台提供的 transformI18n() 方法暂不支持这种写法：** 
![3](https://github.com/pure-admin/vue-pure-admin/assets/96187352/fa716c20-de87-4aa5-999a-d731bb6aa8a2)

**这是Vue I18n的方法调用：** 可这种方式只允许在setup下使用
![1](https://github.com/pure-admin/vue-pure-admin/assets/96187352/da23ee42-6bd3-4f05-9db1-cbbccea645e4)

### 如何复现该问题 (How to reproduce the problem)

Vue I18n自带的方法局限性，ts无法使用，目前通过简单的替换暂时解决，后续是否会考虑支持

### 操作系统和浏览器信息 (Operating system and browser information)

- Windows 11
- Chrome 114

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
只允许在setup下使用是规范

**Comment by xiaoxian521** [comment]
`transformI18n`只支持传一个参数

**Comment by jack20211101** [comment]
> `transformI18n`只支持传一个参数
[看到了这个回答，](https://stackoverflow.com/questions/57049471/problem-to-use-vuei18n-outside-a-component/66695008#66695008)
进行了一些改造，前端小白不知道对不对，但是能实现功能

![image](https://github.com/pure-admin/vue-pure-admin/assets/96187352/4e8aa0de-6045-4e12-9c14-d77a7117cbdd)
