### ISSUE TITLE
平台采用只有静态路由模式时，按文档教程修改后，首次登录拿不到权限

### ISSUE THREAD

**Issue by shuiche-it** [pure-admin/vue-pure-admin#737]
## 前言
平台中使用了只有静态路由模式，改动是按照

[https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/#%E5%A6%82%E4%BD%95%E5%8F%AA%E8%A6%81%E9%9D%99%E6%80%81%E8%B7%AF%E7%94%B1](https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/#%E5%A6%82%E4%BD%95%E5%8F%AA%E8%A6%81%E9%9D%99%E6%80%81%E8%B7%AF%E7%94%B1)

修改的
## 首次登录拿不到权限

首次登录时，拿不到权限信息， 具体原因是：先组装了路由，其次才设置了角色。在组装时会用到权限

## 解决办法：

在登录的函数中，将 `setToken({...})` 放到 `usePermissionStoreHook().handleWholeMenus([]); ` 前面就可以了

## 截图
改正后的截图：

<img width="852" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/10776422/ac04b99b-7662-4737-86a0-86e31ac1a428">

官网文档教程：

![image](https://github.com/pure-admin/vue-pure-admin/assets/10776422/e504142b-f91b-4a1f-aa86-48fafa424603)

### 如何复现该问题 (How to reproduce the problem)

直接下载 精简版代码，按照文档修改为静态路由模式，其中添加了几个示例路由。首次登录时拿不到权限，只有默认菜单，需要强制刷新页面后，才能出现权限菜单

### 操作系统和浏览器信息 (Operating system and browser information)

MacOS 12
Chrome 116

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎在文档中进行修改 https://github.com/pure-admin/pure-admin-doc

**Comment by shuiche-it** [comment]
已经提交了一个PR。
