### ISSUE TITLE
【路由切换bug】route.mate只设置transition.name会造成页面切换的意外卡顿

### ISSUE THREAD

**Issue by cvpv** [pure-admin/vue-pure-admin#739]
### 描述问题 (Describe the problem)

检查src\layout\components\appMain.vue代码，发现

一旦设置了transition.name
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/1101a743-f6d1-495c-90e0-9a5bcff4e453)
就会在进入和离开时候增加class animate__animated

当我们没有设置任何animate时候，也会出现强制一秒等待
```
.animate__animated {
    -webkit-animation-duration: 1s;
    animation-duration: 1s;
    -webkit-animation-duration: var(--animate-duration);
    animation-duration: var(--animate-duration);
    -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
}
```

### 如何复现该问题 (How to reproduce the problem)

将路由mate增加下面这个属性
```
  transition: {
          name: "fade"
        }

```

发现并没有淡入淡出效果。

当然，你可以直接访问官方项目的“/components/map” ，你会发现页面是很突兀的突然显示出来，在此之前有1秒的空屏！
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/d66de453-89f4-45d3-b0f3-2c925fbfdb7b)
暂时注释上述代码后，会发现页面加载变快了（当然由于地图组件自身加载速度的影响，无法显著看到fade的明显变化）

或者在官方项目其他任何一个页面修改：
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/3359b2ee-5ddb-42eb-bff3-4cf2b66b3813)

，只添加`  name: "fade"`。

在注释和解开下面注释（src\layout\components\appMain.vue），会有显著变化。
![image](https://github.com/pure-admin/vue-pure-admin/assets/84720311/b4299dbb-6de0-4dec-815c-9408eeb4bfaf)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by cvpv** [comment]
对了。Transition组件中，一旦enterActiveClass和leaveActiveClass存在，则name无论写什么值，都无效！

**Comment by xiaoxian521** [comment]
嗯 从你的描述看是这样的 你有试过`enterActiveClass`和`leaveActiveClass`赋空值会影响`name`吗

**Comment by cvpv** [comment]
> 嗯 从你的描述看是这样的 你有试过`enterActiveClass`和`leaveActiveClass`赋空值会影响`name`吗

没有用。
```javascript
  transitions.value(this.route) &&
          `animate__animated ${this.route.meta.transition.enterTransition}`
```
一旦填写了route.meta.transition （非null | '' | NaN | 0 | undefined），则始终返回右边的值。

我测试过，`enterActiveClass`和`leaveActiveClass`为空字符串也会导致name失效

我这边是这样修复的，

```javascript
   {
        name: transitions.value(this.route) && this.route.meta.transition.enterTransition ? 'pure-classes-transition' : (transitions.value(this.route) && this.route.meta.transition.name) || 'fade-transform',
        // enterActiveClass: transitions.value(this.route) && `animate__animated ${this.route.meta.transition.enterTransition}`,
        // leaveActiveClass: transitions.value(this.route) && `animate__animated ${this.route.meta.transition.leaveTransition}`,
        // todo 修复 Transition bug
        enterActiveClass: transitions.value(this.route) && (this.route.meta.transition.enterTransition ? `animate__animated ${this.route.meta.transition.enterTransition}` : undefined),
        leaveActiveClass: transitions.value(this.route) && (this.route.meta.transition.leaveTransition ? `animate__animated ${this.route.meta.transition.leaveTransition}` : undefined),
        mode: 'out-in',
        appear: true,
      },
```

没有能力PR  ,希望作者或者大佬能修复下

**Comment by xiaoxian521** [comment]
感谢反馈！
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/984bddbde26563011a2d457b2dcfb9da801463c5)
