### ISSUE TITLE
数字动画组件Safari兼容问题

### ISSUE THREAD

**Issue by L1803703552** [pure-admin/vue-pure-admin#740]
### 描述问题 (Describe the problem)

数字动画组件在Safari上不会停止滚动
<img width="1319" alt="截屏2023-09-18 16 22 44" src="https://github.com/pure-admin/vue-pure-admin/assets/53083703/8a0171ae-ebfb-400f-81cf-baec849c74c1">
代码报错位置在 **@/components/ReCountTo/rebound/index.tsx** 第24-33行
```
const ulRef = ref();
const timer = ref(null);
onBeforeMount(() => {
  const ua = navigator.userAgent.toLowerCase();
  const testUA = regexp => regexp.test(ua);
  const isSafari = testUA(/safari/g) && !testUA(/chrome/g);

  // Safari浏览器的兼容代码
  isSafari &&
    (timer.value = setTimeout(() => {
      ulRef.value.setAttribute(
        "style",
        `
    animation: none;
    transform: translateY(calc(var(--i) * -9.09%))
  `
      );
    }, props.delay * 1000));
});
return () => (
      <>
        <div
          class="scroll-num"
          style={{ "--i": props.i, "--delay": props.delay }}
        >
          <ul ref="ulRef" style={{ fontSize: "32px" }}>
            <li>0</li>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
```
目前已知ulRef获取不到DOM节点，ulRef.value为undefined

### 如何复现该问题 (How to reproduce the problem)

项目启动后用Safari浏览器打开页面，或使用chrome响应式模拟iPhone或iPad

### 操作系统和浏览器信息 (Operating system and browser information)

Safari浏览器 版本16.6 (18615.3.12.11.2)
macOS 13.5.2 (22G91)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [ ] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
不考虑 Safari 欢迎pr

**Comment by cvpv** [comment]
Safari做为主流浏览器应该需要考虑
