### ISSUE TITLE
精简版在创建三层菜单点击出现404

### ISSUE THREAD

**Issue by awhlmycn** [pure-admin/vue-pure-admin#743]
### 描述问题 (Describe the problem)

在精简版的代码下，弄一个三级菜单，
主题模式，选择《顶部模式》 没有问题
主题模式，切换到《混合模式》 就会出现404

### 如何复现该问题 (How to reproduce the problem)

// 最简代码，也就是这些字段必须有
export default {
    path: "/market",
    meta: {
        icon: "informationLine",
        title: "市场",
        // showLink: false,
        rank: 9
    },
    children: [
        {
            path: "/market/lp",
            meta: {
                title: "LP"
            },
            children : [
                {
                    path: "/market/lp/lpfund",
                    name: "lpfund",
                    component: () => import("@/views/market/lpfund.vue"),
                    meta: {
                        title: "投资基金"
                    },
                },
                {
                    path: "/market/lp/lpproject",
                    name: "lpproject",
                    component: () => import("@/views/market/lpproject.vue"),
                    meta: {
                        title: "直投项目"
                    },
                }
            ]
        },
    ]
} as RouteConfigsTable;

### 操作系统和浏览器信息 (Operating system and browser information)

1.操作系统：windows
2：浏览器：谷歌

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考 https://github.com/pure-admin/vue-pure-admin/tree/main/src/views/nested
