### ISSUE TITLE
左边菜单栏中添加退出登录按钮

### ISSUE THREAD

**Issue by lovelypp777** [pure-admin/vue-pure-admin#744]
### 描述问题 (Describe the problem)

请问如何在左侧栏中添加退出登录按钮。
用户点击后，弹出确认对话框，确认后退出登录

谢谢！

### 如何复现该问题 (How to reproduce the problem)

新需求

### 操作系统和浏览器信息 (Operating system and browser information)

windows 11

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
这属于业务代码 自行解决哈
