### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by huajiujiang** [pure-admin/vue-pure-admin#746]
### 描述问题 (Describe the problem)

切换路由菜单，页面内容空白，要重新刷新才会立马显示内容

### 如何复现该问题 (How to reproduce the problem)

正常写了一个组件，放在路由页面去显示，第一次加载能显示，后续切换路由，再切换回来，就为空白，需要刷新才会显示

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="578" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/1736c3f4-ab73-4819-8aa3-8e9b86a725f0">
