### ISSUE TITLE
建议添加swagger相关页面

### ISSUE THREAD

**Issue by lovelypp777** [pure-admin/vue-pure-admin#751]
### 描述问题 (Describe the problem)

建议添加swagger相关页面

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/pure-admin-backend/blob/main/src/config/index.ts#L16
