### ISSUE TITLE
路由配置中不填rank(rank不能为0)会引发问题

### ISSUE THREAD

**Issue by gentingincubus** [pure-admin/vue-pure-admin#752]
### 描述问题 (Describe the problem)

配置动态路由时，把路由的配置都填上，rank偷懒填0，比如我的路径为/department/staff/index,结果框架往department文件夹找第一个文件夹的第一个vue文件，就把他放上去了（无论这个文件夹是否为department下的staff文件夹，只找第一个），类似的，所有path为/department/xxx/xx的路由 只要rank为0， 都会找这个第一个文件夹的第一个vue文件 把他渲染上去，甚至会找staff/components/xxx.vue（第一个vue）

### 如何复现该问题 (How to reproduce the problem)

配置路由时不填rank或rank等于0, 稳定复现 并非偶然

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多看以往issues
<img width="572" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/5e9f19db-7c62-43c4-8c38-9d50c3d6656e">

**Comment by xiaoxian521** [comment]
<img width="1162" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/6bf14aed-eecb-476f-ba12-e2071aec75bb">
