### ISSUE TITLE
封装的ReDialog打开有动画效果，关闭没有

### ISSUE THREAD

**Issue by yanghuoji** [pure-admin/vue-pure-admin#753]
### 描述问题 (Describe the problem)

封装的ReDialog打开有动画效果，关闭的动画没有。基于Element封装的，但是Element官网的示例又有关闭的动画

### 如何复现该问题 (How to reproduce the problem)

演示的各种demo均没有动画，https://yiming_chang.gitee.io/vue-pure-admin/#/components/dialog

在Element的官网中看的demo，https://element-plus.org/zh-CN/component/dialog.html

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
[Duplicate](https://github.com/pure-admin/vue-pure-admin/issues/622)

**Comment by xiaoxian521** [comment]
[已修复](https://github.com/pure-admin/vue-pure-admin/commit/4bbbd56a2a83fac7890032f46a2fcb69d934d1b0)
