### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by XieB** [pure-admin/vue-pure-admin#755]
### 描述问题 (Describe the problem)

手动改变窗口大小，内存会一直增加

### 如何复现该问题 (How to reproduce the problem)

登录后，打开浏览器控制台，改变窗口大小。

### 操作系统和浏览器信息 (Operating system and browser information)

win10
chrome 117

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
先了解啥才叫内存溢出 再列出具体细节视频
