### ISSUE TITLE
页面路由为叶子节点时，设置showLink: false，刷新页面，页面tag不见了

### ISSUE THREAD

**Issue by shiny1217** [pure-admin/vue-pure-admin#757]
### 描述问题 (Describe the problem)

页面路由为叶子节点时，设置showLink: false，刷新页面，页面tag不见了

### 如何复现该问题 (How to reproduce the problem)

src\router\modules\nested.ts
 children: [
            {
              path: "/nested/menu1/menu1-2/menu1-2-1",
              component: () =>
                import("@/views/nested/menu1/menu1-2/menu1-2-1/index.vue"),
              name: "Menu1-2-1",
              meta: {
                title: $t("menus.hsmenu1-2-1"),
                keepAlive: true,
                showLink: false
              }
            },

src\views\nested\menu1\menu1-1\index.vue
 <router-link to="/nested/menu1/menu1-2/menu1-2-1">aaa</router-link>

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
`showLink: false`
不会出现在菜单 也不会出现在标签页 多看文档
