### ISSUE TITLE
Eslint检查问题

### ISSUE THREAD

**Issue by carpONE** [pure-admin/vue-pure-admin#759]
### 描述问题 (Describe the problem)

如何解决defineOptions爆红问题
![image](https://github.com/pure-admin/vue-pure-admin/assets/81232339/4fe09dd1-9b06-49be-b2d1-a9682738ce35)

### 如何复现该问题 (How to reproduce the problem)

默认就会爆红

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
安装文档推荐的vscode插件 这不是`Eslint` 是`typescript`
