### ISSUE TITLE
用户手动在浏览器`Application`面板中清除系统相关缓存，导致页面切换时失效，应重定向到登录页

### ISSUE THREAD

**Issue by JarvisChao** [pure-admin/vue-pure-admin#761]
### 描述问题 (Describe the problem)

目前測試下來，refresh 失效或錯誤只會停留在原地，沒有做 login 導向
另外，平台好像沒有設定網址列 redirect，例如：未登入狀態貼上內頁網址，導向 login 頁沒有紀錄剛剛貼上的網址，登入後只會往 welcome 去，這也會間接影響 refresh 失效 -> 導向 login -> 登入後不會是剛剛 refresh 失效那頁，對使用體驗可能會比較差一點

### 如何复现该问题 (How to reproduce the problem)

如問題描述

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
列出具体操作视频 看不懂你的描述啥

**Comment by JarvisChao** [comment]
> 列出具体操作视频 看不懂你的描述啥

refresh 失效模擬，最後重新整理整個變空白
https://github.com/pure-admin/vue-pure-admin/assets/38325453/783dc530-debb-4410-b642-3dc1b00b1220

login 只會導至 welcome
https://github.com/pure-admin/vue-pure-admin/assets/38325453/ad1034e3-384d-40a4-a12c-d50a45b62f6e

**Comment by xiaoxian521** [comment]
第一个视频操作确实出乎我的意料 哈哈 
第二个视频的话，因为`welcome`是首页 所以默认会跳转到首页，当然这是可以根据自己业务调整的哈，调整下图箭头所指代码即可
<img width="1283" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/14fce43b-0f70-41c4-86d9-0bcf293f93d1">

**Comment by xiaoxian521** [comment]
将会在`5.0.0`版本修复
<img width="868" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/e29a0c2e-30a7-4906-a720-9ad1546ceea9">

**Comment by xiaoxian521** [comment]
经过考虑 这个操作是比较极端且用户一般不会此操作 所以平台不打算处理这里
当然 https://github.com/pure-admin/vue-pure-admin/pull/762 该`pr`也可以给后续有此需求的做参考 谢谢
