### ISSUE TITLE
暗黑模式下地图组件页面样式错误

### ISSUE THREAD

**Issue by heyingjie** [pure-admin/vue-pure-admin#766]
### 描述问题 (Describe the problem)

在暗黑模式下，选项菜单还有marker上的提示是全白的，文字看不见

### 如何复现该问题 (How to reproduce the problem)

进入暗黑模式，打开地图组件界面

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr
