### ISSUE TITLE
关于git commit 关闭代码检验问题和动态二级菜单问题

### ISSUE THREAD

**Issue by DankeBIBI** [pure-admin/vue-pure-admin#768]
### 描述问题 (Describe the problem)

我想git commit 关闭代码检验问题，
还有动态多级菜单，我的动态菜单有三级，我现在想在点击二级菜单也跳转页面（动态二级菜单也配置页面了）该如何操作呀？谢谢

### 如何复现该问题 (How to reproduce the problem)

如上所述

### 操作系统和浏览器信息 (Operating system and browser information)

如上所述

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
文档都有 issues都有相同的 自己动手 丰衣足食
最近忙于发布`5.0.0`版本 非`bug`一律暂不解决 文档可以解决百分之99的问题
