### ISSUE TITLE
克隆vue-pure-admin完整版的代码,安装并运行报错: Uncaught SyntaxError: Unexpected identifier 'All'   en.yaml:11 

### ISSUE THREAD

**Issue by SGWorldline** [pure-admin/vue-pure-admin#770]
### 描述问题 (Describe the problem)

克隆vue-pure-admin完整版的代码,安装并运行报错: 
Uncaught SyntaxError: Unexpected identifier 'All'   en.yaml:11 

### 如何复现该问题 (How to reproduce the problem)

克隆vue-pure-admin完整版的代码,安装并运行报错: 
Uncaught SyntaxError: Unexpected identifier 'All'   en.yaml:11 

### 操作系统和浏览器信息 (Operating system and browser information)

谷歌浏览器 版本 118.0.5993.89（正式版本） （64 位）
windows11系统
node:18.14.0
pnpm:8.6.9

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
平台没有en.yaml文件 自行检查
