### ISSUE TITLE
导航栏为顶部模式时，鼠标放在功能菜单上， 子菜单会一直闪烁

### ISSUE THREAD

**Issue by wgk-421** [pure-admin/vue-pure-admin#771]
### 描述问题 (Describe the problem)

导航栏为顶部模式时，鼠标放在功能菜单上， 子菜单会一直闪烁
![image](https://github.com/pure-admin/vue-pure-admin/assets/57676075/6b7c210f-74e9-4f9b-abfc-ac5662d2d389)

### 如何复现该问题 (How to reproduce the problem)

导航栏为顶部模式时，鼠标放在功能菜单上， 子菜单会一直闪烁

### 操作系统和浏览器信息 (Operating system and browser information)

window   谷歌

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
非平台问题
