### ISSUE TITLE
内嵌 iframe时 标签页右键zIndex问题

### ISSUE THREAD

**Issue by lotherli** [pure-admin/vue-pure-admin#772]
### 描述问题 (Describe the problem)

![4531698308966_ pic](https://github.com/pure-admin/vue-pure-admin/assets/36142693/227219ab-2817-44fb-bd33-deae2bc9b221)

https://github.com/pure-admin/vue-pure-admin/blob/a0c56e99b7d81f1397220ebda40b0f83fb778713/src/layout/components/appMain.vue#L158-L163
增加  z-index:1 或者z-index:0

### 如何复现该问题 (How to reproduce the problem)

![WeChat69bd553c4275ef9a35ab26923a89ed7c](https://github.com/pure-admin/vue-pure-admin/assets/36142693/6c64ae0d-8ec7-4b91-ade7-1b895e44aae3)
``
选择其中一个菜单，然后右键点击tag标签页，
``

### 操作系统和浏览器信息 (Operating system and browser information)

![WeChatb0319220f8e2495870282b0232fa3373](https://github.com/pure-admin/vue-pure-admin/assets/36142693/24f8bd09-d17a-4f45-9ab1-cef95e821fed)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
小优化 欢迎pr

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/02c2e4fc4b09f01912ec24fea0608251ed034b5a)

**Comment by itcuihao** [comment]
借楼问下，例如iframe 我不想在 `router/modules/a.ts`中修改跳转，我想在`views/a/index.vue`中实现跳转，目的是为了可以携带参数，通过 iframe传参，是否有 demo可以参考 @xiaoxian521
