### ISSUE TITLE
标签操作里的打开详情页后面包屑点击有问题

### ISSUE THREAD

**Issue by caim18340** [pure-admin/vue-pure-admin#773]
### 描述问题 (Describe the problem)

在线项目里的标签页操作菜单打开
然后随便点击下面的打开某某详情页
然后再去点击上方面包屑的某某详情页
就会发现有问题，他又打开了一个详情页
正确的应该是在当前详情页不动

### 如何复现该问题 (How to reproduce the problem)

在线项目里的标签页操作菜单打开
然后随便点击下面的打开某某详情页
然后再去点击上方面包屑的某某详情页
就会发现有问题，他又打开了一个详情页
正确的应该是在当前详情页不动

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 首先你这个都复现不了 提供具体视频
其次参标签页操作的代码
![image](https://github.com/pure-admin/vue-pure-admin/assets/44761321/39f9e237-ca61-4ecc-b69b-2d973e12fedf)
