### ISSUE TITLE
详情页的点击面包屑有问题

### ISSUE THREAD

**Issue by caim18340** [pure-admin/vue-pure-admin#776]
### 描述问题 (Describe the problem)

完整版演示里的标签页操作页面点击详情页后，再点击上方的详情页面包屑，会打开一个错误的页面。这是操作具体的视频压缩包链接https://wwma.lanzouj.com/ioHv01cz13pi

### 如何复现该问题 (How to reproduce the problem)

这是操作具体的视频压缩包链接https://wwma.lanzouj.com/ioHv01cz13pi

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
直接把视频拖到issues里就行了 压缩包的话 彼此都麻烦
这的确是个bug 谢谢反馈 等有空修复

**Comment by caim18340** [comment]
最新的精简版怎么同步一下完整版修复的问题

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/29f83b491123f4146c67ad0f9271cf78bb91a4a0)
