### ISSUE TITLE
演示系统 菜单加载不出来

### ISSUE THREAD

**Issue by yangzxzx** [pure-admin/vue-pure-admin#777]
### 描述问题 (Describe the problem)

演示系统 菜单加载不出来，一直转圈

### 如何复现该问题 (How to reproduce the problem)

演示系统 https://yiming_chang.gitee.io/vue-pure-admin/#/  直接登录

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
刚开始用 多看文档 文档能解决百分之97的问题

**Comment by xiaoxian521** [comment]
不好意思 误会你的意思了 可能是gitee同步那边出了点小问题 已经修复 谢谢反馈🙏
