### ISSUE TITLE
路由生成有问题

### ISSUE THREAD

**Issue by wangjinbo666** [pure-admin/vue-pure-admin#779]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/45446805/5bd83cc5-2956-4458-99d7-d9c3592846c4)
左侧菜单加载不出来

### 如何复现该问题 (How to reproduce the problem)

直接登录就行

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
线上看不了就拉倒本地 线上用的gitee 可能某些时间不稳定
