### ISSUE TITLE
fixedHeader 下 el-backtop失效

### ISSUE THREAD

**Issue by RosyCloudsLee** [pure-admin/vue-pure-admin#782]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/43403309/3ce6b26f-42c2-497a-824c-227899332f97)
上图代码在feat: 添加页脚引入的，导致在fixedHeader 下 el-backtop失效（滚动条的样式也发生改变），去掉wrap-style和view-style，能看到 el-backtop，滚动条样式恢复。

### 如何复现该问题 (How to reproduce the problem)

在线demo    [卡片列表页](https://yiming_chang.gitee.io/vue-pure-admin/#/list/card) 选36条/页，能看到现象

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
谢谢反馈 该问题会在 v5.0.0 版本前修复

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/a8b9683a5f0a0d0127426408014a7873042cd1f7)
