### ISSUE TITLE
不需要安装sass-loader依赖

### ISSUE THREAD

**Issue by echofly** [pure-admin/vue-pure-admin#785]
### 描述问题 (Describe the problem)

vite项目中sass是被默认支持的，只需要安装sass，不用安装sass-loader
![image](https://github.com/pure-admin/vue-pure-admin/assets/36875450/3f441f2b-9952-423d-bd37-33aeb6aef18c)

### 如何复现该问题 (How to reproduce the problem)

如上

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
嗯 你命名规范就不需要安装
https://github.com/pure-admin/vue-pure-admin/commit/271b953081e2190770998313089f55a43cbe4a4d
