### ISSUE TITLE
VITE_COMPRESSION gzip压缩后，index.html里关联的 链接，没有修改为.gz

### ISSUE THREAD

**Issue by foreverhot1019** [pure-admin/vue-pure-admin#788]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/19644278/cc9d9690-470d-4ae0-95cd-6b00a9044926)
![image](https://github.com/pure-admin/vue-pure-admin/assets/19644278/3de6ecca-8aed-42ad-ab79-5bfbee3b84be)

所有文件资源都已经 打包为 .gz格式，但 index.htnl里面的文件链接便没有修改，导致 后端不好处理请求。

### 如何复现该问题 (How to reproduce the problem)

build 时，开启 VITE_COMPRESSION = "gzip-clear"，绑到静态文件服务器。

### 操作系统和浏览器信息 (Operating system and browser information)

win10 64位 .net Core 7.0

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看 https://www.bilibili.com/video/BV1kg411v7QT/?vd_source=5a992808de6229d78e7810536c5f9ab3
这里演示过gzip

**Comment by xiaoxian521** [comment]
哦 感觉你看这里就能解决 https://yiming_chang.gitee.io/pure-admin-doc/pages/build/#%E5%BC%80%E5%90%AF-gzip%E3%80%81brotli-%E5%8E%8B%E7%BC%A9
