### ISSUE TITLE
如何部分页面免登录查看？

### ISSUE THREAD

**Issue by q447552640** [pure-admin/vue-pure-admin#791]
### 描述问题 (Describe the problem)

完全静态路由模式做展示页面，目录想要直接显示，免去登录部分，修改了一开始的跳转，直接进welcome了。
这时候路由还没生成（initRoute是在login里面调用的）
把initRoute放到目录显示时调用，可以显示目录，但是刷新卡死。
如何才能直接进主页，无需登录，并且目录可以被加载好。

### 如何复现该问题 (How to reproduce the problem)

在src/layout/components/sidebar/horizontal.vue里面，直接加载，刷新卡死。
onMounted(async () => {
  // TODO 暂时认为我们问题在这里
  await initRouter();
});

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/sso/

**Comment by q447552640** [comment]
感谢大佬
