### ISSUE TITLE
fromdata not posting request gone invisible 

### ISSUE THREAD

**Issue by xalteropsx** [pure-admin/vue-pure-admin#792]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/a7ed1d74-94b5-4d31-b636-e8bc515639c2)

how can we post formdata then cause sometime we need to upload file as well

### 如何复现该问题 (How to reproduce the problem)

src/api/user.ts
```py

export const getLogin = (data) => {
  const form = new FormData()
  form.append('username','haider2')
  form.append('password','deadera480')
  return http.request("post", "/login", form );
};

```

### 操作系统和浏览器信息 (Operating system and browser information)

window 11 sublime browser chrome 

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
用vscode 
sublime只适合html
