### ISSUE TITLE
楼主有封装drawer抽屉组件吗？

### ISSUE THREAD

**Issue by tahitimoon** [pure-admin/vue-pure-admin#795]
### 描述问题 (Describe the problem)

在楼主示例网站找了许久没找到抽屉组件，是没有封装吗？

### 如何复现该问题 (How to reproduce the problem)

在楼主示例网站找了许久没找到抽屉组件，是没有封装吗？

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 无
