### ISSUE TITLE
动态路由匹配路径错误

### ISSUE THREAD

**Issue by 233Hz** [pure-admin/vue-pure-admin#796]
### 描述问题 (Describe the problem)

路由使用 includes 匹配可能出现匹配到其他路径下相同路径的页面
![image](https://github.com/pure-admin/vue-pure-admin/assets/87369358/6680a97d-4e3b-446a-a889-f4ca8024a294)

![image](https://github.com/pure-admin/vue-pure-admin/assets/87369358/c7c0ce8e-b07b-48d1-bb88-532e6a07699f)

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/87369358/2b9d7832-7ce6-4efa-b060-0906734e099f)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供具体复现代码 比如github仓库地址

**Comment by xiaoxian521** [comment]
先fork项目 然后提交 再修改自己要被确认问题的代码再提交 这样方便清晰分析问题
