### ISSUE TITLE
开启CDN模式打包分析的时候echarts还是打包到js文件

### ISSUE THREAD

**Issue by smarteng** [pure-admin/vue-pure-admin#797]
### 描述问题 (Describe the problem)
<img width="964" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/fd185d30-8c07-482b-96c4-64f58961149f">

<img width="488" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/35437e2c-7cf3-4230-9bb2-dc647fd94221">

版本：master版本

开启CDN模式打包分析的时候echarts还是打包到js文件，同时也引入了
<img width="1407" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/76851cea-f4ac-4762-a592-0a3128fb18a1">

### 如何复现该问题 (How to reproduce the problem)

pnpm report   查看报告
pnpm build 查看dist index.html文件

### 操作系统和浏览器信息 (Operating system and browser information)

Mac

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by smarteng** [comment]
首先非常感谢能这么快的回复，必须手动点赞。
其次，我测试了一下：
**在cdn引入echarts**
<img width="605" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/6c8fa2a2-c6c2-4c23-9adb-77de8963d477">

<img width="692" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/7a748e4e-28d5-4e3d-904a-ab3c7fb146e3">
**不在CDN引入echarts**
<img width="707" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/3febcf14-abce-462f-82bd-570636d15b46">
<img width="709" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/663786/64042ace-608e-42c8-bc95-333d1aef85be">

产生的文件没有变化，我不是专业做前端的，但是我感觉应该不是 vite-plugin-cdn-import 的问题。

**Comment by xiaoxian521** [comment]
这种方案：自行写个最小的demo 引入vite-plugin-cdn-import和echatrs观察变化 
目前我没有时间查看这个是否是问题并且是什么问题

**Comment by xiaoxian521** [comment]
目前只处理明确的问题 所以还请提问者自行确定问题
