### ISSUE TITLE
首页修改内容点击菜单切换不加载内容

### ISSUE THREAD

**Issue by MiniNec** [pure-admin/vue-pure-admin#798]
### 描述问题 (Describe the problem)

首页修改内容点击菜单切换不加载内容

### 如何复现该问题 (How to reproduce the problem)

thin版,首页的文字修改成两行,点击任意菜单,不显示内容

### 操作系统和浏览器信息 (Operating system and browser information)

win10,使用的chorme,我是前后端联调,但是如果不点击首页,其他操作菜单切换都是正常的

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vue3-%E5%8D%95%E6%96%87%E4%BB%B6%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%E6%A0%B9%E6%A0%87%E7%AD%BE-%E4%BD%86%E6%98%AF%E5%B9%B3%E5%8F%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E8%BF%99%E4%B9%88%E7%94%A8%E5%91%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
