### ISSUE TITLE
'NODE_OPTIONS' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by MiniNec** [pure-admin/vue-pure-admin#801]
### 描述问题 (Describe the problem)

项目在pnpm install 成功后,使用pnpm run dev出现'NODE_OPTIONS' 不是内部或外部命令，也不是可运行的程序
或批处理文件。的问题

### 如何复现该问题 (How to reproduce the problem)

具体问题不明,在代码未修改的情况下出现

### 操作系统和浏览器信息 (Operating system and browser information)

win10  node 18.16.0

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
如遇此情况 安装并使用`cross-env`
参考 https://github.com/pure-admin/vue-pure-admin/commit/392105e8202f2280f0d86873d742eeae362abe80

**Comment by shady-xia** [comment]
可以看下是不是因为把 `.npmrc` 文件删掉了，如果删掉恢复就行了
