### ISSUE TITLE
[提问][非bug]@import引入scss文件时使用url()只有最外层的样式生效，嵌套的css部分无法读取

### ISSUE THREAD

**Issue by UntilX** [pure-admin/vue-pure-admin#802]
### 描述问题 (Describe the problem)

![WX20231120-192330@2x](https://github.com/pure-admin/vue-pure-admin/assets/40851247/15b551c9-d0da-4f8a-b132-04544edaef38)

如上图所示，很多人遇到了这种情况，解决办法是不要使用@import url('')的形式，要使用@import ''的形式。
但是我看作者使用`@import url('')`没有问题，请问是如何配置的。

### 如何复现该问题 (How to reproduce the problem)

我配置大改过，应该无法复现

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前比较忙 暂不解决非bug问题 我将issues评论开放
