### ISSUE TITLE
在精简版接口请求拿到数据后调用useECharts报错

### ISSUE THREAD

**Issue by 6ivan** [pure-admin/vue-pure-admin#803]
### 描述问题 (Describe the problem)

<img width="613" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/48577458/d9e94768-03dc-44b4-a26b-309c13015f62">

### 如何复现该问题 (How to reproduce the problem)

代码
<img width="571" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/48577458/a71242d7-e399-49d9-a2bc-6d34ed7971e6">

### 操作系统和浏览器信息 (Operating system and browser information)

谷歌
MacOS

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考完整版 正确配置echarts

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/tree/main/src/plugins/echarts

https://github.com/pure-admin/vue-pure-admin/blob/main/src/main.ts#L8C10-L8C20

https://github.com/pure-admin/vue-pure-admin/blob/main/src/main.ts#L59
