### ISSUE TITLE
精简版缺少注册模块

### ISSUE THREAD

**Issue by davidCcD** [pure-admin/vue-pure-admin#805]
### 描述问题 (Describe the problem)

精简固然是好，但精简到只有登录模块，没有注册模块，就不实用了。于是还得用完整版。

### 如何复现该问题 (How to reproduce the problem)

精简固然是好，但精简到只有登录模块，没有注册模块，就不实用了。于是还得用完整版。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 自行引入 因为它叫精简版

**Comment by xiaoxian521** [comment]
还有后台管理一般没有注册 完整版有完全只是提供更多的demo 代码非常简单且都在那里放着 自己动手丰衣足食
