### ISSUE TITLE
appMain 中的el-scrollbar 没起作用  滑块没有改变样式

### ISSUE THREAD

**Issue by Ewithome** [pure-admin/vue-pure-admin#806]
### 描述问题 (Describe the problem)

appMain 中的el-scrollbar 没起作用  滑块没有改变样式

### 如何复现该问题 (How to reproduce the problem)

appMain 中的el-scrollbar 没起作用  滑块没有改变样式

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by Ewithome** [comment]
感谢您的来信！查收后我会第一时间给您答复！如果是重要资料，请给我电话或短信通知下！ 张益明   ：  13312914526

**Comment by xiaoxian521** [comment]
使用最新代码 提供具体截图 而不只是简单描述
