### ISSUE TITLE
addDialog中丢失响应式数据

### ISSUE THREAD

**Issue by jswangshuo** [pure-admin/vue-pure-admin#807]
### 描述问题 (Describe the problem)

addDialog中渲染的组件editForm 使用useWaringInform导出的响应式数据data  data丢失响应式数据

**使用场景**
在useWaringInform统一定义了数据和处理逻辑 所有接口也都在这个hook函数中调用 
所以导出了响应式数据data 在editForm中进行渲染 但是发现丢失了响应式

### 如何复现该问题 (How to reproduce the problem)

**editForm**
`<template>
  {{ data }}
</template>

<script lang="ts" setup>
import { useWaringInform } from "../hook";
const { data } = useWaringInform();

</script>
`

**useWaringInform**
导出openDialog和data
`
  let data = ref([]);
  function openDialog(row?: any) {
    setTimeout(() => {
      data.value = [1, 2, 3];
      console.log(data.value,'565')
      ElMessage.info("数据更新");
    },2000);
    addDialog({
      props: {
        row
      },
      width: "30%",
      draggable: true,
      fullscreenIcon: true,
      closeOnClickModal: true,
      contentRenderer: () => h(editForm, { ref: formRef }),
      beforeSure: done => {
        formRef.value.getRef().validate(async data => {
          await warnNoticeApi.update(data);
          done();
          getData();
          ElMessage.success("编辑成功");
        });
      }
    });
  }`

![image](https://github.com/pure-admin/vue-pure-admin/assets/75619002/7ee22dea-44aa-49aa-9402-a63b73db2623)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
那是你用法问题 多参考项目代码
