### ISSUE TITLE
Tab presistence 

### ISSUE THREAD

**Issue by xalteropsx** [pure-admin/vue-pure-admin#808]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/6fea9724-a5e7-4662-a662-6712c54e354f)
![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/a9fe56fd-1be4-4d49-838b-f14517b5750a)

why this loading keep appear after the page load once 

### 如何复现该问题 (How to reproduce the problem)

sorry for not reproduce this cause i clone the same branch just ran using normal way tab persistence enable not work 

is the keep-alive tab not existed ? 

plz guide me am i missing something 

### 操作系统和浏览器信息 (Operating system and browser information)

window 11 
chrome ,brave 

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
Unable to reproduce, check the code yourself

**Comment by xalteropsx** [comment]
please help bro whenever i switch page the loading appear it quiet 3-4sec each page switch

**Comment by xalteropsx** [comment]
@xiaoxian521 please guide last timei am kinda lost what am i missing 
![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/8f06c15f-c570-46fc-850c-1bd17668d6c8)
![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/0f65335e-ff02-4ecb-9bf5-245724c0ea7f)

**Comment by xalteropsx** [comment]
```js

    cacheOperate({ mode, name }: cacheType) {
      const delIndex = this.cachePageList.findIndex((v: any) => v === name);
      console.log(mode);
      console.log(name);

``` cacheOperate not trigger when appending tab 

this leading to an empty array

**Comment by xiaoxian521** [comment]
Please don't bring some unnecessary noise and check the code yourself
