### ISSUE TITLE
同时运行两个vue-pure-admin会导致Authorization错乱

### ISSUE THREAD

**Issue by davidCcD** [pure-admin/vue-pure-admin#809]
### 描述问题 (Describe the problem)

同时运行两个vue-pure-admin，端口分别为8848、8849，会导致Authorization错乱，比如项目1登录后，再用项目2登录，会读取到项目1的token，导致出错。我以为是要修改src/utils/localforage/index.ts里面的name，改成了
    this.storage.config({
          driver: [this.storage.INDEXEDDB, this.storage.LOCALSTORAGE],
          name: "my-web-project-2"
    });
但问题并没有解决。似乎是cookie混乱了？
请问大佬，是在哪里设置呢？

### 如何复现该问题 (How to reproduce the problem)

同时运行两个vue-pure-admin，端口分别为8848、8849，会导致Authorization错乱，比如项目1登录后，再用项目2登录，会读取到项目1的token，导致出错。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by bethe410** [comment]
我也遇到了这个问题，排查了好久……wontfix也没关系，但可以请大佬提示一下是什么原因？
