### ISSUE TITLE
@pureadmin/utils

### ISSUE THREAD

**Issue by xalteropsx** [pure-admin/vue-pure-admin#810]
### 描述问题 (Describe the problem)

你的包不支持 svg 渲染器

### 如何复现该问题 (How to reproduce the problem)

const { setOptions, getInstance, resize } = useECharts(lineChartRef, { renderer: "svg" });

import { SVGRenderer } from "echarts/renderers";
use([SVGRenderer]);
### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xalteropsx** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/dbe9beae-3bae-471e-912b-91707ad82d8d)
compare vue-echarts 
![image](https://github.com/pure-admin/vue-pure-admin/assets/103671642/bda1902b-13e0-401b-bfbf-0bbfe2818e70)

**Comment by xiaoxian521** [comment]
你的用法不对 
等待我更新文档 https://github.com/pure-admin/pure-admin-utils-docs/pull/14
时间未知 持续关注
