### ISSUE TITLE
pure-table设置了border，在设置adaptive时，表头的上边框边框不显示

### ISSUE THREAD

**Issue by TZZCODE** [pure-admin/vue-pure-admin#813]
### 描述问题 (Describe the problem)

<img width="1042" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/18049263/538b453a-f204-48e6-a28a-1ec7b2193772">

### 如何复现该问题 (How to reproduce the problem)

pure-table设置了border，设置adaptive时

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应地方提问
https://github.com/pure-admin/pure-admin-table/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
