### ISSUE TITLE
非国际化精简版，无法运行项目

### ISSUE THREAD

**Issue by Malunc** [pure-admin/vue-pure-admin#814]
### 描述问题 (Describe the problem)

![1880a99bb8aaca97b2273d7c06fd48e](https://github.com/pure-admin/vue-pure-admin/assets/75530283/bddd1982-d6a7-4d7b-aeb6-01bfbb2f451f)
使用的是非国际化精简版，正常pnpm安装所有依赖后，运行项目出现该报错信息，无法启动项目

### 如何复现该问题 (How to reproduce the problem)

clone 非国际化精简版，pnpm安装依赖，运行项目就会出现报错

### 操作系统和浏览器信息 (Operating system and browser information)

windowns 系统
google 浏览器
node 16.16.0
pnpm 6.32.3

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="1330" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/2b450738-5703-4a4c-889e-9fa27238c403">
