### ISSUE TITLE
pure admin 引入 Vditor MD编辑器报错

### ISSUE THREAD

**Issue by 88act** [pure-admin/vue-pure-admin#816]
### 描述问题 (Describe the problem)

 Vditor MD 编辑器  https://github.com/Vanessa219/vditor/ 
 
 其他项目中，使用  
 npm install vditor --save  
 方式 安装， 能正常使用   
 
在 pure admin 中
 使用 pnpm add vditor  方式安装
，在vue 页面引入报错

版主有空帮忙看看

### 如何复现该问题 (How to reproduce the problem)

https://b3log.org/vditor/demo/index.html

### 操作系统和浏览器信息 (Operating system and browser information)

win10 ,pc , chrome

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前没时间测试
任何组件都可以引入pureadmin 只是没找到办法而已
等我有空吧
