### ISSUE TITLE
关于vite-plugin-fake-server无法载入

### ISSUE THREAD

**Issue by wolf777a** [pure-admin/vue-pure-admin#817]
### 描述问题 (Describe the problem)

控制台报错
23:24:15 [vite-plugin-fake-server] failed to load module from mock\refreshToken.ts
23:24:15 [vite-plugin-fake-server] failed to load module from mock\login.ts
23:24:15 [vite-plugin-fake-server] failed to load module from mock\asyncRoutes.ts
23:24:15 [vite-plugin-fake-server] failed to load module from mock\list.ts
23:24:15 [vite-plugin-fake-server] failed to load module from mock\map.ts
23:24:15 [vite-plugin-fake-server] failed to load module from mock\system.ts

项目可以正常启动，页面正常，login请求报404
查阅了 vite-plugin-fake-server源码包
发现问题在

<img width="597" alt="截图20231201232749" src="https://github.com/pure-admin/vue-pure-admin/assets/122727626/8e38c383-19f4-4796-b7f4-24b27126ef6b">

不知道啥原因，找了issue也没有找到
隐隐约约是有看到作者在和  vite-plugin-fake-server 的作者交流，但是没有看到解决方案

### 如何复现该问题 (How to reproduce the problem)

按照操作
pnpm i
pnpm dev

### 操作系统和浏览器信息 (Operating system and browser information)

windows

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
我在windows上测试是没问题带 带上你的问题去 https://github.com/condorheroblog/vite-plugin-fake-server 提
