### ISSUE TITLE
分页的样式可以配置成显示表格右下角吗？现在是固定下最底部。有这种属性可以设置？

### ISSUE THREAD

**Issue by zhangran2616** [pure-admin/vue-pure-admin#818]
### 描述问题 (Describe the problem)

分页的样式可以配置成显示表格右下角吗？紧挨着那。现在是固定下最底部。有这种属性可以设置？

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

Google浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应库在对应地方提问 https://github.com/pure-admin/pure-admin-table
