### ISSUE TITLE
请问下addDialog关于button的配置问题

### ISSUE THREAD

**Issue by zhangran2616** [pure-admin/vue-pure-admin#820]
### 描述问题 (Describe the problem)

addDialog默认现在是确认和取消2个默认值。如果我想在点击确认按钮调用接口的时候设置成loading状态，接口返回就取消loading。只能通过：
footerButtons: [
        // {
        //   label: "按钮1",
        //   size: "small",
        //   type: "success",
        //   btnClick: ({ dialog: { options, index }, button }) => {
        //     console.log(options, index, button);
        //     //closeDialog(options, index);
        //     button.btn.loading = true;
        //   }
        // }
      ],
      这个属性来配置吗？我仅仅只是想设置下loading。其他属性还是用默认的。

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
不好意思 目前很忙 目前只解决确定性bug

**Comment by jack20211101** [comment]
> 👌，。

可以通过回调中**index**在**dialogStore**里取到当前弹出层配置，但是无法直接**dialogStore.value[index].footerButtons[1].loading = true**访问，loading没有初始化会提示不存在。
作者目前是在[这个位置判断然后给默认值](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.vue#L19)，我将它[移动到了](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.ts#L18)。

**Comment by zhangran2616** [comment]
> > 👌，。
> 
> 可以通过回调中**index**在**dialogStore**里取到当前弹出层配置，但是无法直接**dialogStore.value[index].footerButtons[1].loading = true**访问，loading没有初始化会提示不存在。 作者目前是在[这个位置](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.vue#L19)判断然后给默认值，我将它[移动到了](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.ts#L18)。所有是的，要么改组件，要么每次填写footerButtons

{
            label: "确定",
            type: "primary",
            text: true,
            bg: true,
            btnClick: ({ dialog: { options, index }, button }) => {
              button.btn.loading = true;
              const done = () =>
                closeDialog(options, index, { command: "sure" });
              if (options?.beforeSure && isFunction(options?.beforeSure)) {
                button.btn.loading = true;
                options.beforeSure(done, { options, index });
                button.btn.loading = false;
              } else {
                done();
              }
            }
          }
          
          加这个位置为啥不生效呢？

**Comment by jack20211101** [comment]
> button

哈？应该是这样吧：**options.footerButtons[0].loading = true**，但是似乎达不到想要的效果，下面是我改的，凑合能用。当然可以试试修改**done()**方法传参。我是这么改的：

[src/components/ReDialog/index.vue#L20](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.vue#L20)
![image](https://github.com/pure-admin/vue-pure-admin/assets/96187352/b43f3564-1f44-483c-aa90-9db2785ba362)
[src/components/ReDialog/index.ts](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.ts#L18C1-L18C1)
![image](https://github.com/pure-admin/vue-pure-admin/assets/96187352/67be282d-1f43-4a9f-bcd5-34b38ba7fca9)
**这个提出来，放哪随意**
![image](https://github.com/pure-admin/vue-pure-admin/assets/96187352/98ba1fba-8656-40ef-8422-ad8b161a7865)

**Comment by zhangran2616** [comment]
> > button
> 
> 哈？应该是这样吧：**options.footerButtons[0].loading = true**，但是似乎达不到想要的效果，下面是我改的，凑合能用。当然可以试试修改**done()**方法传参。我是这么改的：
> 
> [src/components/ReDialog/index.vue#L20](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.vue#L20) ![image](https://private-user-images.githubusercontent.com/96187352/287886273-b43f3564-1f44-483c-aa90-9db2785ba362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTIzMDUsIm5iZiI6MTcwMTc1MjAwNSwicGF0aCI6Ii85NjE4NzM1Mi8yODc4ODYyNzMtYjQzZjM1NjQtMWY0NC00ODNjLWFhOTAtOWRiMjc4NWJhMzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3M2QwZGJjZDc0MDY0NDc5MTZiNzY4YWQ1ODgxY2M3ZDc2YmE5MTEwYjI3YzNhYTg2Y2FlNGVhM2QyYmUxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buPtltIHznaw71Cu3Vvi6acuzUILr91NNozdHtTin7E) [src/components/ReDialog/index.ts](https://github.com/pure-admin/vue-pure-admin/blob/main/src/components/ReDialog/index.ts#L18C1-L18C1) ![image](https://private-user-images.githubusercontent.com/96187352/287886344-67be282d-1f43-4a9f-bcd5-34b38ba7fca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTIzMDUsIm5iZiI6MTcwMTc1MjAwNSwicGF0aCI6Ii85NjE4NzM1Mi8yODc4ODYzNDQtNjdiZTI4MmQtMWY0My00YTlmLWJjZDUtMzRiMzhiYTdmY2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYzU3ODM2ZjQ1OWQ3ODUzNTQ3Yjc2OTIyMDA5NjhiMjFjYjlkMGU5NTA3MDQ5NmMwYzgzNzgyMGI4ZWZlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.izq-1pJydCJMpZHmLA2AzkpzXfXEm3IsPsjqd8ex17Y) **这个提出来，放哪随意** ![image](https://private-user-images.githubusercontent.com/96187352/287886443-98ba1fba-8656-40ef-8422-ad8b161a7865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTIzMDUsIm5iZiI6MTcwMTc1MjAwNSwicGF0aCI6Ii85NjE4NzM1Mi8yODc4ODY0NDMtOThiYTFmYmEtODY1Ni00MGVmLTg0MjItYWQ4YjE2MWE3ODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYWE0ZjM4YjQwZGQwYzBiYjc1MmIwM2YxNDc2ODVjOWNjZDg3NzVhZDY3ODEzMWZhZDk0MmQ5MjQ2OWEwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ntuxhMs1jvbIlHEp8XX2u35ypL-SR1CGGh_SLX3Duo0)

感谢回复

**Comment by lqllife** [comment]
接口请求报错时，还需要将 确定 按钮的loading取消掉，有好的思路吗？ @zhangran2616 @jack20211101

**Comment by jack20211101** [comment]
> 接口请求报错时，还需要将 确定 按钮的loading取消掉，有好的思路吗？ @zhangran2616 @jack20211101
类似上图，options.footerButtons[1].loading = false

**Comment by jack20211101** [comment]
> 接口请求报错时，还需要将确定按钮的加载取消掉，有好的思路吗？@zhangran2616 @jack20211101

options.footerButtons[1].loading = false 类似这样
