### ISSUE TITLE
没有关闭当前标签页的功能

### ISSUE THREAD

**Issue by Rebuilding127** [pure-admin/vue-pure-admin#821]
### 描述问题 (Describe the problem)

没有关闭当前标签页的功能。
应用场景如：新增表单数据（以单独Tab页形式打开录入数据）保存后自动关闭当前标签页。

未在文档或示例功能找找到想要的，只在标签页操作菜单所展示的功能中找到类似的，可控制关闭菜单标签页的功能。

但是实际使可能用存在问题。
例如，编辑的标签页可以同时多个，比如编辑1、编辑2、编辑3，此时若关闭编辑3，实际会关闭编辑1标签，查阅代码发现是由于关闭操作的逻辑是根据页面`path`进行匹配，匹配成功后关闭首个匹配页，由于这3个编辑页面的`path`都是一样的，只是`query | params` 不同，按该逻辑匹配的首个匹配项不一定是想要关闭的当前页。
我考虑过把匹配逻辑 `findIndex` 改为 `findLastIndex` 但一样会存在问题。

### 如何复现该问题 (How to reproduce the problem)

示例网站中的标签页操作菜单。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
自行添加

**Comment by xiaoxian521** [comment]
在还未发布 [5.0](https://github.com/pure-admin/vue-pure-admin/issues/748) 之前 
不再新增任何功能 只解决bug
