### ISSUE TITLE
http请求 前置拦截whiteList  refresh-token 需改回 refreshToken

### ISSUE THREAD

**Issue by fancyfff** [pure-admin/vue-pure-admin#823]
### 描述问题 (Describe the problem)

1. user api  方法：刷新token  已改成 refreshToken
2. http请求前置拦截 httpInterceptorsRequest 下面方法
   const whiteList = ["/refreshToken", "/login"];
        return whiteList.find(url => url === config.url)
这边的 url === config.url 无法匹配，导致无法跳过

### 如何复现该问题 (How to reproduce the problem)

token过期后刷新页面即可

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
早已解决 https://github.com/pure-admin/vue-pure-admin/commit/a713d372dee9a7ca8bdd9330a62a4e932ae58f43
