### ISSUE TITLE
[Feature Request] Migrate `package.json` to `json5` or `yaml`

### ISSUE THREAD

**Issue by aboutZZ** [pure-admin/vue-pure-admin#824]
### 描述问题 (Describe the problem)

pnpm 支持 `json5` 以及 `yaml` 格式的包描述文件，主要是支持注释这个特性比较香。`json` 阅读性较差，依赖多了都不知道这是干啥的，想加点注释也加不上去。
因此希望能迁移至`json5` 或 `yaml` 格式

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
可以的 等`5.0.0`版本发布吧 然后抽时间我看看

**Comment by aboutZZ** [comment]
好的，迁移至 `json5` 只需要把 `package.json` 重命名为 `package.json5`， 无痛迁移✈。然后就能愉快地加上注释了
