### ISSUE TITLE
配置后端接口前缀？

### ISSUE THREAD

**Issue by CrazyCat6** [pure-admin/vue-pure-admin#825]
### 描述问题 (Describe the problem)

怎么配置后端接口前缀 ？是在这吗？
<img width="700" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/38643408/e4ec10c8-c07d-4d21-b7ba-e27904d869bc">
访问不了，
![image](https://github.com/pure-admin/vue-pure-admin/assets/38643408/4107fe39-d0f6-4b05-a9b4-d9983379c8ba)

### 如何复现该问题 (How to reproduce the problem)

怎么配置后端接口前缀 ？是在这吗？
<img width="700" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/38643408/e4ec10c8-c07d-4d21-b7ba-e27904d869bc">
访问不了，
![image](https://github.com/pure-admin/vue-pure-admin/assets/38643408/4107fe39-d0f6-4b05-a9b4-d9983379c8ba)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
请看文档 `5.0.0`版本发布前 只解决bug
