### ISSUE TITLE
关于`@pureadmin/utils`的消息以及它的文档重构后已推出

### ISSUE THREAD

**Issue by xiaoxian521** [pure-admin/vue-pure-admin#827]
目前 [pure-admin-utils](https://github.com/pure-admin/pure-admin-utils-docs/issues/7) 源码只提供给平台内部成员，后面我会将其放出，大概会在我的 [bilibili](https://space.bilibili.com/301103230?spm_id_from=333.1007.0.0) 下个`vue-pure-admin`最新完整免费教学视频时将 [@pureadmin/utils](https://www.npmjs.com/package/@pureadmin/utils) 代码开放出来。 
 
具体时间不好讲，开源真的没有绝对的日期，全凭爱好、热情支撑下去。如果非要个期限，我只能说你的等待，我绝不辜负

你们也可以看到平台从`2020-11-16`开发以来从来没强制收费才能用，文档源码全部开源，而且文档很保姆级吧，我也没有刻意做流量，也不会有任何强制链接跳转，教学视频重来不收费，甚至今年我把捐赠二维码也删了，近几年市场环境差，我也没考虑过收费。没错，搞开源，我们很纯粹。主要是年轻，没任何经济压力，够生活就行。当然我知道这种状态可能会在未来几年减弱，但这也是很正常的，因为生活压力来了，没那么多精力了。纯粹搞开源还是得趁年轻，别等老了就算有能力也没精力了；它可能不会使你的钱包鼓鼓，但你可以享受开源；不断突破自己，不管奋战多晚，依旧很值得。毕竟选择了这个行业，编码要陪伴自己半辈子，做点有意义的事情岂不快哉。年老了，跟朋友还能吹吹牛😆。这不就是年轻应该做的嘛，加油吧 😜。哦，对了，做开源还能结识很多技术大佬，互相交流学习，岂不美哉。

目前，平台开放一切代码使用权限，也就是不管你想二次开源还是你想商业化，无需经过我的同意，想咋用就咋用，不会追究任何责任，说直白点就是 [pure-admin](https://github.com/pure-admin) 里的代码都是你的

目前 [pure-admin-utils-docs](https://pure-admin-utils.netlify.app/) 文档已经重构完成。如果你当前浏览`pure-admin-utils-docs`与下面视频页面不一致，请强制刷新浏览器或清理浏览器缓存即可（重构后的文档可不算简单哦，内置很多实用功能，如果你也有文档需求，不妨试试😄）

https://github.com/pure-admin/vue-pure-admin/assets/44761321/646f529d-3c0f-47e2-97be-6a620b09490f

**Comment by xiaoxian521** [comment]
后面平台可能会推出 [pure-admin-table](https://github.com/pure-admin/pure-admin-table) 文档，尽管它已经有详细的示例了，但是有个文档感觉更正式专业一点吧 😄

<img width="1676" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/b3929149-f389-4e4f-8e22-2edea84f1663">

**Comment by LinkanDawang** [comment]
感谢提供了这么好的项目

**Comment by is-Joe** [comment]
感谢，文档相当良心了

**Comment by jack20211101** [comment]
加油！~
