### ISSUE TITLE
pnpm i 下载依赖一直失败

### ISSUE THREAD

**Issue by jswangshuo** [pure-admin/vue-pure-admin#828]
### 描述问题 (Describe the problem)

pnpm i 下载依赖一直失败 使用的是 精简版非国际化
![image](https://github.com/pure-admin/vue-pure-admin/assets/75619002/fd56d50e-ea6b-41f4-9c76-7a4c4ca4ca03)

### 如何复现该问题 (How to reproduce the problem)

WARN  GET https://registry.npmjs.org/@pureadmin/theme/-/theme-3.1.0.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@pureadmin/theme/-/theme-3.1.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
 ETIMEDOUT  request to https://registry.npmjs.org/@pureadmin/theme/-/theme-3.1.0.tgz failed, reason: connect ETIMEDOUT 104.16.25.34:443

FetchError: request to https://registry.npmjs.org/@pureadmin/theme/-/theme-3.1.0.tgz failed, reason: connect ETIMEDOUT 104.16.25.34:443
    at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\pnpm\dist\pnpm.cjs:69196:18)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多看文档 https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E6%85%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
