### ISSUE TITLE
标签页持久化配置不生效

### ISSUE THREAD

**Issue by lqllife** [pure-admin/vue-pure-admin#829]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/23254569/4e464eb6-7b96-482a-96c1-c2f49177de76)

打开这个设置后，每次切换标签页时还是会销毁并重新加载组件，PureAdmin完整版的演示环境上也存在这个问题。

### 如何复现该问题 (How to reproduce the problem)

在设置中打开`标签页持久化`，在标签页A中搜索一些内容，切换到B，再切回A，A里面搜索的内容没有了。
![1](https://github.com/pure-admin/vue-pure-admin/assets/23254569/57b4e677-035d-4e88-9240-79c45aa7f84a)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
.....标签页持久化是针对标签 页面缓存用keepalive 多看看文档哈 这好像是常识了
