### ISSUE TITLE
按照element-plus方式修改主题配色, 没有成功

### ISSUE THREAD

**Issue by myBoringCode** [pure-admin/vue-pure-admin#835]
### 描述问题 (Describe the problem)

安装[官方文档](https://element-plus.org/zh-CN/guide/theming.html#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%AE%83%EF%BC%9F)进行操作, 没有成功
代码均拷贝于https://github.com/element-plus/element-plus-vite-starter
![image](https://github.com/pure-admin/vue-pure-admin/assets/129058082/abf7d3f2-04ee-4541-b5b8-4374e8d758a9)
![image](https://github.com/pure-admin/vue-pure-admin/assets/129058082/d61ffbc2-05c6-463f-b6a0-3bdec2466891)

### 如何复现该问题 (How to reproduce the problem)

按照官方文档进行操作

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/theme/#%E5%86%85%E7%BD%AE%E4%B8%BB%E9%A2%98
