### ISSUE TITLE
精简版

### ISSUE THREAD

**Issue by lotherli** [pure-admin/vue-pure-admin#837]
### 描述问题 (Describe the problem)

是否有考虑先将5.0版本中除【开发系统管理-菜单管理】的近期更新到精简版中
想去使用您的精简版，看到你修复了很多的问题，导致目前我自身不敢去使用精简版😂

### 如何复现该问题 (How to reproduce the problem)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="949" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/d7d75873-f22f-4634-91d8-66c657dbcaef">

**Comment by lotherli** [comment]
是的，看了你的5.0计划，预计在24年上半年😂，就怕来一手5月份。或者你先来一手4.6版本🙈

**Comment by xiaoxian521** [comment]
额 `5.0`版本是最后的大版本，所以需要等我把所有工作做完再发。 开源不是商业，在我有时间肯定会开发
