### ISSUE TITLE
多语言优化

### ISSUE THREAD

**Issue by SeaLee02** [pure-admin/vue-pure-admin#838]
### 描述问题 (Describe the problem)

现在的所以的配置都在一个xml文件里面，能不能跟路由一样，分module存放，这样好区分

### 如何复现该问题 (How to reproduce the problem)

现在的所以的配置都在一个xml文件里面，能不能跟路由一样，分module存放，这样好区分

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
emm
有没有可能你走错地方了？
平台的国际化不是划分的很清楚吗
<img width="294" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/46f68f17-341f-4207-8986-b6c69890f840">
