### ISSUE TITLE
如何将动态标签添加到菜单

### ISSUE THREAD

**Issue by chengfzy** [pure-admin/vue-pure-admin#840]
### 描述问题 (Describe the problem)

请教大佬，如下图所示，我想将通过params传参调用生成的两个标签也显示到菜单栏，该如何操作呢?

![image](https://github.com/pure-admin/vue-pure-admin/assets/7237187/6b2e7dab-512e-45d6-9993-2924f68e5362)

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
不支持 请自行实现

**Comment by chengfzy** [comment]
好吧，谢谢大佬。折腾半天了，没找到办法

**Comment by xiaoxian521** [comment]
添加了也没用啊 刷新就没了 除非对菜单也做本地持久化缓存 标签页操作那只是针对标签

**Comment by chengfzy** [comment]
有这种需求，比如我需要显示多个设备相关信息，每个设备信息是类似的，只是ID不同，而这些ID可以根据在登陆时通过后台得到。这种场景就和上面的动态标签有点类似啊，但我新手没想到怎么去动态添加相应的菜单

**Comment by xiaoxian521** [comment]
这种通常是在标签上显示，菜单不会显示
菜单一般都是初始化就完成的
所以你的需求需要自行解决哈

**Comment by chengfzy** [comment]
好的，明白了，我再想想办法，谢谢大佬
