### ISSUE TITLE
切换菜单就会报错-比如进入系统管理-用户管理会报错：TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by nepucbl** [pure-admin/vue-pure-admin#843]
### 描述问题 (Describe the problem)

切换菜单就会报错-比如进入系统管理-用户管理会报错：TypeError: Cannot read properties of null (reading 'parentNode')
![切换菜单会报错](https://github.com/pure-admin/vue-pure-admin/assets/56592756/0eecefcf-830a-486b-ab1e-0bc1cd04d4a1)

### 如何复现该问题 (How to reproduce the problem)

切换菜单就会报错-比如进入系统管理-用户管理会报错

### 操作系统和浏览器信息 (Operating system and browser information)

谷歌浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
嗯 这是升级vue版本带来的问题 明天会处理

**Comment by xiaoxian521** [comment]
感谢反馈 
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/246da7c872c6038217fa3397fdc417bf48b060ab)
