### ISSUE TITLE
登录报错，Headers is not defined

### ISSUE THREAD

**Issue by brosegu** [pure-admin/vue-pure-admin#849]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/12181144/582bfeea-f86c-4dad-8a87-4971378b0153)

### 如何复现该问题 (How to reproduce the problem)

本地安装依赖之后，登录界面，使用账户登录，无反应，浏览器控制台报错如图

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
`windows`系统吗？
删除`pnpm-lock.yaml`和`node_modules`在启动试试

**Comment by xiaoxian521** [comment]
如果还有问题 固定`vite-plugin-fake-server v2.0.0`
https://github.com/pure-admin/vue-pure-admin/commit/76cbbad940c86f714da788a27aa765667ee1e4c7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by brosegu** [comment]
两种方式都试过了，windows环境，serve模式。
![image](https://github.com/pure-admin/vue-pure-admin/assets/12181144/1115b6ec-067a-4ed0-9ad7-0b3b40e0c982)
还是同样的错误

**Comment by condorheroblog** [comment]
@brosegu 你 Node.js 的版本是多少，Vite 只支持 18+ 或者 20+，我看其他库也有这个问题，升级到 18 就没问题了

**Comment by condorheroblog** [comment]
你可以查看 Node.js 对 [Headers](https://nodejs.org/api/globals.html#class-headers) 方法支持的版本要求


![image](https://github.com/pure-admin/vue-pure-admin/assets/47056890/948a8908-8028-473b-8cd8-9bc6938c49e0)

**Comment by xiaoxian521** [comment]
是啊，像这种问题提问前要先提供系统环境和`node`以及`pnpm`版本

**Comment by brosegu** [comment]
是的，找到这个问题了。是node和npm的问题，node升级到18+可以了。按照vue官方文档来的。最低18+，感谢你们了
