### ISSUE TITLE
非bug！！！，只是对于代码有点疑问，望大佬解惑

### ISSUE THREAD

**Issue by liuk123456789** [pure-admin/vue-pure-admin#850]
### 描述问题 (Describe the problem)

感谢大佬开源此后台系统，相关文档配套做的很用心，下面是在看源码时存在疑惑的地方
![image](https://github.com/pure-admin/vue-pure-admin/assets/45746866/94d11769-3fe9-49d1-9360-d9c91510c39d)

![image](https://github.com/pure-admin/vue-pure-admin/assets/45746866/24d9609a-c54c-4f1e-bcef-30718506b001)

**formatFlatteningRoutes** 方法里已经进行了层级树的递归构建，所以上述的**buildHierarchyTree**是不是可以进行移除

### 如何复现该问题 (How to reproduce the problem)

非bug！！！！

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
不好意思 目前只解决bug
