### ISSUE TITLE
可能<el-dropdown>引起的左侧菜单收起和展开卡顿问题

### ISSUE THREAD

**Issue by ZhangMinghi** [pure-admin/vue-pure-admin#851]
### 描述问题 (Describe the problem)

当table表格内的数据超过3行左右，收起和展开左侧菜单过度动画会有明显卡顿；当把<template>标签中的<el-dropdown>下拉菜单全部注释后卡顿情况有明显好转，但是仍然会有卡顿。请看一下问题是不是能够复现，应该跟之前图标的卡顿是不同的

https://github.com/pure-admin/vue-pure-admin/assets/45185657/26139a85-7567-4d7e-b8c0-e37c2e072961

### 如何复现该问题 (How to reproduce the problem)

直接在项目mock中"/user"接口中添加数据，大概5-6条

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
无法定位具体原因 暂不解决 欢迎pr
