### ISSUE TITLE
修改本地跨域代理失效

### ISSUE THREAD

**Issue by morifeng123** [pure-admin/vue-pure-admin#854]
### 描述问题 (Describe the problem)

![1704427810637](https://github.com/pure-admin/vue-pure-admin/assets/72648261/61154a67-b9e2-42f6-ae39-62c505d65706)
![1704427838334](https://github.com/pure-admin/vue-pure-admin/assets/72648261/1cce80a1-7dd2-4b39-a282-b7b30a138fe9)
![1704427861483(1)](https://github.com/pure-admin/vue-pure-admin/assets/72648261/933bc4e4-ac31-40aa-a257-70c1d6b07464)

### 如何复现该问题 (How to reproduce the problem)

按照视频里的方法尝试过了 也是不行

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by morifeng123** [comment]
后端地址的请求接口也访问过 排除跨域问题

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/request/
