### ISSUE TITLE
动态路由的问题

### ISSUE THREAD

**Issue by 99mujin** [pure-admin/vue-pure-admin#855]
### 描述问题 (Describe the problem)

路由全部都是由后端提供的，出现的问题是登陆后的页面为无layout页面，也就是说顶级菜单会出现无layout的状态，刷新页面恢复正常。

### 如何复现该问题 (How to reproduce the problem)

将原本的首页隐藏后，全部的路由由后端提供，登陆会出现该问题

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/blob/main/.env#L5
