### ISSUE TITLE
动态路由

### ISSUE THREAD

**Issue by 99mujin** [pure-admin/vue-pure-admin#856]
### 描述问题 (Describe the problem)

<img width="213" alt="1" src="https://github.com/pure-admin/vue-pure-admin/assets/126851292/1e732d77-acce-4cc4-9f65-bd6cd7e27238">
在env文件中设置了VITE_HIDE_HOME = true，所有的菜单均为后端返回，在登陆后出现的顶级菜单页面为无layout形式，刷新后恢复正常。

### 如何复现该问题 (How to reproduce the problem)

<img width="550" alt="2" src="https://github.com/pure-admin/vue-pure-admin/assets/126851292/aa072475-f2ac-41ce-bd76-1cea388c1ae1">

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多自己调查调查 这都是我多次测试的 多看看是不是你路由问题 不要一直提问 多自己思考

**Comment by xiaoxian521** [comment]
提醒一点 前端路由不要乱删 有些路由是固定的 不管你是不是都是后端路由 前端一些固定的路由是约定俗成的
