### ISSUE TITLE
热更新导致动态路由失效

### ISSUE THREAD

**Issue by Soul-Killer-Ky** [pure-admin/vue-pure-admin#857]
### 描述问题 (Describe the problem)

使用后端动态路由方案，改变views下任意.vue文件中 <script setup lang="ts"></script> 中的代码，保存，此时页面热更新，此时router被重置，addRoute添加的路由全部失效，router.options.routes中只剩下前端路由，但是wholeMenus中路由数据仍然存在，且router.beforeEach不会被触发，导致函数调用时如果使用了hasAuth校验权限，校验会失败

### 如何复现该问题 (How to reproduce the problem)

改变views下任意.vue文件中 <script setup lang="ts"></script> 中的代码，保存，此时页面热更新，此时router被重置，addRoute添加的路由全部失效，router.options.routes中只剩下前端路由

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供具体复习仓库 fork pureadmin 然后再修改代码 我需要看到详细修改记录

**Comment by Soul-Killer-Ky** [comment]
浮现代码：
https://github.com/Soul-Killer-Ky/pure-admin-thin/commit/f2d3393bbcd80e04ccefa408fdc9a8e63854ded6

![image](https://github.com/pure-admin/vue-pure-admin/assets/26269381/5c700fda-cb16-4c40-9401-adb66199d2ed)

import Test from "@iconify-icons/ep/list" 和 import Test from "@iconify-icons/ep/delete" 来回更改就能看出问题

**Comment by Yizzzzzzzzz** [comment]
同有这个问题，最后如何解决的？

**Comment by erraleio** [comment]
您好，解决了吗？我是在登录触发热更新后，登录后就白屏了。下载的新项目也这样
