### ISSUE TITLE
第二次获无感刷新取不到refreshToken

### ISSUE THREAD

**Issue by freadman** [pure-admin/vue-pure-admin#859]
### 描述问题 (Describe the problem)

场景：
登录-获取refreshToken-等待过期-过期-点击其他页面-通过refreshToken获取新的refreshToken-等待过期-过期-点击其他页面-重新获取refreshToken-报错
<img width="1114" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/104674917/3012393d-bd02-426f-a6fd-7bfa1c431806">
打印接口请求，发现第二次无感刷新时没有传递refreshToken参数（第一次有传递，第二次无传递）
<img width="795" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/104674917/507ff82a-bef1-48e0-82c2-fc33640ff8f2">
<img width="1176" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/104674917/f4b25253-f5af-4f7d-a5fa-8d08e21caf22">

<img width="1128" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/104674917/1cdb3eb1-dec9-4ec8-b5c8-cc77a123fe45">
<img width="1128" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/104674917/22e53904-bc18-41c1-b36b-74c599faad44">

### 如何复现该问题 (How to reproduce the problem)

登录-获取refreshToken-等待过期-过期-点击其他页面-通过refreshToken获取新的refreshToken-等待过期-过期-点击其他页面-重新获取refreshToken-报错

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
你这是精简版吧 它几个月没更新 所以不会有啥问题 请自行检查代码
