### ISSUE TITLE
本地跨域代理未生效

### ISSUE THREAD

**Issue by chdxia** [pure-admin/vue-pure-admin#860]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/59914930/af9fa96d-39d5-472f-ba49-4d2f659d3da1)
![image](https://github.com/pure-admin/vue-pure-admin/assets/59914930/de4fb591-e2fe-4ec8-8957-ee79daeb55f7)
![image](https://github.com/pure-admin/vue-pure-admin/assets/59914930/d3a91dd1-d27b-40a1-aa95-0d67cb6ed52f)
![image](https://github.com/pure-admin/vue-pure-admin/assets/59914930/3d4a2064-d072-4b22-ba89-285d5fc5fa6c)

### 如何复现该问题 (How to reproduce the problem)

"name": "pure-admin-thin",
"version": "4.5.0",
特地请教一下
已阅读下述文档内容
https://yiming_chang.gitee.io/pure-admin-doc/pages/request/

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://www.bilibili.com/video/BV1kg411v7QT/
目前只解决bug
