### ISSUE TITLE
v-copy 异常

### ISSUE THREAD

**Issue by nineaiyu** [pure-admin/vue-pure-admin#861]
### 描述问题 (Describe the problem)

当需要复制的字段的值存在，为 false 的时候，有异常

### 如何复现该问题 (How to reproduce the problem)

`
const text= ref(false);
<span v-copy:click="text" class="text-sky-500">{{ text }}</span>
`

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
自行转化 使用字符串false
