### ISSUE TITLE
PureTableBar 设置隐藏字段，但是列展示勾选不一致

### ISSUE THREAD

**Issue by nineaiyu** [pure-admin/vue-pure-admin#862]
### 描述问题 (Describe the problem)

通过 hide 方法设置字段是否隐藏，但是列展示中，勾选状态不一致

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/19207867/06756ccb-6923-4c5b-8148-73dc75d86b41)

![image](https://github.com/pure-admin/vue-pure-admin/assets/19207867/517350ce-ecf2-4293-8556-3004de918e6c)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="1270" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/c6d4ce5c-1483-4a7d-95eb-144ca6cee985">
可能是国际化造成的 欢迎pr
