### ISSUE TITLE
5.0和4.X的区别

### ISSUE THREAD

**Issue by lotherli** [pure-admin/vue-pure-admin#863]
### 描述问题 (Describe the problem)

大佬，问个问题，
我现在使用的是4.5非国际化精简版本，后期你5.0发布后，我只需要更新代码（类似于打补丁），还是需要将4.5代码进行大的改动。

### 如何复现该问题 (How to reproduce the problem)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/748

**Comment by xiaoxian521** [comment]
5.0 大改

**Comment by lotherli** [comment]
谢谢答疑🙏

**Comment by xiaoxian521** [comment]
是的
