### ISSUE TITLE
hash、h5模式打包，刷新问题

### ISSUE THREAD

**Issue by 18408288631** [pure-admin/vue-pure-admin#866]
### 描述问题 (Describe the problem)

打包环境hash模式：登录后刷新页面正常；h5模式：登录后刷新页面，请求路径异常

### 如何复现该问题 (How to reproduce the problem)

打包环境hash模式：登录后刷新页面正常；h5模式：登录后刷新页面，请求路径异常
![Uploading 1704992576440.png…]()

### 操作系统和浏览器信息 (Operating system and browser information)

google游览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/865#issuecomment-1888191929
全局搜 h5 东西放那 免费且保姆级提供好给你 自己动手丰衣足食
