### ISSUE TITLE
完整版登录时报错

### ISSUE THREAD

**Issue by spring680611** [pure-admin/vue-pure-admin#868]
### 描述问题 (Describe the problem)

vue-pure-admin/node_modules/.pnpm/vite-plugin-fake-server@2.0.0/node_modules/vite-plugin-fake-server/dist/index.mjs:661
                                responseHeaders: new Headers({ ...globalResponseHeaders, ...responseHeaders }),
                                                     ^

ReferenceError: Headers is not defined

### 如何复现该问题 (How to reproduce the problem)

不知道

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
按此安装node版本 https://github.com/pure-admin/vue-pure-admin/blob/main/package.json#L165

**Comment by xiaoxian521** [comment]
或者直接用这个版本 https://github.com/pure-admin/vue-pure-admin/blob/main/.nvmrc
