### ISSUE TITLE
请问有交流群吗？后端学习前端遇到不少问题

### ISSUE THREAD

**Issue by AppleVinegar** [pure-admin/vue-pure-admin#870]
### 描述问题 (Describe the problem)

多个已加载的table标签页，在点击标签页切换时会自动刷新并触发了onMounted函数，我想要不刷新在哪边修改呢？

### 如何复现该问题 (How to reproduce the problem)

在多个已加载的table的标签页来回切换时会自动刷新，并触发了onMounted 函数

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
q群 779709725
