### ISSUE TITLE
标签判断布尔类型写成了字符串类型

### ISSUE THREAD

**Issue by komorebi-cqd** [pure-admin/vue-pure-admin#875]
### 描述问题 (Describe the problem)

在vue-pure-admin中layout下面的hooks下面的useTags中[https://github.com/pure-admin/vue-pure-admin/blob/main/src/layout/hooks/useTag.ts](url)，某些时候项目加载过快还没从浏览器中读取到hideTabs的值，就会直接用了ref("false")，但这是字符串false就代表了true，就会出现顶部导航条离内容很远的情况，tags也被隐藏了
![微信图片_20240118143328](https://github.com/pure-admin/vue-pure-admin/assets/76776644/c9da73da-95ac-4603-abb6-14466ca314e6)

### 如何复现该问题 (How to reproduce the problem)

偶发的，我也不知道应该怎么重现，但是我项目访问的人数较多，就老有人反馈。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 看样子 你自己改造很多 请自行排查 目前只解决确定性bug 目前很忙 没空帮你们排查 抱歉
