### ISSUE TITLE
vue-pure-admin里面的

### ISSUE THREAD

**Issue by komorebi-cqd** [pure-admin/vue-pure-admin#876]
### 描述问题 (Describe the problem)

vue-pure-admin里面的这段判断代码，ref("false")写成字符串了，会导致tag消失，不是我改造的，是你项目里面的，没希望你能帮我排查，只是希望你能改一下你的问题，别以后别人用你的项目出现我这样的问题还找不到问题在哪。
[问题出现地方的链接](https://github.com/pure-admin/vue-pure-admin/blob/main/src/layout/hooks/useTag.ts)
```ts

const showTags =
    ref(
      storageLocal().getItem<StorageConfigs>(
        `${responsiveStorageNameSpace()}configure`
      ).hideTabs
    ) ?? ref("false");
```

### 如何复现该问题 (How to reproduce the problem)

多用多刷新就会出现

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
当然你也可以贡献代码啊 	`false`为字符串 那你改成boolean 看看能不能复现 如果不能提个pr和视频 岂不是更好
我们目前没时间排查这些难以复现的东西 很忙 抱歉

**Comment by xiaoxian521** [comment]
不光是针对你 所有人提issues 必须得有说服力
pr更是如此
