### ISSUE TITLE
增加自定义主题后，面板可以显示主题，但是如果切换了一次，再想切换其他，就不能切换了

### ISSUE THREAD

**Issue by yuanjianhua** [pure-admin/vue-pure-admin#890]
### 描述问题 (Describe the problem)

增加自定义主题后，面板可以显示主题，但是如果切换了一次，再想切换其他，就不能切换了。不切换自定义的主题，其他的默认主题可以随意切换。
@pureadmin/theme 下的toBrowerEnvs.js下multipleScopeVars有值，调试的时候发现只有默认的主题，并没有获取到最新的，还请大佬指点

### 如何复现该问题 (How to reproduce the problem)

新增主题色，重新编译

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考 https://github.com/pure-admin/vue-pure-admin/commit/ba1f655b6e8db3742a87422d1ffbc1e4a61211cb

**Comment by yuanjianhua** [comment]
代码如下：
1、添加主题色
![image](https://github.com/pure-admin/vue-pure-admin/assets/948641/46a40443-8a46-4b28-b583-cb35a7d0bc80)
![image](https://github.com/pure-admin/vue-pure-admin/assets/948641/78e73945-1848-4793-be77-a973f2d2a506)
2、编译后的multipleScopeVars值，包含添加的yellow
![image](https://github.com/pure-admin/vue-pure-admin/assets/948641/3f21c253-8c87-4aab-b16d-4e9f03de9f62)
3、调试的值，没有yellow
![image](https://github.com/pure-admin/vue-pure-admin/assets/948641/f0897eca-e903-445d-8c06-2fbae3831512)

**Comment by xiaoxian521** [comment]
不好意思 目前很忙 在我提个的那个pr中 完全删除yellow 也就意味着 可以完全添加任何主题配色，请自行研究代码 再改那里的时候还是非常容易的
