### ISSUE TITLE
请问这是我使用错误么？关于动态路由

### ISSUE THREAD

**Issue by wplct** [pure-admin/vue-pure-admin#895]
### 描述问题 (Describe the problem)

后端传的路由如下
`
{
    "success": true,
    "data": [
        {
            "path": "/vadmin",
            "meta": {
                "title": "\u7cfb\u7edf\u7ba1\u7406",
                "icon": "",
                "rank": 0
            },
            "children": [
                {
                    "path": "/vadmin/user",
                    "component": "vadmin/list/index",
                    "name": "vadmin_user",
                    "meta": {
                        "title": "\u7528\u6237\u7ba1\u7406",
                        "icon": "",
                        "rank": 0
                    }
                },
                {
                    "path": "/vadmin/group",
                    "component": "vadmin/list/index",
                    "name": "vadmin_group",
                    "meta": {
                        "title": "\u7ec4\u7ba1\u7406",
                        "icon": "",
                        "rank": 0
                    }
                }
            ]
        }
    ]
}

`

经过处理后，会导致定位到其他view导致错误

后修改 /src/router/utils.ts:313

`      const index = v?.component
        ? modulesRoutesKeys.findIndex(ev => ev.includes(v.component as any))
        : modulesRoutesKeys.findIndex(ev => ev.includes(v.path));
      v.component = modulesRoutes[modulesRoutesKeys[index]];
`

修改为

`
      const index = v?.component
        ? modulesRoutesKeys.findIndex(ev => ev.includes(v.component as any))
        : modulesRoutesKeys.findIndex(ev => ev.includes(v.path));
      if (!v.children || !v.children.length) {
        v.component = modulesRoutes[modulesRoutesKeys[index]];
      }
`

后修复
是否是我传的路由有问题

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/11318344/acefb97a-fb0f-4184-968a-e05d1a91f66b)
这是我的view目录情况

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/
