### ISSUE TITLE
关于部署到线上环境后的发生的性能问题

### ISSUE THREAD

**Issue by cnelf** [pure-admin/vue-pure-admin#896]
### 描述问题 (Describe the problem)

项目部署后发现打开部分页面白屏时间过长，最终定位到的问题是由于某段正则表达式执行时间过长
![77667D67-3F70-4854-AE9E-0803B5715FA2](https://github.com/pure-admin/vue-pure-admin/assets/42031617/af58cf2f-7f01-45e2-a8fe-3e941da67061)
![lQLPJwMAXwUwYnfMiM0G0LAmleZug5qedwWhkwclbEsA_1744_136](https://github.com/pure-admin/vue-pure-admin/assets/42031617/3ca07bb3-734e-4ddb-9e74-c9cfd1db9175)

追溯来源后发现是从 `src/utils/sso.ts` 文件引入的，将其注释后再重新部署解决了白屏问题
![9A316F03-69A5-45DA-9894-F690E9CE2FCB](https://github.com/pure-admin/vue-pure-admin/assets/42031617/216801fd-8e6f-41c0-bb7f-e5c1ee609fe9)

这边也请排查一下是否存在该问题

### 如何复现该问题 (How to reproduce the problem)

将项目部署到线上环境后即可复现

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
我建议是多看文档 注意规范 和注意点 文档这么详细 https://yiming_chang.gitee.io/pure-admin-doc/pages/sso/
