### ISSUE TITLE
精简版本与非精简版本 readme 是同一个吗

### ISSUE THREAD

**Issue by leafgrey** [pure-admin/vue-pure-admin#902]
### 描述问题 (Describe the problem)

精简版 国际化与非国际化 容易混淆 一摸一样的 readme

### 如何复现该问题 (How to reproduce the problem)

git clone 从链接 无法区分 打开仓库之后显示的 readme文件也是一样的

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
readme 对于你项目没有影响
