### ISSUE TITLE
布局小bug

### ISSUE THREAD

**Issue by qq2466070039** [pure-admin/vue-pure-admin#903]
### 描述问题 (Describe the problem)

宽度缩小为760px以后切换为竖向布局，刷新以后再放大无法回到默认设置的横向布局

修改方案
改动以下代码
原代码
`width <= 760 ? setTheme("vertical") : setTheme(useAppStoreHook().layout);`
新代码
`width <= 760 ? setTheme("vertical") : width <= 760 ? setTheme("vertical") : setTheme($config.Layout ?? "vertical");`

### 如何复现该问题 (How to reproduce the problem)

宽度缩小为760px以后切换为竖向布局，刷新以后再放大无法回到默认设置的横向布局

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
上面新代码逻辑上是有突出的 优化后 欢迎pr
