### ISSUE TITLE
eslint报错

### ISSUE THREAD

**Issue by pan52yu** [pure-admin/vue-pure-admin#904]
## 在 vscode 打开，eslint 会报错，每个文件的第一行都会报错
![image](https://github.com/pure-admin/vue-pure-admin/assets/76894844/a00e6153-6a43-47df-87e1-51d2173ffe7f)
![image](https://github.com/pure-admin/vue-pure-admin/assets/76894844/f8fc7170-d19f-42aa-b9be-86cf5ab12bec)

### 如何复现该问题 (How to reproduce the problem)

vscode 打开，eslint 报错，每个文件的第一行都会报错

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看以往issues
