### ISSUE TITLE
monorepo下构建失败

### ISSUE THREAD

**Issue by 18259669383** [pure-admin/vue-pure-admin#905]
### 描述问题 (Describe the problem)

使用的是qiankun，项目的目录是
packages
            主应用
            子应用1
            子应用2
单独运行是不会出现问题，
如果在monorepo下运行会出现
![图片](https://github.com/pure-admin/vue-pure-admin/assets/93261537/8e0f3818-ecba-4491-81f7-4fc413a075df)
没有想到问题的原因

### 如何复现该问题 (How to reproduce the problem)

因为已经对接后台，复现的话有点麻烦。作者看到，就帮忙提供出现这种问题的猜想就行，有去看过你推荐的那个微前端的库了，但并没有看出什么问题，有可能这个就是个很简单的问题而已

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看以往issues

**Comment by xiaoxian521** [comment]
你这个问题啊 需要自行安装`vue-demi`

**Comment by 18259669383** [comment]
> 你这个问题啊 需要自行安装`vue-demi`

有尝试过安装过这个依赖（也是不行），但我觉得应该不是这个原因，因为不装这个依赖，单独运行是可行的，所以很费解

**Comment by xiaoxian521** [comment]
那我就不知道了 我的微服务版本是没问题的 请自行研究

**Comment by 18259669383** [comment]
我将 cdn 和 pure-admin-theme 两者去除掉可以解决在 monorepo 实现构建

**Comment by ruan-cat** [comment]
我今天也用monorepo架构来运行vue-pure-admin项目了，也出现了相同的错误。这是 [vite-plugin-cdn-import](https://github.com/MMF-FE/vite-plugin-cdn-import/issues/60) 的故障。
