### ISSUE TITLE
”关闭标签页“处理逻辑的问题

### ISSUE THREAD

**Issue by Humilitas** [pure-admin/vue-pure-admin#906]
### 描述问题 (Describe the problem)

`src/layout/components/tag/index.vue` 
```vue
function deleteMenu(item, tag?: string) {
  deleteDynamicTag(item, item.path, tag);
  handleAliveRoute(route as ToRouteType);
}
``` 

此处` handleAliveRoute(route as ToRouteType);`处理的总是当前路由（对应着当前打开的标签页），意味着关闭其他标签页时也当成关闭当前标签页来处理了。
 

### 如何复现该问题 (How to reproduce the problem)

查看代码：`src/layout/components/tag/index.vue` 

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
提供复现视频 而不是简单的描述

**Comment by Humilitas** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/26362027/24b80814-df64-421a-9eab-1dd720f657de)

比如说，点击关闭“消息提示组件”页面，`handleAliveRoute`处理缓存路由时传入的是当前页面（“瀑布流无限滚动组件”）的信息

**Comment by xiaoxian521** [comment]
啊？ 谢谢反馈，等待确认哈 目前太忙了 可能年后处理吧
