### ISSUE TITLE
pnpm替换为npm后启动异常

### ISSUE THREAD

**Issue by yoh310** [pure-admin/vue-pure-admin#909]
### 描述问题 (Describe the problem)

pnpm替换为npm后启动异常，package.json配置及异常如图
![error](https://github.com/pure-admin/vue-pure-admin/assets/35712597/6a8bf0b9-442a-4a4c-b6e8-77c010d44423)

### 如何复现该问题 (How to reproduce the problem)

按照文档说明替换package.json参数后初始化、执行npm run dev命令

### 操作系统和浏览器信息 (Operating system and browser information)

windows环境
node版本 v17.9.1

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/874#issuecomment-1897766311
