### ISSUE TITLE
useEcharts 通过数据集绘制图表不起做用

### ISSUE THREAD

**Issue by ivanberry** [pure-admin/vue-pure-admin#910]
### 描述问题 (Describe the problem)

数据来源Echart官网：

option = {
  legend: {},
  tooltip: {},
  dataset: {
    // Provide a set of data.
    source: [
      ['product', '2015', '2016', '2017'],
      ['Matcha Latte', 43.3, 85.8, 93.7],
      ['Milk Tea', 83.1, 73.4, 55.1],
      ['Cheese Cocoa', 86.4, 65.2, 82.5],
      ['Walnut Brownie', 72.4, 53.9, 39.1]
    ]
  },
  // Declare an x-axis (category axis).
  // The category map the first column in the dataset by default.
  xAxis: { type: 'category' },
  // Declare a y-axis (value axis).
  yAxis: {},
  // Declare several 'bar' series,
  // every series will auto-map to each column by default.
  series: [{ type: 'bar' }, { type: 'bar' }, { type: 'bar' }]
};

替换view/components/chart/bar.vue option 数据集写法不会绘制图片，但是更改为普通的数据方式，会渲染

### 如何复现该问题 (How to reproduce the problem)

更改数据模式为以上的形式即可

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://pure-admin-utils.netlify.app/hooks/useECharts/useECharts

**Comment by xiaoxian521** [comment]
对应问题在对应仓库提问
