### ISSUE TITLE
自适应内容高度未处理页脚

### ISSUE THREAD

**Issue by mynetfan** [pure-admin/vue-pure-admin#911]
### 描述问题 (Describe the problem)

当显示页脚时，表格的自适应高度表现不正确，页面和表格都会出现滚动条。

### 如何复现该问题 (How to reproduce the problem)

测试地址：
https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/high

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
非页脚问题，自行调整 offsetBottom

**Comment by xiaoxian521** [comment]
已改为默认 [将页脚放在一屏可视区](https://github.com/pure-admin/vue-pure-admin/commit/fc9feb311fd4fa40ddaf5ce8792a42df085c9f52)
