### ISSUE TITLE
这个开源框架有微信交流群吗？

### ISSUE THREAD

**Issue by dragony111** [pure-admin/vue-pure-admin#912]
### 描述问题 (Describe the problem)

如果能有个微信在线交流群就好了，管理员能否拉一个微信技术交流群，方便探讨和咨询。

### 如何复现该问题 (How to reproduce the problem)

如果能有个微信在线交流群就好了，管理员能否拉一个微信技术交流群，方便探讨和咨询。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
多个交流群已满 精力有限 不再提供任何交流群
