### ISSUE TITLE
ReDialog 默认的“取消”、“确定”按钮会触发两次 closeDialog

### ISSUE THREAD

**Issue by liu-jia-yi** [pure-admin/vue-pure-admin#913]
### 描述问题 (Describe the problem)

因为默认的“取消”、“确定”按钮会调用 closeDialog，同时因为 el-dialog 监听了 close 事件，handleClose 函数内也调用了 closeDialog，此时如果定义了 closeCallBack 回调函数，那么该回调函数就会执行两次。

### 如何复现该问题 (How to reproduce the problem)

比如 [示例页面](https://yiming_chang.gitee.io/vue-pure-admin/#/components/dialog) 中“关闭后的回调”弹窗，点击“取消”或“确定”后，都会弹出两个 message

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
谢谢反馈 可能是el dialog又更新了啥 节后解决

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/86ce1681c716f7355b5253794b341f1013e18e55#diff-4d64e4073f44bac7ad4b8a099090c57de72a73bedaf1ea048c7904c72c0eb577L93)
