### ISSUE TITLE
精简版的代码好像还没有同步最新版本的4.5.0版本。

### ISSUE THREAD

**Issue by dragony111** [pure-admin/vue-pure-admin#920]
### 描述问题 (Describe the problem)

在用精简版非国际化版本开发中，发现这个精简版的的代码好像还没有同步最新版本的4.5.0版本。

### 如何复现该问题 (How to reproduce the problem)

大概什么时候有新的精简版同步

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="929" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/83f93502-b14a-42fa-9a4c-fb131000b59c">

**Comment by dragony111** [comment]
5.0版本发布后，现在项目4.5的版本能平滑升级到5.0吗？

**Comment by shang-zhen** [comment]
使用文件对比工具升级完了,大概麻烦的地方就是mock文件。
