### ISSUE TITLE
cellRenderer函数在ts下突发警告

### ISSUE THREAD

**Issue by flowerwOw0316** [pure-admin/vue-pure-admin#925]
### 描述问题 (Describe the problem)

更新"@pureadmin/table": "^3.0.0"， "element-plus": "2.5.1" 出现ts错误
![QQ截图20240222101343](https://github.com/pure-admin/vue-pure-admin/assets/50901029/74579b2b-5193-42c6-80f8-3a6910f00f76)

### 如何复现该问题 (How to reproduce the problem)

webstorm2023.3.4打开后

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应库提问
