### ISSUE TITLE
https://pure-admin.github.io/pure-admin-table/ 这个地址的示例在哪里？ 

### ISSUE THREAD

**Issue by JiaMingJia** [pure-admin/vue-pure-admin#927]
### 描述问题 (Describe the problem)

https://pure-admin.github.io/pure-admin-table/ 这个地址的代码在哪里？ 我在项目的代码没有找到相应的示例。

### 如何复现该问题 (How to reproduce the problem)

https://pure-admin.github.io/pure-admin-table/ 这个地址的代码在哪里？ 我在项目的代码没有找到相应的示例。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/pure-admin-table/blob/main/src/columns.tsx#L36
