### ISSUE TITLE
能否为 后端传来的 前端尚未实现的 路由菜单 添加“建设中……”视图？

### ISSUE THREAD

**Issue by upr1ght** [pure-admin/vue-pure-admin#928]
### 描述问题 (Describe the problem)

导航菜单 一般在项目设计阶段就确定下来，但是前后端的开发需要根据客户需求实现，且前后端分离开发，实现步调可能不一致。 能否为 后端传来的 前端尚未实现的 路由菜单 添加“建设中……”视图？

### 如何复现该问题 (How to reproduce the problem)

这是一个新的功能需求，不是BUG

### 操作系统和浏览器信息 (Operating system and browser information)

这是一个新的功能需求，不是BUG

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
这种业务代码很简单 请自行实现
