### ISSUE TITLE
pure-admin-table 表头设置为多语言后，表头的列设置功能无法展示出列名称

### ISSUE THREAD

**Issue by JiaMingJia** [pure-admin/vue-pure-admin#931]
### 描述问题 (Describe the problem)

pure-admin-table 表头设置为多语言后，表头的列设置功能无法展示出列名称
![image](https://github.com/pure-admin/vue-pure-admin/assets/149217352/62012585-1953-40b0-ad74-8e18c637da8c)

### 如何复现该问题 (How to reproduce the problem)

pure-admin-table 表头设置为多语言后，表头的列设置功能无法展示出列名称

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/52103ab52d04c963b68af4dd3d69fc8c44673dae)
