### ISSUE TITLE
.husky 的问题

### ISSUE THREAD

**Issue by yzg-daily** [pure-admin/vue-pure-admin#932]
### 描述问题 (Describe the problem)

野生程序员一名， 对于.husky没有用过。文档中能不能增加点这个的说明？
我想把这个项目保持一下自己用，新建了仓库提交，所有的文件都需要提交（没有fork）。git提交的的时候一直无法通过验证，代码量太多了。我是先删除了 .husky. 请问一下还有没有其他办法解决？

### 如何复现该问题 (How to reproduce the problem)

新建了仓库提交，所有的文件都需要提交

### 操作系统和浏览器信息 (Operating system and browser information)

window 10

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
仔细看文档 什么都有 新手多看文档
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#husky-%E6%98%AF%E4%BB%80%E4%B9%88-%E5%8F%AF%E4%BB%A5%E5%88%A0%E9%99%A4-husky-%E6%8F%90%E4%BA%A4%E5%89%8D%E6%A0%A1%E9%AA%8C%E5%90%97-%E5%A6%82%E4%BD%95%E5%BD%BB%E5%BA%95%E5%88%A0%E9%99%A4
