### ISSUE TITLE
菜单管理的样式不兼容移动端

### ISSUE THREAD

**Issue by dnslin** [pure-admin/vue-pure-admin#933]
### 描述问题 (Describe the problem)

菜单管理的 修改，新增的模态框 样式在移动端下没有自适应

### 如何复现该问题 (How to reproduce the problem)

使用 手机 访问网站

### 操作系统和浏览器信息 (Operating system and browser information)

安卓12 chrome 浏览器 

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
移动端的兼容处理是针对整体框架，而不是业务
这本身就是以`pc`端为主，移动端建议用别的`ui`库

**Comment by dnslin** [comment]
我的建议是在移动端的情况下 这里访问自动全屏，全屏的样式是没有问题的
![Screenshot_2024-02-26-23-37-34-481_com android chrome](https://github.com/pure-admin/vue-pure-admin/assets/49158572/f171cbf1-52be-4b00-b3b3-2e2e31687791)

**Comment by xiaoxian521** [comment]
不错的建议 后续处理
