### ISSUE TITLE
提几个建议并不是bug

### ISSUE THREAD

**Issue by leafkevin** [pure-admin/vue-pure-admin#934]
### 描述问题 (Describe the problem)

1.能够提供在.vue文件，不使用tsx hooks的页面示例，tsx有写业务逻辑实现比较麻烦。
2.上面的tab页签，点击已存在的tab页签，每次都会刷新，这样不好，比如：我要编辑当前的tab页签内容，但是一些数据，我要参考已经打开的tab页签的内容，刷新了参考的内容就是丢失了。可以在tab页签上面，增加刷新小图标，默认不刷新。
3.目前新增，编辑页面，都是openDailog方式，能否提供一个新增、编辑时，打开一个页面，同时上面的tab页签，也会相应增加的示例呢。

### 如何复现该问题 (How to reproduce the problem)

只是建议，并不是bug

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前只解决bug

**Comment by xiaoxian521** [comment]
你提的三点 多看看示例 都能写出来 刚入手就多看示例 和文档
