### ISSUE TITLE
我的问题

### ISSUE THREAD

**Issue by duankan1** [pure-admin/vue-pure-admin#935]
### 描述问题 (Describe the problem)

作者大大，我是一个新手前端，觉得你的项目非常的，但是我在看你的代码时候，找不到在哪里配置请求的域名，一般我看都是在env文件配置的，但是你那里没有，能告知一下这个项目在哪里配置吗

### 如何复现该问题 (How to reproduce the problem)

111，感谢作者大大

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
新手多看文档哈
https://yiming_chang.gitee.io/pure-admin-doc/pages/request/#%E5%A6%82%E4%BD%95%E4%B8%8E%E5%90%8E%E5%8F%B0%E8%81%94%E8%B0%83
