### ISSUE TITLE
http请求的问题

### ISSUE THREAD

**Issue by yzg-daily** [pure-admin/vue-pure-admin#937]
### 描述问题 (Describe the problem)

vite 中设置了代理，请求返回了项目的index.html

### 如何复现该问题 (How to reproduce the problem)

我在 /src/view/xxx/components/cat.vue 组件中引入了 
```vue
 import { http } from "@/utils/http";
import { baseUrlApi } from "@/api/utils";

const getCode = async () => {
  console.log(http.request);
  try {
    const res = await http.request("get", baseUrlApi("login/login"), {});
    console.log(res);
  } catch (e) {
    console.log(e);
  }
};
```

代理
```js
proxy: {
        "/supplier": {
          target: VITE_BASE_URL,
          changeOrigin: true
        }
      },
```
请求一直返回项目的index.html

### 操作系统和浏览器信息 (Operating system and browser information)

windows 10 chrome

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/request/#%E5%A6%82%E4%BD%95%E4%B8%8E%E5%90%8E%E5%8F%B0%E8%81%94%E8%B0%83
