### ISSUE TITLE
关联问题937

### ISSUE THREAD

**Issue by yzg-daily** [pure-admin/vue-pure-admin#939]
### 描述问题 (Describe the problem)

我已经按照文档设置了代理和uilts.ts，请求还是有问题

### 如何复现该问题 (How to reproduce the problem)

组件内请求接口，响应结果是index.html的字符串。配置了代理应该是返回接口数据才对。有接口可以正常访问。
并且有时候修改代码之后缓存很严重，得强制刷新才可以。
有没有QQ或者微信群之类的。发一个。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
类似问题 如果实在不懂 参考 https://yiming_chang.gitee.io/pure-admin-doc/pages/opensource/
