### ISSUE TITLE
页面跳转的时候，底部有个滚动框

### ISSUE THREAD

**Issue by nineaiyu** [pure-admin/vue-pure-admin#941]
### 描述问题 (Describe the problem)

页面跳转的时候，底部有个滚动框，页面渲染之后，滚动框就消失了
![微信截图_20240228102253](https://github.com/pure-admin/vue-pure-admin/assets/19207867/af2ec6fb-e1da-47db-9e55-1acd138097fc)

### 如何复现该问题 (How to reproduce the problem)

https://yiming_chang.gitee.io/vue-pure-admin/#/components/upload
点击连接，这两个来回点击，就可以看到底部的滚动框
![image](https://github.com/pure-admin/vue-pure-admin/assets/19207867/5d92ed30-d044-42f2-9b34-66c003710b5c)

### 操作系统和浏览器信息 (Operating system and browser information)

edge浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
非bug问题 mac无法复现 欢迎pr
