### ISSUE TITLE
@pureadmin/utils 的 debounce 函数

### ISSUE THREAD

**Issue by HuangKaiSong** [pure-admin/vue-pure-admin#942]
### 描述问题 (Describe the problem)

返回的函数缺失 fn 的类型

### 如何复现该问题 (How to reproduce the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/72957518/96d88a87-0cde-40ae-a5ff-4dbd503d2904)

![image](https://github.com/pure-admin/vue-pure-admin/assets/72957518/bfeb6a6a-5e43-414c-8444-1ad75ffaffbf)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应地方提问 https://github.com/pure-admin/pure-admin-utils-docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
