### ISSUE TITLE
可以添加微软monaco-editor吗

### ISSUE THREAD

**Issue by 1402564807** [pure-admin/vue-pure-admin#945]
### 描述问题 (Describe the problem)

可以添加微软monaco-editor吗 我试着自己添加了下，最新的0.47.0会报错  只能添加0.33.0的版本

### 如何复现该问题 (How to reproduce the problem)

最新的0.47.0会报错

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
项目不影响组件 自行探索哈
