### ISSUE TITLE
初次拉取项目，使用`vscode`时`eslint`报错

### ISSUE THREAD

**Issue by skyline523** [pure-admin/vue-pure-admin#953]
### 描述问题 (Describe the problem)

文档无记录eslint相关问题或文章，已安装项目推荐vscode插件，问题仍然存在

### 如何复现该问题 (How to reproduce the problem)

克隆项目安装依赖eslint报错

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考以往issues哈 这种问题我们没法复现 需要自己研究下哈 
可以参考这种做法：
先安装依赖 然后执行`pnpm lint` 没问题再执行 `pnpm typecheck` 
上面两个命令执行下来 没有报错 说明非代码问题 而是你vscode的配置问题 自行研究下哈

**Comment by skyline523** [comment]
能康康你的vscode配置吗

**Comment by xiaoxian521** [comment]
正常情况下不需要特别的配置

<img width="980" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/2c2a7513-d5fd-448d-a3e9-b6f1be6caeb6">

这个文件就是我的配置

**Comment by skyline523** [comment]
好的，感谢

**Comment by skyline523** [comment]
问题已解决，项目使用的配置文件是eslint.config.ts，当前版本e's'lin'teslint不支持该格式配置文件，需要在vscode配置中打开以下配置：
![image](https://github.com/pure-admin/vue-pure-admin/assets/76251617/0308bde3-d345-467d-bf89-bac4226ab9a1)

**Comment by skyline523** [comment]
也建议作者有时间可以把类似配置文件都改成如`.eslintrc.js`格式的文件，以防止这种错误发生

**Comment by xiaoxian521** [comment]
怎么说呢 多看看代码或者记录哈 改掉都是有原因的 我们仓库非常新
`.eslintrc.js`配置文件将在`eslint v9`废弃 https://zh-hans.eslint.org/docs/latest/use/configure/configuration-files
https://github.com/pure-admin/vue-pure-admin/pull/786

**Comment by skyline523** [comment]
哈哈哈好的
