### ISSUE TITLE
pure-table没有sort-change事件吗？

### ISSUE THREAD

**Issue by xxxx96923** [pure-admin/vue-pure-admin#959]
### 描述问题 (Describe the problem)

我的分页数据要走接口的，没有sort-change事件，只能排序本页的话，那就不符合我的项目的需求了

### 如何复现该问题 (How to reproduce the problem)

页面引用pure-table标签，字段设置sortable，点击表头排序，发现表格排序了，但是没有触发排序事件，在node_modules的@pureadmin/table中查看代码，没有找到排序相关事件，文档中也没找到

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应处提问哈 https://github.com/pure-admin/pure-admin-table
