### ISSUE TITLE
有没有js版本的

### ISSUE THREAD

**Issue by WebRookie** [pure-admin/vue-pure-admin#961]
### 描述问题 (Describe the problem)

如题

### 如何复现该问题 (How to reproduce the problem)

提个需求

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#nuxt3-%E7%89%88%E6%9C%AC%E5%92%8C-js-%E7%89%88%E6%9C%AC%E4%BC%9A%E5%BC%80%E5%8F%91%E5%90%97
