### ISSUE TITLE
http/index.ts 文件中 get 和 post 方法的泛型写反了

### ISSUE THREAD

**Issue by jerrybendy** [pure-admin/vue-pure-admin#963]
### 描述问题 (Describe the problem)

在 [176行](https://github.com/pure-admin/vue-pure-admin/blob/main/src/utils/http/index.ts#L176) 和  [185行](https://github.com/pure-admin/vue-pure-admin/blob/main/src/utils/http/index.ts#L185) 中 get 和 post 都有 T 和 P 两个泛型参数，根据正常的使用习惯以及 axios 的泛型定义，应该是数据参数放前面、配置放后面。

```diff
  public post<T, P>(
    url: string,
-    params?: AxiosRequestConfig<T>,
+    params?: AxiosRequestConfig<P>,
    config?: PureHttpRequestConfig
-  ): Promise<P> {
+  ): Promise<T> {
-    return this.request<P>("post", url, params, config);
+    return this.request<T>("post", url, params, config);
  }
```

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前使用没有问题
不过很欢迎你的pr哈

**Comment by jerrybendy** [comment]
使用没问题是因为从来没用过，代码库里面只使用了 `request` 方法，而没有使用过 `get` 和 `post`，所以一直未能发现问题

**Comment by xiaoxian521** [comment]
确实好久没用过了 后面我自己测哈 谢谢提醒

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/commit/abd042afe81e2cd8d0567cd4dd4f1498825ac4e6)
