### ISSUE TITLE
pure-admin-thin，请问components下的ReDialog打开的表单页能回车提交吗？

### ISSUE THREAD

**Issue by xxxx96923** [pure-admin/vue-pure-admin#964]
### 描述问题 (Describe the problem)

需求是点击回车即可触发确认按钮，提交整个表单

### 如何复现该问题 (How to reproduce the problem)

目前使用版本：4.5.0

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
参考下图 里面有所有用法
<img width="970" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/35bb873c-551c-4106-95b3-8352daa0bec0">

**Comment by xxxx96923** [comment]
这里面看过，没找到回车事件，四个表单也试过了，都没有触发回车事件，那是没有吗？那要实现，是不是要把现在的底部按钮隐藏起来，然后在表单页自己写按钮？

**Comment by xiaoxian521** [comment]
看 https://element-plus.org/zh-CN/component/dialog.html 我们基于这个封装 这个有我们就有

**Comment by xxxx96923** [comment]
好的，谢谢大佬

**Comment by xxxx96923** [comment]
其实就是有没有触发默认的确定按钮的方法，只是目前的需求限定了回车而已

**Comment by xxxx96923** [comment]
解决了，我改了一点ReDialog的内容
![QQ截图20240318105209](https://github.com/pure-admin/vue-pure-admin/assets/37437202/225cd7f8-a6b9-4c5e-a7e0-29c85db7d3b2)
![QQ截图20240318105234](https://github.com/pure-admin/vue-pure-admin/assets/37437202/2abbf6df-727d-4311-bcfc-c26f4f8004b7)

**Comment by xxxx96923** [comment]
改了下handleEnter中内容，`if (!options?.hideFooter && options?.footerRenderer) return;`
