### ISSUE TITLE
精简版5.1.0本地启动一段时间后刷新页面后菜单栏一直显示加载圈

### ISSUE THREAD

**Issue by xiaobu-zefa** [pure-admin/vue-pure-admin#966]
### 描述问题 (Describe the problem)

控制台等无任何报错, 经排查后发现是获取不到异步路由菜单导致页面一直显示加载;
之前的版本路由菜单是每次刷新页面都会重新加载, 升级后发现换成了使用 localStorage 存储, 不知道是不是这个原因;
于是手动将使用 localStorage 的地方换回了使用 sessionStorage, 可以正常使用了, 刷新的时候会重新调用 get-async-route 重新获取菜单

### 如何复现该问题 (How to reproduce the problem)

不知道怎么复现, 本地启动一段时间后就会出现

### 操作系统和浏览器信息 (Operating system and browser information)

window11 
chrome

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
完整版用这么久没发现该问题哈 如果能复现 可以@我 我将调查并解决 
精简版同步流程很严格 所以精简版有问题完整版肯定能复现哈

**Comment by Thresh-Frazier** [comment]
建议作者在手册以及vite.config.ts中添加一下：
如设置了代理的前缀时，注意请求白名单的相关配置
另建议考虑将白名单独立为单独配置项设置
