### ISSUE TITLE
pure-table headerRenderer和多级表头不能共存

### ISSUE THREAD

**Issue by ail994** [pure-admin/vue-pure-admin#967]
### 描述问题 (Describe the problem)

pure-table headerRenderer和多级表头不能共存，只有多级表头生效，headerRenderer不起作用

### 如何复现该问题 (How to reproduce the problem)

  const columns: TableColumnList = [
    {
      label: "日期",
      prop: "date"
    },
    {
      label: "姓名",
      prop: "name"
    },
    {
      label: "地址",
      prop: "address"
    },
    {
      align: "right",
      children: [
        {
          label: "地址",
          prop: "address"
        },
      ],
      // 自定义表头
      headerRenderer: () => (
        <el-input
          v-model={search.value}
          size="small"
          clearable
          placeholder="Type to search"
        />
      )
   }]

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
对应问题在对应仓库提问 https://github.com/pure-admin/pure-admin-table
