### ISSUE TITLE
5.1.0版本点击菜单栏beforeEach会被执行两次

### ISSUE THREAD

**Issue by tombingo** [pure-admin/vue-pure-admin#972]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/13918652/002b56c8-5e24-49e4-b609-8573ddab0af8)
解决方案：删除el-menu的router属性
![image](https://github.com/pure-admin/vue-pure-admin/assets/13918652/1a8d911b-02a0-4fe2-a3a5-08bbb2667403)
![image](https://github.com/pure-admin/vue-pure-admin/assets/13918652/e33aa237-19fd-4c1a-aa01-dfb3fbab238b)

### 如何复现该问题 (How to reproduce the problem)

打印beforeEach日志

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
有相同isseus 自行找一下 这个又没啥影响

**Comment by xiaoxian521** [comment]
应该说一直都这样吧
