### ISSUE TITLE
点击标签调整页面触发两次组件的onBeforeRouteLeave

### ISSUE THREAD

**Issue by wanghaochun** [pure-admin/vue-pure-admin#973]
### 描述问题 (Describe the problem)

基于4.5.0精简版，在单组件内使用路由onBeforeRouteLeave，在点击其它标签触发跳转时，会触发两次onBeforeRouteLeave。通过左侧菜单点击不会出现该问题。

### 如何复现该问题 (How to reproduce the problem)

任意单组件内使用onBeforeRouteLeave，在页面上点击其它标签切换会触发两次该守卫。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
same https://github.com/pure-admin/vue-pure-admin/issues/972

**Comment by wanghaochun** [comment]
> same #972

你好，是点击标签栏切换是才会触发两次，点菜单栏不会。
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/c79b4b9e-908b-439c-972e-0e0968d97fcd)

**Comment by xiaoxian521** [comment]
我之前提交commit有备注记录 但是我没时间去找哈
目前太忙了 计划一堆 
而且这个并不影响什么 
而且这应该是vue-router的问题 根据我的记忆

**Comment by wanghaochun** [comment]
已找到问题所在：
1、先说说背景，我是想在用户离开页面前提醒用户当前数据没保存，让用户做二次确认，用了vueRoute官方的API在组件内声明onBeforeRouteLeave；
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/7e1d1658-57c6-4db3-89f4-cc5d5b6bfcbb)
2、点击菜单栏时（如下）
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/aee4f76e-0efc-4cc3-a621-7e7cd7f8af2d)
弹窗（如下）只会弹一次，无论我点击确定或取消
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/e6060eb1-3e4b-4f79-8dde-0c26ce6160c4)
3、点击标签栏（如下）
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/03a70d27-eddc-4733-a713-e23f86e87b0f)
第一次弹窗选取消后会重复再弹一次
4、最后发现问题在于标签栏点击事件冒泡引起了路由两次跳转
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/0ec6a60f-990a-4707-899f-40cbefbaf008)
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/61b167e7-852f-416f-9509-1ca46cc5cb8f)

临时解决方案：把tagOnClick事件取消后问题不再出现，标签栏切换和菜单跳转均正常
暂时未知该方式会造成什么影响。请看一下。

**Comment by wanghaochun** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/14145922/8f45212c-152a-475b-8147-ca14ea389240)
好像将router-link标签的to属性置空更好，这样标签切换的可点击区域会更大。。当然会有什么影响暂时还未知。
