### ISSUE TITLE
如何从get请求中传入并且获取params参数

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [pure-admin/vue-pure-admin#978]
### 描述问题 (Describe the problem)

定义了get接口，接口外部传入参数，但是后台的接口获取参数是undefined
对于get与post的接口参数定义有什么不一样
![image](https://github.com/pure-admin/vue-pure-admin/assets/87591236/5adf7c4d-07b1-4870-9330-c6d0bc5c3cfe)
![image](https://github.com/pure-admin/vue-pure-admin/assets/87591236/e0c525cf-e8d6-4554-8817-0305f96425f8)
![image](https://github.com/pure-admin/vue-pure-admin/assets/87591236/c0dd2fba-8de9-4638-a14c-d5176f66e86c)

### 如何复现该问题 (How to reproduce the problem)

后台无法在get请求中获取params参数

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
看文档哈 
目前只解决bug
