### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Yolo-00** [pure-admin/vue-pure-admin#979]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/129492349/575c1f6d-b01d-49cf-81eb-1b2618108c08)

### 如何复现该问题 (How to reproduce the problem)

是否考虑给该组件添加拖拽控制高度的功能

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
目前只解决bug 计划很满
