### ISSUE TITLE
倒计时（建议）

### ISSUE THREAD

**Issue by Yolo-00** [pure-admin/vue-pure-admin#981]
### 描述问题 (Describe the problem)

timer.value = setInterval(() => {
     time -= 1;
 }, 1000);
在 setInterval 内开始每秒减一就会出现开始执行递减会有一秒后的延迟执行递减
建议最好是能在开始前执行一次减一操作
time--;
timer.value = setInterval(() => {
     time --;
 }, 1000);

### 如何复现该问题 (How to reproduce the problem)

console.log(new Date().getTime());
let timer = setInterval(() => {
	console.log(new Date().getTime());
	clearInterval(timer);
}, 1000);
![image](https://github.com/pure-admin/vue-pure-admin/assets/129492349/a614c45d-11e0-4728-9afe-6a1562c4e673)

### 验证 (Verify)

- [x] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr哈
目前只处理确定性bug
计划有点多 不好意思哈
