### ISSUE TITLE
顶部菜单模式样式问题

### ISSUE THREAD

**Issue by d-411** [pure-admin/vue-pure-admin#983]
### 描述问题 (Describe the problem)

如果部分路由列表通过接口返回，接口响应时间过长（我测试是50毫秒以上），会导致本该折叠的路由列表未被折叠。
正常：![正常](https://github.com/pure-admin/vue-pure-admin/assets/95357537/f49e9828-7d59-41c2-bb12-74126a5b2964)
异常：
![异常](https://github.com/pure-admin/vue-pure-admin/assets/95357537/4a9b69b7-e5f7-42b0-9722-fa845e352537)

### 如何复现该问题 (How to reproduce the problem)

动态接口响应时间稍微长一点，比如1秒

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
加个loading
欢迎pr
