### ISSUE TITLE
offlineIcon 中添加的图标，离线不可用

### ISSUE THREAD

**Issue by liu-jia-yi** [pure-admin/vue-pure-admin#986]
### 描述问题 (Describe the problem)

由于 offlineIcon.ts 以及路由的 icon 都改为了冒号格式，所以 useRenderIcon 使用了 IconifyIconOnline，经过测试，在模拟的内网环境下，菜单中的图标都不显示了。
![image](https://github.com/pure-admin/vue-pure-admin/assets/20166121/740925e3-a9c7-4a8b-9402-da598042c6ae)
![image](https://github.com/pure-admin/vue-pure-admin/assets/20166121/f464eaa5-fa03-4f3e-81fc-fe793f61a4d4)

### 如何复现该问题 (How to reproduce the problem)

删除 localstorage 中 icon 相关的存储，network 中 block 获取在线图标的三个地址。

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
项目有很多示例 文档也很清晰 自己多看哈
