### ISSUE TITLE
1、图标选择器打不开了。2、pnpm install卡在了canvas:Running install script

### ISSUE THREAD

**Issue by itmeicn** [pure-admin/vue-pure-admin#988]
### 描述问题 (Describe the problem)

1、官网完整版案列，点击‘图标选择器’，没反应js报404:https://yiming_chang.gitee.io/vue-pure-admin/static/js/icon-select-8dgVFFYV.js
2、一直卡住运行不了。node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script...

### 如何复现该问题 (How to reproduce the problem)

1、https://yiming_chang.gitee.io/vue-pure-admin/static/js/icon-select-8dgVFFYV.js
2、下载的github最新的源码，pnpm install

### 操作系统和浏览器信息 (Operating system and browser information)

win10

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
无法复现
