### ISSUE TITLE
登录时卡屏

### ISSUE THREAD

**Issue by zhaoxin1998** [pure-admin/vue-pure-admin#990]
### 描述问题 (Describe the problem)

本地开发一切正常，部署到线上后，给角色添加菜单，页面就会卡住，内存开始飙升，本地调用线上的后台接口一切正常，删除掉角色对应新增的菜单后又恢复正常

### 如何复现该问题 (How to reproduce the problem)

给管理员角色新增几个菜单，保存刷新就会卡住

### 操作系统和浏览器信息 (Operating system and browser information)

谷歌浏览器

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
这种开发没问题 线上有问题 看看自己业务代码 排查一下 我们不会帮助处理这种自己写的业务代码
