### ISSUE TITLE
项目开局关于prettier小小的优化

### ISSUE THREAD

**Issue by you-hengh** [pure-admin/vue-pure-admin#996]
### 描述问题 (Describe the problem)

因为我写过全局 prettier 的配置路径,相信五湖四海的朋友总有和我一样配置 prettier 全局路径配置的
```js
// setting.json
{
  // ...其他配置
  "prettier.configPath": "C:\\Users\\user\\.vscode\\.prettier\\.prettier.json",
}
```
我发现在这样的状态下, 项目自带的 `.prettierrc.js` 无法得到启用, 这样在代码格式化方面就不能做到统一

这个问题我查询了 vscode prettier 插件 在其中[#1033](https://github.com/prettier/prettier-vscode/issues/1033)得到了解决方案

就是在项目的 `.vscode/settings.json` 里面添加一句

```json
{
    "prettier.configPath": ""
}
```
利用工作区优先级高于本地设置优先级 覆盖 prettier.configPath 的配置, 这样就可以在不修改本地 prettier 配置的情况下, 使用项目的提供的 prettier 相关格式化配置了

### 如何复现该问题 (How to reproduce the problem)

如果本地配置了`prettier.configPath`的情况下, 则项目自带的 `.prettierrc.js` 不能生效

### 操作系统和浏览器信息 (Operating system and browser information)

system: win11 专业版 23H2
chrome: 122.0.6261.129
project: pure-admin-thin 5.1.0

补充一下: 可以在Bug repot 模板里 提示复制命令 快速反馈系统版本信息

![image](https://github.com/pure-admin/vue-pure-admin/assets/34816426/41821105-3709-46b9-8d43-0cf867987d32)

![image](https://github.com/pure-admin/vue-pure-admin/assets/34816426/40033805-8841-40ef-9e0d-92e260bb2478)

```bash
npx envinfo --system --npmPackages @pureadmin/cli  --binaries --browsers
```

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
欢迎pr 我们会进一步调查❤️
